"use client";
import { type FormEvent, useState } from "react";
import ServiceAreaEditor from "./ServiceAreaEditor";
import { COUNTIES_BY_STATE, US_STATES, normalizeServiceAreas, type ServiceArea } from "@/lib/featured-businesses/location";
const inputClass="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-200";
export default function FeaturedBusinessRequestForm(){const[state,setState]=useState("MO"),[county,setCounty]=useState(""),[areas,setAreas]=useState<ServiceArea[]>([]),[errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[sending,setSending]=useState(false),[done,setDone]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(sending)return;setSending(true);setErrors({});setMessage("");const form=new FormData(event.currentTarget);const normalized=normalizeServiceAreas(areas,{stateCode:state,countyName:county});form.set("businessState",state);form.set("businessCounty",county);form.set("serviceAreas",JSON.stringify(normalized));form.set("consentConfirmed",form.get("consentConfirmed")?"true":"false");const response=await fetch("/api/featured-business-requests",{method:"POST",body:form});const payload=await response.json().catch(()=>({}));setSending(false);if(!response.ok){setErrors(payload.errors??{});setMessage(payload.error??"Please correct the highlighted information and try again.");return;}setDone(true);}
 if(done)return <section role="status" className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-8"><h2 className="text-3xl font-black text-emerald-950">Thank you!</h2><p className="mt-3 leading-7 text-emerald-900">Your request has been submitted to IDS for review. We will contact you if we need any additional information.</p></section>;
 const error=(key:string)=>errors[key]&&<span className="mt-1 block text-sm font-bold text-red-700">{errors[key]}</span>;
 return <form onSubmit={submit} className="space-y-7 rounded-[2rem] bg-white p-6 shadow-sm sm:p-9"><input className="sr-only" tabIndex={-1} autoComplete="off" name="company" aria-hidden="true"/><section><h2 className="text-2xl font-black">Private contact information</h2><p className="mt-2 text-sm text-slate-600">Used only by IDS to review your request. It is never published.</p><div className="mt-4 grid gap-5 sm:grid-cols-2"><label className="font-bold">Contact Person Name *<input name="contactName" required maxLength={120} className={inputClass}/>{error("contactName")}</label><label className="font-bold">Contact Email *<input name="contactEmail" type="email" required maxLength={254} className={inputClass}/>{error("contactEmail")}</label></div></section><section><h2 className="text-2xl font-black">Public business information</h2><div className="mt-4 space-y-5"><label className="block font-bold">Business Name *<input name="businessName" required maxLength={160} className={inputClass}/>{error("businessName")}</label><label className="block font-bold">Services / Business Description *<textarea name="description" required maxLength={3000} rows={6} className={inputClass}/>{error("description")}</label>
 <div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">Primary Business State *<select required value={state} onChange={e=>{setState(e.target.value);setCounty("")}} className={inputClass}>{US_STATES.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select>{error("businessState")}</label><label className="font-bold">Primary Business County / County-Equivalent *<select required value={county} onChange={e=>setCounty(e.target.value)} className={inputClass}><option value="">Select county</option>{(COUNTIES_BY_STATE[state]??[]).map(item=><option key={item}>{item}</option>)}</select>{error("businessCounty")}</label><label className="font-bold">Business City (Optional)<input name="businessCity" maxLength={120} className={inputClass}/></label><label className="font-bold">ZIP / Postal Code (Optional)<input name="postalCode" maxLength={20} autoComplete="postal-code" className={inputClass}/></label></div>
 <ServiceAreaEditor value={areas} onChange={setAreas}/>{error("serviceAreas")}<label className="block font-bold">Operating Region / Area Served Display Text (Optional)<input name="operatingRegion" maxLength={200} placeholder="Southeast Missouri" className={inputClass}/></label><label className="block font-bold">Public Phone Number (Optional)<span className="mt-1 block text-sm font-normal text-slate-600">Leave blank if you do not want a phone number displayed in your listing.</span><input name="phone" type="tel" maxLength={80} className={inputClass}/></label><label className="block font-bold">Public Street / Mailing Address (Optional)<span className="mt-1 block text-sm font-normal text-slate-600">Home-based and service-area businesses may leave this blank.</span><textarea name="address" maxLength={500} rows={2} className={inputClass}/></label><div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">Website URL (Optional)<input name="websiteUrl" type="url" className={inputClass}/>{error("websiteUrl")}</label><label className="font-bold">Facebook URL (Optional)<input name="facebookUrl" type="url" className={inputClass}/>{error("facebookUrl")}</label></div><label className="block font-bold">Special Offer / Discount (Optional)<textarea name="specialOffer" maxLength={1000} rows={3} className={inputClass}/></label><label className="block font-bold">Logo / Business Image *<input name="logo" required type="file" accept="image/jpeg,image/png,image/webp" className={`${inputClass} file:mr-4 file:rounded-lg file:border-0 file:bg-emerald-700 file:px-4 file:py-2 file:font-bold file:text-white`}/><span className="mt-1 block text-sm font-normal text-slate-600">JPEG, PNG, or WebP. Maximum 5 MB.</span>{error("logo")}</label></div></section>
 <section><label className="block font-bold">Additional Notes for IDS (Optional)<textarea name="additionalNotes" maxLength={2000} rows={4} className={inputClass}/><span className="mt-1 block text-sm font-normal text-slate-600">Private; never shown in the directory.</span></label></section><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 font-bold"><input name="consentConfirmed" required type="checkbox" className="mt-1 h-5 w-5"/>I confirm that I am authorized to submit this business information and logo and authorize IDS to display the submitted public business information and logo if this request is approved.</label>{error("consentConfirmed")}{message&&<p role="alert" className="font-bold text-red-700">{message}</p>}<button disabled={sending} className="min-h-12 rounded-xl bg-emerald-700 px-7 py-3 font-black text-white hover:bg-emerald-800 disabled:opacity-60">{sending?"Submitting…":"Submit Featured Business Request"}</button></form>}
