"use client";
import LinkSetupSubscription from "./LinkSetupSubscription";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ServiceTerms, WarrantyVerified } from "./ServiceTerms";
import { displayDate, displayStatus, serviceButton, serviceFetch, useOperationKey, useServiceTask } from "./ui";
import { serviceMoney } from "@/lib/service/policy";
import type { ServicePricing } from "@/lib/service/types";

type PublicCase = { caseNumber: string; kind: string; status: string; warrantyStatus: string; arrangement: string; paymentAuthorized: boolean; invoice: { status: string; payment_status: string; pricing: ServicePricing; totals: { customerDueCents: number } | null } | null; appointments: { id: string; starts_at: string; ends_at: string; status: string; session_number: number | null }[] };
export function CustomerCase({ token }: { token: string }) {
  const [record, setRecord] = useState<PublicCase | null>(null); const [accepted, setAccepted] = useState(false); const task = useServiceTask(); const { getKey: key } = useOperationKey();
  const url = `/api/service/manage/${encodeURIComponent(token)}`;
  const refresh = useCallback(async () => setRecord(await serviceFetch<PublicCase>(url)), [url]);
  const [loadError, setLoadError] = useState("");
  useEffect(() => { let alive = true; serviceFetch<PublicCase>(url).then(value => { if (alive) setRecord(value); }).catch(error => { if (alive) setLoadError(error.message); }); return () => { alive = false; }; }, [url]);
  const action = (name: string, data: Record<string, unknown> = {}) => task.run(async () => {
    const input = { action: name, ...data }; const result = await serviceFetch<{ url?: string }>(url, { ...input, key: key(input) });
    if (result.url) window.location.assign(result.url); else await refresh();
  });
  if (!record) return <p role="status">{loadError || "Loading your request…"}</p>;
  const billable = record.kind !== "included_support" && record.warrantyStatus !== "verified" && !["warranty_verification", "warranty_not_covered_authorization_required", "cancelled"].includes(record.status);
  return <div className="space-y-6"><p className="text-sm leading-6">Keep this private link. It permits access to this request and its payment actions.</p><section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">{record.caseNumber}</h2><p>Service status: <strong>{displayStatus(record.status)}</strong></p>{record.kind !== "included_support" && <>{record.warrantyStatus === "verified" ? <WarrantyVerified /> : <p>Warranty: {displayStatus(record.warrantyStatus)}</p>}<p>Arrangement: {displayStatus(record.arrangement)}</p><p>Invoice: {displayStatus(record.invoice?.status ?? "not yet available")}</p><p>Payment: {displayStatus(record.invoice?.payment_status ?? "not due")}</p>{record.invoice?.totals && <p className="text-xl font-bold">{["paid", "paid_cash", "refunded", "partially_refunded", "payment_review"].includes(record.invoice.payment_status) ? "Final invoice amount" : "Customer due"}: {serviceMoney(record.invoice.totals.customerDueCents)}</p>}</>}<button className={serviceButton} disabled={task.busy} onClick={() => void task.run(refresh, "Status refreshed.")}>Refresh status</button></section>
    {record.status === "warranty_not_covered_authorization_required" && <section className="space-y-4 rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="text-xl font-black">Warranty was not confirmed</h2><p>Review the rates before deciding. Paid work will require separate payment-method authorization.</p><ServiceTerms pricing={record.invoice?.pricing} /><div className="flex flex-wrap gap-3"><button disabled={task.busy} className={serviceButton} onClick={() => void action("authorize_paid", { decision: "proceed" })}>Proceed with paid Service</button><button disabled={task.busy} className={serviceButton} onClick={() => void action("authorize_paid", { decision: "cancel" })}>Cancel this request</button></div></section>}
    {billable && <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Payment authorization</h2><ServiceTerms pricing={record.invoice?.pricing} /><label className="flex items-start gap-3"><input type="checkbox" className="mt-1 size-5 shrink-0" checked={accepted} onChange={e => setAccepted(e.target.checked)} />I accept the published Service rates and authorize payment for approved, completed work. Saving a card does not charge an estimate.</label><div className="flex flex-wrap gap-3"><button disabled={task.busy || !accepted} className={serviceButton} onClick={() => void action("authorize_payment", { acceptedTerms: true })}>{record.paymentAuthorized ? "Authorize a different card" : "Authorize payment method"}</button>{record.invoice?.status === "finalized" && record.invoice.payment_status === "payment_due" && <button disabled={task.busy || !accepted} className={serviceButton} onClick={() => void action("pay_invoice", { acceptedTerms: true })}>Pay finalized invoice</button>}</div></section>}
    <section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">Appointments</h2>{record.appointments.length === 0 && <p>No appointment is scheduled.</p>}{record.appointments.map(a => <div key={a.id} className="rounded-xl bg-slate-50 p-4"><p>{displayDate(a.starts_at)} — {displayStatus(a.status)}{a.session_number ? ` · Session ${a.session_number}` : ""}</p>{a.status === "scheduled" && <button disabled={task.busy} className={`${serviceButton} mt-3`} onClick={() => void action("cancel_appointment", { appointmentId: a.id })}>Cancel appointment</button>}</div>)}{record.kind === "included_support" && <p className="text-sm">Cancellation less than 24 hours before the start uses the scheduled session. A no-show also uses the next available session.</p>}</section>{task.status}</div>;
}
type PublicSubscription = { status: string; activationAt: string | null; paidThrough: string | null; failedAt: string | null; cancelAtPeriodEnd: boolean; eligible: boolean; cycles: { id: string; starts_at: string; ends_at: string; remote_support_sessions: { number: number; status: string; reason: string | null }[] }[] };
export function CustomerSubscription({ token }: { token: string }) {
  const [record, setRecord] = useState<PublicSubscription | null>(null); const [loadError, setLoadError] = useState(""); const task = useServiceTask(); const { getKey, clear } = useOperationKey();
  const url = `/api/remote-support/manage/${encodeURIComponent(token)}`;
  const refresh = useCallback(async () => setRecord(await serviceFetch<PublicSubscription>(url)), [url]);
  useEffect(() => { let alive = true; serviceFetch<PublicSubscription>(url).then(value => { if (alive) setRecord(value); }).catch(error => { if (alive) setLoadError(error.message); }); return () => { alive = false; }; }, [url]);
  const action = (name: string) => task.run(async () => { const result = await serviceFetch<{ url?: string }>(url, { action: name, ...(name === "retry_payment" ? { key: getKey(name) } : {}) }); clear(); if (result.url) window.location.assign(result.url); else await refresh(); });
  if (!record) return <p role="status">{loadError || "Loading subscription…"}</p>;
  return <section className="space-y-5 rounded-2xl border bg-white p-5"><p>Keep this private billing link. Do not share it.</p><p>Status: <strong>{displayStatus(record.status)}</strong></p><p>Activation: {displayDate(record.activationAt)}</p><p>Paid through: {displayDate(record.paidThrough)}</p><p>Eligible for support and the Service discount: {record.eligible ? "Yes" : "No"}</p>{record.failedAt && <p className="rounded-xl bg-amber-50 p-4">Payment failed {displayDate(record.failedAt)}. Support, discounts and appointments are paused. Update your payment method and retry within 14 days to restore access.</p>}{record.cancelAtPeriodEnd && <p>Cancellation is scheduled for the end of your paid period. No partial-month refund is issued.</p>}<div className="flex flex-wrap gap-3"><button disabled={task.busy} className={serviceButton} onClick={() => void task.run(refresh, "Status refreshed.")}>Refresh status</button>{record.status !== "pending_payment" && <button disabled={task.busy} className={serviceButton} onClick={() => void action("update_payment")}>Update payment method</button>}{record.status === "suspended" && <button disabled={task.busy} className={serviceButton} onClick={() => void action("retry_payment")}>Retry overdue payment</button>}{!["pending_payment", "cancelled"].includes(record.status) && !record.cancelAtPeriodEnd && <button disabled={task.busy} className={serviceButton} onClick={() => void action("cancel")}>Cancel at paid-period end</button>}</div><Link href="/remote-assistance" className="inline-flex min-h-11 items-center font-bold text-emerald-900 underline">Request Remote Support</Link><LinkSetupSubscription token={token} /><h2 className="text-xl font-bold">Numbered sessions</h2>{record.cycles.map(cycle => <div key={cycle.id} className="rounded-xl bg-slate-50 p-4"><p className="mb-3 font-semibold">{displayDate(cycle.starts_at)} to {displayDate(cycle.ends_at)}</p><ol className="space-y-2">{[...cycle.remote_support_sessions].sort((a, b) => a.number - b.number).map(s => <li key={s.number}>Session {s.number}: {displayStatus(s.status)}{s.reason ? ` (${displayStatus(s.reason)})` : ""}</li>)}</ol></div>)}{task.status}</section>;
}
