import { DEFAULT_SERVICE_PRICING, serviceMoney } from "@/lib/service/policy";
import type { ServicePricing } from "@/lib/service/types";

export function WarrantyVerified() {
  return <p className="rounded-xl border border-emerald-600 bg-emerald-50 p-4 text-lg font-bold text-emerald-950">Warranty verified — Customer due $0.00</p>;
}
export function SupportTerms() {
  return <div className="space-y-3 leading-7"><p><strong>$100/month · Four Remote Support Sessions per billing cycle.</strong> Get help by Phone or Facebook Messenger. One session covers one issue until resolved, including follow-up conversations. There is no 24-hour session limit.</p><p>Unused sessions do not roll over. Cancel anytime; no prorated or partial-month refunds. Active subscribers receive 25% off eligible paid Service labor and travel. Parts, materials and consumables are excluded.</p><p>A standalone subscription activates after successful payment. With a machine, the first $100 is collected at checkout and support activates 10 days after payment confirmation. Monthly renewal follows your first paid support month.</p><p>Cancel an appointment at least 24 hours before it starts to preserve the session; exactly 24 hours qualifies. A later cancellation uses the scheduled session. A no-show uses the scheduled session and the next available session, including Session 1 of the next cycle when necessary.</p><p>A failed monthly payment immediately suspends support and the discount and pauses appointments. Payment recovery within 14 days restores access; otherwise the subscription is cancelled.</p></div>;
}
export function ServiceTerms({ pricing = DEFAULT_SERVICE_PRICING }: { pricing?: ServicePricing }) {
  return <div className="space-y-3 leading-7"><p><strong>Labor: {serviceMoney(pricing.firstHourCents)} for the first started hour, then {serviceMoney(pricing.additionalHalfHourCents)} per started additional 30 minutes.</strong> Diagnosis and actual work are billable even when repair cannot be completed. Repair is not guaranteed.</p><p>Initial on-site travel uses mapped driving time from central Williamsville, Missouri. The first 60 minutes each way are included. Combined excess time costs {serviceMoney(pricing.initialTravelHalfHourCents)} per started 30 minutes. Remote Service has no travel charge.</p><p>For a legitimate return visit, the full round trip costs {serviceMoney(pricing.returnTravelHalfHourCents)} per started 30 minutes. A return caused by a customer-controlled hazard costs {serviceMoney(pricing.hazardTravelHalfHourCents)} per started 30 minutes for the full round trip.</p><p>Waiting for the manufacturer or parts does not accrue labor. Actual work across visits is cumulative; resuming does not restart the first-hour minimum. Staff assess customer-caused delays and stop unsafe work. Additional parts, materials, consumables and authorized expenses are separate.</p><p>Active Remote Support subscribers receive 25% off eligible labor and travel, even after using all four sessions. Supplies are not discounted. Warranty requires IDS verification of both equipment and required service. Physical warranty work defaults to shop drop-off; on-site warranty work requires explicit IDS approval. Covered work has $0 customer due.</p></div>;
}
