"use client";
import { useState } from "react";
import type { ServicePricing, StaffProfile } from "@/lib/service/types";
import { Field, Notes, formValues, serviceButton, serviceFetch, serviceInput, useOperationKey, useServiceTask } from "./ui";

export function StaffManagement({ staff, refresh }: { staff: StaffProfile[]; refresh: () => Promise<void> }) {
  const [editing, setEditing] = useState<StaffProfile | null>(null); const task = useServiceTask(); const { getKey: key } = useOperationKey();
  return <section className="space-y-5 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">Staff accounts</h2><p className="text-sm leading-6">Individual accounts have no fixed count limit. Disable access without deleting attribution. New accounts begin without payment or cash permissions.</p><ul className="space-y-2">{staff.map(person => <li key={person.id} className="flex flex-wrap items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="min-w-0 flex-1 break-words">{person.name} · {person.enabled ? "Enabled" : "Disabled"}</span><button className={serviceButton} onClick={() => setEditing(person)}>Edit {person.name}</button></li>)}</ul><form key={editing?.id ?? "new"} className="grid gap-4 sm:grid-cols-2" onSubmit={event => { const data = formValues(event); void task.run(async () => {
    const input = { id: editing?.id ?? null, name: data.get("name"), email: data.get("email"), phone: data.get("phone"), enabled: data.get("enabled") === "on", canCollectPayments: data.get("collect") === "on", canRecordCash: data.get("cash") === "on", resetPassword: data.get("reset") === "on" };
    await serviceFetch("/api/service/staff/accounts", { ...input, key: key(input) }); await refresh(); setEditing(null);
  }, "Staff settings saved. New accounts and resets queue a private activation email; delivery requires the Service email control."); }}><h3 className="font-bold sm:col-span-2">{editing ? `Edit ${editing.name}` : "Add staff member"}</h3><Field name="name" label="Name" defaultValue={editing?.name} required /><Field name="email" label="Email (account identity)" type="email" defaultValue={editing?.email} readOnly={Boolean(editing)} required /><Field name="phone" label="Phone" type="tel" defaultValue={editing?.phone} required />{editing && <div className="space-y-3 sm:col-span-2">{[["enabled", "Enabled", editing.enabled], ["collect", "May explicitly collect payments", editing.can_collect_payments], ["cash", "May record cash receipts", editing.can_record_cash], ["reset", "Reset password and revoke existing sessions", false]].map(([name, label, checked]) => <label key={String(name)} className="flex min-h-11 items-center gap-3"><input name={String(name)} type="checkbox" defaultChecked={Boolean(checked)} className="size-5" />{label}</label>)}</div>}<div className="flex flex-wrap gap-3 sm:col-span-2"><button className={serviceButton} disabled={task.busy}>{editing ? "Save staff settings" : "Create staff account"}</button>{editing && <button className={serviceButton} type="button" onClick={() => setEditing(null)}>Add another staff member</button>}</div></form>{task.status}</section>;
}
const rateLabels: Record<keyof ServicePricing, string> = { firstHourCents: "First started hour ($)", additionalHalfHourCents: "Additional started 30 minutes ($)", initialTravelHalfHourCents: "Initial excess travel / 30 minutes ($)", returnTravelHalfHourCents: "Legitimate return travel / 30 minutes ($)", hazardTravelHalfHourCents: "Hazard return travel / 30 minutes ($)", warrantyHourlyCents: "Warranty service value / hour ($)" };
export function PricingManagement({ pricing, version, refresh }: { pricing: ServicePricing; version: number; refresh: () => Promise<void> }) {
  const task = useServiceTask(); const { getKey: key } = useOperationKey();
  return <form key={version} className="space-y-5 rounded-2xl border bg-white p-5" onSubmit={event => { const data = formValues(event); void task.run(async () => {
    const input = { version, reason: data.get("reason"), pricing: Object.fromEntries(Object.keys(rateLabels).map(name => [name, Math.round(Number(data.get(name)) * 100)])) };
    await serviceFetch("/api/service/staff/pricing", { ...input, key: key(input) }); await refresh();
  }, "Future-case rates saved. Existing invoice rate snapshots remain unchanged."); }}><h2 className="text-2xl font-black">Service pricing</h2><p>Master authority for future cases. Changes require a reason and preserve existing invoice rates.</p><div className="grid gap-4 sm:grid-cols-2">{Object.entries(rateLabels).map(([name, label]) => <Field key={name} name={name} label={label}><input className={serviceInput} type="number" name={name} defaultValue={pricing[name as keyof ServicePricing] / 100} min="0" step="0.01" required /></Field>)}</div><Notes name="reason" label="Reason for pricing change" required />{task.status}<button className={serviceButton} disabled={task.busy}>Save future-case rates</button></form>;
}
