"use client";
import { useEffect, useState } from "react";
import type { CaseDetail, StaffActor, StaffProfile } from "@/lib/service/types";
import WorkSheetEditor from "./WorkSheetEditor";
import { WarrantyVerified } from "./ServiceTerms";
import { Field, Notes, displayDate, displayStatus, formValues, serviceButton, serviceFetch, serviceInput, useOperationKey, useServiceTask } from "./ui";

export default function StaffCase({ detail, actor, staff, refresh, controls, onDirtyChange }: { detail: CaseDetail; actor: StaffActor; staff: StaffProfile[]; refresh: () => Promise<void>; onDirtyChange: (dirty: boolean) => void; controls: { payments: boolean; cash: boolean; terminal: boolean } }) {
  const [viewedAt] = useState(() => Date.now());
  const job = detail.case; const invoice = detail.invoice; const [sheet, setSheet] = useState(invoice?.sheet ?? null);
  const [paymentUrl, setPaymentUrl] = useState(""); const task = useServiceTask(); const { getKey: key, clear: clearKey } = useOperationKey();
  const endpoint = `/api/service/staff/cases/${job.id}`; const master = actor.role === "master";
  const dirty = Boolean(invoice && sheet && JSON.stringify(invoice.sheet) !== JSON.stringify(sheet));
  useEffect(() => { onDirtyChange(dirty); return () => onDirtyChange(false); }, [dirty, onDirtyChange]);
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const action = (actionName: string, data: Record<string, unknown> = {}) => task.run(async () => {
    const input = { action: actionName, version: job.version, data }; await serviceFetch(endpoint, { ...input, key: key(input) }); await refresh();
  });
  const activeAppointments = detail.appointments.filter(a => ["scheduled", "paused"].includes(a.status));
  return <div className="min-w-0 space-y-5"><section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">{job.case_number} · {job.customer_name}</h2><p>{job.customer_phone}{job.customer_email ? ` · ${job.customer_email}` : ""}</p><p>Technical status: <strong>{displayStatus(job.status)}</strong> · {displayStatus(job.kind)}</p><p>Assignment: {job.assigned_staff_id === actor.id && actor.id ? actor.name : staff.find(s => s.id === job.assigned_staff_id)?.name ?? "Unassigned"}</p><h3 className="font-bold">Issue Notes</h3><p className="whitespace-pre-wrap break-words">{job.issue_notes}</p>{job.resolution_notes && <><h3 className="font-bold">Resolution Notes</h3><p className="whitespace-pre-wrap break-words">{job.resolution_notes}</p></>}<details><summary className="min-h-11 cursor-pointer font-bold">Equipment and address</summary><dl className="space-y-2">{Object.entries(job.equipment).map(([name, value]) => <div key={name}><dt className="font-semibold">{name}</dt><dd className="break-words">{value || "Not supplied"}</dd></div>)}</dl><p className="mt-3 break-words">{job.address}</p></details>{job.kind !== "included_support" && <p>Warranty: {displayStatus(job.warranty_status)} · {displayStatus(job.arrangement)} · Payment method: {job.payment_method_id ? "Authorized" : "Not authorized"}</p>}</section>
    {job.warranty_status === "verified" && <WarrantyVerified />}
    {dirty && <p role="status" className="rounded-xl bg-amber-100 p-4 font-semibold">Unsaved work-sheet changes. Save the draft before another case action.</p>}
    {task.status}<fieldset disabled={task.busy || dirty} className="min-w-0 space-y-5"><legend className="sr-only">Case controls</legend>
      {master && <form className="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-5" onSubmit={e => { const data = formValues(e); void action("assign", { staffId: data.get("staffId") }); }}><Field label="Assign / hand off technician" name="staffId"><select name="staffId" className={serviceInput} required defaultValue={job.assigned_staff_id ?? ""}><option value="" disabled>Choose enabled technician</option>{staff.filter(s => s.enabled).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><button className={serviceButton}>Save assignment</button></form>}
      {job.kind === "included_support" && <section className="space-y-3 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Subscription / sessions</h3><p>Subscription: {displayStatus(detail.subscription?.status ?? "unmatched")}. Paid through {displayDate(detail.subscription?.paid_through ?? null)}.</p><p>One issue remains one session until resolved. Viewing, assigning and adding notes never use a session.</p>{["requested", "active"].includes(job.status) && <button className={serviceButton} onClick={() => void action("start_session")}>{job.started_at ? "Continue same session" : "Start Session"}</button>}<ul className="space-y-2 text-sm">{detail.sessions.map(s => <li key={`${s.cycle_id}:${s.number}`}>Cycle {s.cycle_id.slice(0, 8)} · Session {s.number}: {displayStatus(s.status)}{s.reason ? ` · ${displayStatus(s.reason)}` : ""}</li>)}</ul></section>}
      {master && job.kind === "warranty" && ["warranty_verification", "warranty_not_covered_authorization_required"].includes(job.status) && <form className="space-y-4 rounded-2xl border border-amber-300 bg-white p-5" onSubmit={e => { const data = formValues(e); void action("warranty_review", { equipmentCovered: data.get("equipmentCovered") === "on", serviceCovered: data.get("serviceCovered") === "on", arrangement: data.get("arrangement"), notes: data.get("notes") }); }}><h3 className="text-xl font-black">Warranty verification</h3><p>Verify equipment and required service separately. Unchecked coverage means paid authorization is required from the customer.</p>{[["equipmentCovered", "Equipment coverage verified"], ["serviceCovered", "Required service coverage verified"]].map(([name, label]) => <label className="flex min-h-11 items-center gap-3" key={name}><input type="checkbox" name={name} className="size-5" />{label}</label>)}<Field label="Approved arrangement" name="arrangement"><select name="arrangement" className={serviceInput} defaultValue="shop_dropoff"><option value="shop_dropoff">Shop drop-off (physical warranty default)</option><option value="remote">Remote assistance</option><option value="onsite_ids_approved">On-site — explicitly approved by IDS</option></select></Field><Notes name="notes" label="Coverage evidence and IDS decision" required /><button className={serviceButton}>Record warranty decision</button></form>}
      <section className="space-y-4 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Case history and technical status</h3><form className="space-y-3" onSubmit={e => { const data = formValues(e); void action(String(data.get("action")), { notes: data.get("notes"), ...(data.get("action") === "hold" ? { reason: data.get("reason") } : {}) }); }}><Field name="action" label="Action"><select name="action" className={serviceInput}><option value="note">Add case-history note</option>{job.kind !== "included_support" && ["requested", "scheduled", "active"].includes(job.status) && <option value="begin_service">Begin actual Service work</option>}{job.kind !== "included_support" && job.status === "active" && <option value="hold">Put work on hold</option>}{["waiting_manufacturer_parts", "customer_controlled_hazard"].includes(job.status) && <option value="resume">Resume actual work</option>}{job.kind === "included_support" && job.status === "active" && <option value="resolve">Resolve issue (resolution notes required)</option>}</select></Field><Field name="reason" label="Hold reason (when placing work on hold)"><select name="reason" className={serviceInput}><option value="waiting_manufacturer_parts">Waiting for manufacturer or parts</option><option value="customer_controlled_hazard">Customer-controlled hazard — safety stop</option></select></Field><Notes name="notes" label="Notes / decision" required /><button className={serviceButton}>Record action</button></form>{invoice && job.started_at && !["resolved", "cancelled"].includes(job.status) && <button className={serviceButton} disabled={!invoice.sheet.resolution.trim()} onClick={() => void action("resolve", { notes: invoice.sheet.resolution })}>Resolve using saved work-sheet resolution</button>}</section>
      <section className="space-y-4 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Appointments</h3>{activeAppointments.map(a => <div key={a.id} className="space-y-3 rounded-xl bg-slate-50 p-4"><p>{displayDate(a.starts_at)} to {displayDate(a.ends_at)} · {displayStatus(a.status)}{a.session_number ? ` · Session ${a.session_number}` : ""}</p>{a.status === "scheduled" && <div className="flex flex-wrap gap-3"><button className={serviceButton} onClick={() => void action("cancel_appointment", { appointmentId: a.id, notes: "Staff recorded customer cancellation." })}>Record cancellation</button><button className={serviceButton} disabled={Date.parse(a.starts_at) > viewedAt} onClick={() => void action("no_show", { appointmentId: a.id, notes: "Staff verified customer no-show." })}>Record no-show</button></div>}</div>)}{master && <form className="space-y-3" onSubmit={e => { const data = formValues(e); void action("schedule", { startsAt: new Date(String(data.get("starts"))).toISOString(), endsAt: new Date(String(data.get("ends"))).toISOString() }); }}><p className="text-sm">Times use this device’s local time zone. Assignment and paid authorization / warranty verification are required where applicable.</p><div className="grid gap-3 sm:grid-cols-2"><Field name="starts" label="Appointment start" type="datetime-local" required /><Field name="ends" label="Appointment end" type="datetime-local" required /></div><button className={serviceButton}>Schedule appointment</button></form>}</section>
      <section className="space-y-3 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Staff-added images ({detail.attachments.length}/3)</h3><p className="text-sm">Three images per case, up to 15 MB each. JPEG, PNG, WebP or HEIC; private access.</p><div className="flex flex-wrap gap-3">{detail.attachments.filter(a => a.status === "ready").map(a => <a key={a.id} href={`${endpoint}/attachments/${a.id}`} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center break-all font-bold text-emerald-900 underline">{a.name}</a>)}</div><form className="space-y-3" onSubmit={event => { const data = formValues(event); void task.run(async () => { const file = data.get("image"); if (!(file instanceof File) || !file.size) throw new Error("Choose an image."); if (file.size > 15 * 1024 * 1024) throw new Error("Each image must be 15 MB or smaller."); const input = { name: file.name, type: file.type, size: file.size }; const upload = await serviceFetch<{ id: string; uploadUrl: string }>(`${endpoint}/attachments`, { ...input, id: key(input) }); const result = await fetch(upload.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!result.ok && result.status !== 409) throw new Error("Image upload failed. Retry the same file."); await serviceFetch(`${endpoint}/attachments/${upload.id}`, {}); await refresh(); }, "Private image saved."); }}><Field name="image" label="Add case image"><input className={serviceInput} type="file" name="image" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required disabled={detail.attachments.length >= 3} /></Field><button className={serviceButton} disabled={detail.attachments.length >= 3}>Upload image</button></form></section>
    </fieldset>
    {invoice && sheet && <WorkSheetEditor job={job} invoice={invoice} actor={actor} sheet={sheet} setSheet={setSheet} busy={task.busy} save={name => void action(name, { sheet })} />}
    <fieldset disabled={task.busy || dirty} className="min-w-0 space-y-5"><legend className="sr-only">Invoice review and collection</legend>{invoice?.status === "finalized" && (actor.canCollectPayments || actor.canRecordCash) && <section className="space-y-3 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Payment reconciliation</h3><p>Before switching payment methods, close any unpaid attempt. A processing payment remains blocked until Stripe confirms its outcome.</p><button className={serviceButton} onClick={() => void task.run(async () => { await serviceFetch(`${endpoint}/reconcile-payments`, { closeOpen: true }); clearKey(); await refresh(); }, "Payment state reconciled. Unpaid open attempts were closed where Stripe permits.")}>Reconcile / close unpaid attempts</button></section>}{master && invoice?.status === "submitted_for_master_review" && <section className="space-y-4 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Master invoice review</h3><p>Finalization locks the invoice and calculates payment due. It does not charge the customer.</p><button className={serviceButton} onClick={() => void action("finalize_invoice")}>Finalize invoice — no charge</button><form className="space-y-3" onSubmit={e => { const data = formValues(e); void action("return_invoice", { notes: data.get("notes") }); }}><Notes name="notes" label="Required corrections" required /><button className={serviceButton}>Return to technician</button></form></section>}
      {invoice?.status === "finalized" && invoice.payment_status === "payment_due" && (actor.canCollectPayments || actor.canRecordCash) && <section className="space-y-4 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Explicit payment collection</h3><p>Confirm customer authorization before collecting. A decline leaves Payment Due; technical resolution remains separate.</p><form className="space-y-3" onSubmit={e => { const data = formValues(e); void task.run(async () => { const input = { method: data.get("method"), receipt: data.get("receipt"), notes: data.get("notes") }; const result = await serviceFetch<{ url?: string; status: string }>(`${endpoint}/payments`, { ...input, key: key(input) }); if (result.url) setPaymentUrl(result.url); else { clearKey(); await refresh(); } }, "Payment action recorded. Review the confirmed payment status."); }}><Field label="Collection method" name="method"><select name="method" className={serviceInput}>{controls.payments && actor.canCollectPayments && <><option value="link">Create pay-now link / different card</option>{job.payment_method_id && <option value="card">Charge authorized card on file</option>}{controls.terminal && <option value="terminal">Collect using configured Stripe Terminal reader</option>}</>}{controls.cash && actor.canRecordCash && <option value="cash">Record cash received</option>}</select></Field><Field name="receipt" label="Cash receipt/reference (required for cash)" /><Notes name="notes" label="Authorization / cash-receipt notes" required /><label className="flex items-start gap-3"><input type="checkbox" required className="mt-1 size-5 shrink-0" />I confirm the customer authorized this collection, or the stated cash was received.</label><button className={serviceButton} disabled={!controls.payments && !(controls.cash && actor.canRecordCash)}>Perform selected payment action</button></form>{paymentUrl && <p className="break-all"><a className="font-bold text-emerald-900 underline" href={paymentUrl} target="_blank" rel="noreferrer">Open the customer pay-now link</a></p>}</section>}
      {invoice?.status === "finalized" && job.status === "resolved" && job.warranty_status === "verified" && <section className="space-y-3 rounded-2xl border bg-white p-5"><h3 className="text-xl font-bold">Final warranty report · Customer due $0.00</h3><p>The final report is queued automatically for Service.IDS@proton.me. Use the PDF viewer to print.</p><div className="flex flex-wrap gap-3"><a className={serviceButton} href={`${endpoint}/report`} target="_blank" rel="noreferrer">View / print report</a><a className={serviceButton} href={`${endpoint}/report?download`}>Download PDF</a></div></section>}
    </fieldset>
    <section className="rounded-2xl border bg-white p-5"><h3 className="mb-4 text-xl font-bold">Historical attribution</h3><ol className="space-y-4">{detail.events.map(event => <li key={event.id} className="border-l-2 border-emerald-700 pl-4"><p className="font-semibold">{displayStatus(event.action)} · {event.actor_name}</p><p className="text-sm text-slate-600">{displayDate(event.created_at)}</p>{typeof event.details.notes === "string" && <p className="mt-1 whitespace-pre-wrap break-words">{event.details.notes}</p>}</li>)}</ol></section>
  </div>;
}
