"use client";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import type { CaseDetail, ServiceCase, ServicePricing, StaffActor, StaffProfile, Subscription } from "@/lib/service/types";
import StaffCase from "./StaffCase";
import { StaffManagement, PricingManagement } from "./StaffManagement";
import AvailabilityManagement from "./AvailabilityManagement";
import { displayDate, displayStatus, serviceButton, serviceFetch, serviceInput, useServiceTask } from "./ui";

type Overview = { cases: (ServiceCase & { invoice_status: string | null; payment_status: string | null })[]; staff: StaffProfile[]; subscriptions: (Subscription & { customer_name?: string })[]; pricing: ServicePricing; pricingVersion: number; financialReview: { stripe_object_id: string; reason: string; details: Record<string, unknown> }[]; outbox: { id: string; kind: string; status: string; attempts: number; last_error: string | null }[] };
export default function StaffPortal({ actor, controls }: { actor: StaffActor; controls: { payments: boolean; cash: boolean; terminal: boolean } }) {
  const router = useRouter(); const [dirty, setDirty] = useState(false);
  const [overview, setOverview] = useState<Overview | null>(null); const [detail, setDetail] = useState<CaseDetail | null>(null); const [selected, setSelected] = useState<string | null>(null); const [filter, setFilter] = useState(""); const [loadError, setLoadError] = useState(""); const task = useServiceTask();
  const refresh = useCallback(async () => { const [list, record] = await Promise.all([serviceFetch<Overview>("/api/service/staff/cases"), selected ? serviceFetch<CaseDetail>(`/api/service/staff/cases/${selected}`) : Promise.resolve(null)]); setOverview(list); setDetail(record); }, [selected]);
  useEffect(() => { let alive = true; Promise.all([serviceFetch<Overview>("/api/service/staff/cases"), selected ? serviceFetch<CaseDetail>(`/api/service/staff/cases/${selected}`) : Promise.resolve(null)]).then(([list, record]) => { if (alive) { setOverview(list); setDetail(record); setLoadError(""); } }).catch(error => { if (alive) { setLoadError(error.message); setDetail(null); } }); return () => { alive = false; }; }, [selected]);
  if (!overview) return <p role="status">{loadError || "Loading staff workspace…"}</p>;
  const cases = overview.cases.filter(c => `${c.case_number} ${c.customer_name} ${c.status} ${c.kind}`.toLowerCase().includes(filter.toLowerCase()));
  return <div className="space-y-6"><div className="flex flex-wrap items-center gap-3"><p className="mr-auto font-bold">{actor.name} · {actor.role === "master" ? "Master Admin" : "Technician"}</p><button className={serviceButton} disabled={task.busy || dirty} onClick={() => void task.run(refresh, "Records refreshed.")}>Refresh</button>{actor.role !== "master" && <button className={serviceButton} disabled={task.busy || dirty} onClick={() => void task.run(async () => { await serviceFetch("/api/service/staff/session", undefined, "DELETE"); router.push("/staff/service/login"); }, "")}>Sign out</button>}</div>{task.status}{loadError && <p role="alert">{loadError}</p>}
    <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">{actor.role === "master" ? "All Service and Remote Support cases" : "My Assigned Cases"}</h2><label className="block font-semibold">Search cases<input className={serviceInput} value={filter} onChange={e => setFilter(e.target.value)} placeholder="Case, customer, type or status" /></label>{cases.length === 0 && <p>No matching cases.</p>}<ul className="space-y-3">{cases.map(c => <li key={c.id}><button className={`w-full rounded-xl border p-4 text-left hover:border-emerald-700 ${selected === c.id ? "border-emerald-700 bg-emerald-50" : "border-slate-200"}`} disabled={dirty} onClick={() => { setSelected(c.id); setDetail(null); }}><strong className="block break-words">{c.case_number} · {c.customer_name}</strong><span className="mt-1 block text-sm">{displayStatus(c.kind)} · Technical: {displayStatus(c.status)}{c.invoice_status ? ` · Invoice: ${displayStatus(c.invoice_status)} · Payment: ${displayStatus(c.payment_status ?? "not_due")}` : ""}</span></button></li>)}</ul></section>
    {selected && !detail && !loadError && <p role="status">Loading selected case…</p>}{detail && <StaffCase key={`${detail.case.id}:${detail.case.version}:${detail.invoice?.version ?? 0}`} actor={actor} staff={overview.staff} detail={detail} refresh={refresh} controls={controls} onDirtyChange={setDirty} />}
    {actor.role === "master" && <fieldset disabled={dirty} className="min-w-0 space-y-6"><legend className="sr-only">Master administration</legend><AvailabilityManagement /><section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">Remote Support subscriptions</h2>{overview.subscriptions.length === 0 && <p>No subscriptions yet.</p>}{overview.subscriptions.map(s => <div key={s.id} className="space-y-2 rounded-xl bg-slate-50 p-4"><h3 className="break-words font-bold">{s.customer_name ?? s.id}</h3><p>{displayStatus(s.status)} · {s.source} · {s.livemode ? "Live record" : "Test record"}</p><p>Activation {displayDate(s.activation_at)} · Paid through {displayDate(s.paid_through)}</p>{s.failed_at && <p>Failed payment: {displayDate(s.failed_at)}</p>}{s.cancel_at_period_end && <p>Cancel at paid-period end</p>}<button className={serviceButton} disabled={task.busy} onClick={() => void task.run(async () => { await serviceFetch("/api/service/staff/subscriptions/reconcile", { id: s.id }); await refresh(); }, "Stripe state reconciled.")}>Reconcile Stripe status</button></div>)}</section><section className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">Financial adjustments and review</h2><p>Provider-confirmed refunds, disputes and late subscription payments are retained here. These records do not collect another payment or automatically refund the customer.</p>{overview.financialReview?.map(record => <details key={record.stripe_object_id} className="rounded-xl bg-slate-50 p-3"><summary className="cursor-pointer break-words font-bold">{displayStatus(record.reason)} ? {record.stripe_object_id}</summary><pre className="mt-3 whitespace-pre-wrap break-all text-sm">{JSON.stringify(record.details, null, 2)}</pre></details>)}</section><StaffManagement staff={overview.staff} refresh={refresh} /><PricingManagement pricing={overview.pricing} version={overview.pricingVersion} refresh={refresh} /><section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-2xl font-black">Delivery and reconciliation queue</h2><p className="text-sm">Final warranty reports and private links use the Service email control. Payment reconciliation uses verified Stripe state.</p><button className={serviceButton} disabled={task.busy} onClick={() => void task.run(async () => { const result = await serviceFetch<{ delivered: number; failures: number }>("/api/service/staff/maintenance", {}); await refresh(); if (result.failures) throw new Error(`${result.delivered} delivered; ${result.failures} require retry or review.`); }, "Maintenance completed.")}>Run due maintenance</button><ul className="space-y-2">{overview.outbox?.map(job => <li key={job.id} className="rounded-xl bg-slate-50 p-3">{displayStatus(job.kind)} · {displayStatus(job.status)} · Attempts: {job.attempts}{job.last_error ? ` · ${job.last_error}` : ""}</li>)}</ul></section></fieldset>}
  </div>;
}
