"use client";
import { calculateInvoice, serviceMoney } from "@/lib/service/policy";
import type { ServiceCase, ServiceInvoice, StaffActor, WorkSheet } from "@/lib/service/types";
import { serviceButton, serviceInput, Field, displayStatus } from "./ui";

export default function WorkSheetEditor({ job, invoice, actor, sheet, setSheet, busy, save }: { job: ServiceCase; invoice: ServiceInvoice; actor: StaffActor; sheet: WorkSheet; setSheet: (sheet: WorkSheet) => void; busy: boolean; save: (action: string) => void }) {
  const locked = invoice.status !== "draft" || busy;
  const today = () => new Date().toLocaleDateString("en-CA");
  const update = <K extends keyof WorkSheet>(key: K, value: WorkSheet[K]) => setSheet({ ...sheet, [key]: value });
  const changeLine = (group: "labor" | "travel" | "supplies", id: string, field: string, value: string | number) => setSheet({ ...sheet, [group]: sheet[group].map(line => line.id === id ? { ...line, [field]: value } : line) });
  const remove = (group: "labor" | "travel" | "supplies", id: string) => setSheet({ ...sheet, [group]: sheet[group].filter(line => line.id !== id) });
  let preview = invoice.totals; let previewError = "";
  try { preview = calculateInvoice(sheet, { remote: job.kind === "remote_service" || job.arrangement === "remote", warranty: job.warranty_status === "verified", subscriberEligible: invoice.subscriber_eligible, shopDropoff: job.arrangement === "shop_dropoff", pricing: invoice.pricing }); }
  catch { previewError = "Complete valid quantities to calculate the preview."; }
  return <section className="space-y-5 rounded-2xl border border-slate-200 bg-white p-4 sm:p-6"><h2 className="text-2xl font-black">Invoice / Work Sheet</h2><p className="break-words text-sm">{job.case_number} · {job.customer_name} · {displayStatus(job.kind)}<br />Invoice reference: {invoice.id}</p><p>Invoice: <strong>{displayStatus(invoice.status)}</strong> · Payment: <strong>{displayStatus(invoice.payment_status)}</strong></p>{invoice.review_notes && <p className="rounded-xl bg-amber-50 p-4">Master review: {invoice.review_notes}</p>}<p className="text-sm leading-6">Enter work once here. Active minutes are entered work quantities, not elapsed clock time. Holds and manufacturer/parts waiting do not accrue labor. This same invoice continues across visits and technician handoffs.</p>
    <fieldset disabled={locked} className="min-w-0 space-y-5"><legend className="sr-only">Work performed and charges</legend>
      <div className="grid gap-4 md:grid-cols-2">{(["diagnosis", "workPerformed", "testing", "resolution", "holdNotes", "authorizationNotes"] as const).map(name => <Field key={name} name={name} label={{ diagnosis: "Diagnosis", workPerformed: "Work performed", testing: "Testing", resolution: "Resolution", holdNotes: "Holds / return visits / customer delay decisions", authorizationNotes: "Authorizations" }[name]}><textarea className={serviceInput} rows={3} maxLength={8000} value={sheet[name]} onChange={e => update(name, e.target.value)} /></Field>)}</div>
      <section className="space-y-3"><h3 className="text-xl font-bold">Active labor</h3>{sheet.labor.map((line, index) => <fieldset key={line.id} className="min-w-0 rounded-xl border p-4"><legend className="px-2 font-semibold">Work entry {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><Field name={`labor-date-${line.id}`} label="Service date"><input type="date" className={serviceInput} value={line.date} onChange={e => changeLine("labor", line.id, "date", e.target.value)} /></Field><Field name={`minutes-${line.id}`} label="Actual active minutes"><input type="number" min="1" step="1" className={serviceInput} value={line.minutes || ""} onChange={e => changeLine("labor", line.id, "minutes", Number(e.target.value))} /></Field><Field name={`work-${line.id}`} label="Active work description"><textarea className={serviceInput} value={line.description} maxLength={2000} onChange={e => changeLine("labor", line.id, "description", e.target.value)} /></Field></div><button type="button" className="mt-3 min-h-11 font-bold text-red-800 underline" onClick={() => remove("labor", line.id)}>Remove work entry {index + 1}</button></fieldset>)}<button type="button" className={serviceButton} onClick={() => update("labor", [...sheet.labor, { id: crypto.randomUUID(), date: today(), minutes: 0, description: "", technicianId: actor.id }])}>Add active work</button></section>
      {["onsite", "onsite_ids_approved"].includes(job.arrangement) && <section className="space-y-3"><h3 className="text-xl font-bold">Mapped travel / return visits</h3>{sheet.travel.map((line, index) => <fieldset key={line.id} className="min-w-0 rounded-xl border p-4"><legend className="px-2 font-semibold">Trip {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><Field name={`trip-date-${line.id}`} label="Trip date"><input type="date" className={serviceInput} value={line.date} onChange={e => changeLine("travel", line.id, "date", e.target.value)} /></Field><Field name={`category-${line.id}`} label="Trip category"><select className={serviceInput} value={line.category} onChange={e => changeLine("travel", line.id, "category", e.target.value)}><option value="initial">Initial — 60 minutes each way included</option><option value="legitimate_return">Legitimate return — full trip at {serviceMoney(invoice.pricing.returnTravelHalfHourCents)} / 30 min</option><option value="hazard_return">Customer hazard return — full trip at {serviceMoney(invoice.pricing.hazardTravelHalfHourCents)} / 30 min</option></select></Field>{(["outboundMinutes", "returnMinutes"] as const).map(name => <Field key={name} name={`${name}-${line.id}`} label={name === "outboundMinutes" ? "Mapped outbound minutes" : "Mapped return minutes"}><input className={serviceInput} type="number" min="0" step="1" value={line[name]} onChange={e => changeLine("travel", line.id, name, Number(e.target.value))} /></Field>)}<Field name={`route-${line.id}`} label="Mapped route from central Williamsville, MO"><input className={serviceInput} value={line.mappedRoute} maxLength={1000} onChange={e => changeLine("travel", line.id, "mappedRoute", e.target.value)} /></Field><Field name={`reason-${line.id}`} label="Reason / return-visit details"><textarea className={serviceInput} value={line.reason} maxLength={2000} onChange={e => changeLine("travel", line.id, "reason", e.target.value)} /></Field></div><button type="button" className="mt-3 min-h-11 font-bold text-red-800 underline" onClick={() => remove("travel", line.id)}>Remove trip {index + 1}</button></fieldset>)}<button type="button" className={serviceButton} onClick={() => update("travel", [...sheet.travel, { id: crypto.randomUUID(), date: today(), category: sheet.travel.length ? "legitimate_return" : "initial", outboundMinutes: 0, returnMinutes: 0, mappedRoute: "", reason: "" }])}>Add mapped trip</button></section>}
      <section className="space-y-3"><h3 className="text-xl font-bold">Parts, materials and consumables</h3><p className="text-sm">Separate authorized costs. No subscriber discount applies.</p>{sheet.supplies.map((line, index) => <fieldset key={line.id} className="min-w-0 rounded-xl border p-4"><legend className="px-2 font-semibold">Supply {index + 1}</legend><div className="grid gap-3 sm:grid-cols-2"><Field name={`supply-kind-${line.id}`} label="Category"><select className={serviceInput} value={line.kind} onChange={e => changeLine("supplies", line.id, "kind", e.target.value)}><option value="part">Part</option><option value="material">Material</option><option value="consumable">Consumable</option></select></Field>{(["description", "partNumber", "authorization"] as const).map(name => <Field key={name} name={`${name}-${line.id}`} label={{ description: "Description", partNumber: "Part number (if applicable)", authorization: "Expense authorization / approval" }[name]}><input className={serviceInput} value={line[name]} onChange={e => changeLine("supplies", line.id, name, e.target.value)} /></Field>)}<Field name={`quantity-${line.id}`} label="Quantity"><input className={serviceInput} type="number" min="0.001" step="0.001" value={line.quantity} onChange={e => changeLine("supplies", line.id, "quantity", Number(e.target.value))} /></Field><Field name={`price-${line.id}`} label="Unit price ($)"><input className={serviceInput} type="number" min="0" step="0.01" value={line.unitCents / 100} onChange={e => changeLine("supplies", line.id, "unitCents", Math.round(Number(e.target.value) * 100))} /></Field></div><button type="button" className="mt-3 min-h-11 font-bold text-red-800 underline" onClick={() => remove("supplies", line.id)}>Remove supply {index + 1}</button></fieldset>)}<button type="button" className={serviceButton} onClick={() => update("supplies", [...sheet.supplies, { id: crypto.randomUUID(), kind: "part", description: "", partNumber: "", quantity: 1, unitCents: 0, authorization: "" }])}>Add supply</button></section>
      {job.warranty_status === "verified" && <Field label="Manufacturer reimbursement recorded separately ($)" name="reimbursement"><input className={serviceInput} type="number" min="0" step="0.01" value={sheet.manufacturerReimbursementCents / 100} onChange={e => update("manufacturerReimbursementCents", Math.round(Number(e.target.value) * 100))} /></Field>}
    </fieldset>
    {previewError && <p role="status">{previewError}</p>}
    {preview && <section aria-label="Charge breakdown" className="space-y-3 rounded-xl border p-4 text-sm">
      <h3 className="font-bold">Charge breakdown</h3>
      <p>{job.warranty_status === "verified" ? <>{preview.activeMinutes} active minutes at {serviceMoney(invoice.pricing.warrantyHourlyCents)}/hour warranty value</> : <>{preview.activeMinutes} cumulative active minutes: {preview.activeMinutes ? 1 : 0} first-hour block at {serviceMoney(invoice.pricing.firstHourCents)} + {preview.additionalLaborBlocks} additional begun 30-minute blocks at {serviceMoney(invoice.pricing.additionalHalfHourCents)}</>} = <strong>{serviceMoney(preview.laborCents)}</strong></p>
      {preview.travelLines.map((line, index) => <p key={line.id}>Trip {index + 1}: {line.billableMinutes} billable minutes · {line.blocks} begun 30-minute blocks × {serviceMoney(line.rateCents)} = <strong>{serviceMoney(line.amountCents)}</strong></p>)}
      {sheet.supplies.map((line, index) => <p key={line.id}>Supply {index + 1} ({line.description || displayStatus(line.kind)}): {line.quantity} × {serviceMoney(line.unitCents)} = <strong>{serviceMoney(Math.round(line.quantity * line.unitCents))}</strong></p>)}
      <p>Eligible labor/travel subtotal: <strong>{serviceMoney(preview.eligibleSubtotalCents)}</strong></p>
    </section>}{preview && <dl className="grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-4 text-sm"><dt>Labor ({preview.activeMinutes} active minutes)</dt><dd className="text-right">{serviceMoney(preview.laborCents)}</dd><dt>Travel</dt><dd className="text-right">{serviceMoney(preview.travelCents)}</dd><dt>25% eligible labor/travel discount</dt><dd className="text-right">−{serviceMoney(preview.discountCents)}</dd><dt>Parts / materials / consumables</dt><dd className="text-right">{serviceMoney(preview.partsCents + preview.materialsCents + preview.consumablesCents)}</dd><dt>Full service value</dt><dd className="text-right">{serviceMoney(preview.serviceValueCents)}</dd><dt className="font-bold">{["paid", "paid_cash", "refunded", "partially_refunded", "payment_review"].includes(invoice.payment_status) ? "Final invoice amount" : "Customer due"}</dt><dd className="text-right font-bold">{serviceMoney(preview.customerDueCents)}</dd></dl>}
    {invoice.status === "draft" && <><p className="text-sm">Preview only. Server pricing and current authoritative subscription eligibility are applied on save and finalization.</p><div className="flex flex-wrap gap-3"><button disabled={busy} className={serviceButton} onClick={() => save("save_invoice")}>Save draft</button><button disabled={busy} className={serviceButton} onClick={() => save("submit_invoice")}>Submit for Master review</button></div></>}
  </section>;
}
