"use client";
import { FormEvent, useState } from "react";
import { REVIEW_PRODUCTS, US_STATES } from "@/lib/reviews/types";
import { Stars } from "./Stars";
type Ratings = { easeRating: number|null; speedRating: number|null; priceRating: number|null; supportRating: number|null };
const Privacy = ({ children }: { children: React.ReactNode }) => <p className="mt-1 text-xs leading-5 text-slate-500">{children}</p>;
const RatingField = ({ label, explanation, value, optional, onChange, guidance }: { name?: string; label: string; explanation: string; value: number|null; optional?: boolean; onChange: (n:number)=>void; guidance?: React.ReactNode }) => <div className="rounded-2xl border border-slate-200 p-5"><h3 className="font-black text-slate-950">{label}{!optional && <span aria-hidden="true"> *</span>}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{explanation}</p><div className="mt-3"><Stars interactive value={value} label={label} onChange={onChange}/></div>{guidance}</div>;
export default function ReviewForm({ onSuccess }: { onSuccess?: () => void }) {
  const [product, setProduct] = useState(""); const [written, setWritten] = useState(""); const [ratings, setRatings] = useState<Ratings>({ easeRating:null,speedRating:null,priceRating:null,supportRating:null }); const [errors,setErrors]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); setErrors({}); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); Object.assign(body, ratings, { publishingConsent: form.get("publishingConsent") === "on", contactConsent: form.get("contactConsent") === "on" }); const response = await fetch("/api/reviews", { method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body) }); const result=await response.json(); setBusy(false); if(!response.ok){setErrors(result.errors??{form:result.error});return;} setDone(true); onSuccess?.(); }
  if(done) return <div className="rounded-[2rem] border border-emerald-200 bg-emerald-50 p-8 text-center"><h2 className="text-2xl font-black text-slate-950">Thank You for Your Review</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-slate-700">Your review has been submitted successfully. It will appear on the website after it has been reviewed and approved by Integrity Distribution Systems.</p></div>;
  const inputClass="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-slate-950 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-200";
  return <form onSubmit={submit} className="space-y-6" noValidate><div><h2 className="text-3xl font-black text-slate-950">Leave a Review</h2><p className="mt-3 leading-7 text-slate-600">We appreciate your honest feedback. Your review helps us improve and gives future customers a better understanding of what they can expect from Integrity Distribution Systems.</p></div>{errors.form&&<p role="alert" className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{errors.form}</p>}
  <div className="grid gap-5 sm:grid-cols-2"><label className="font-bold">First Name *<input name="firstName" required maxLength={80} className={inputClass}/><Privacy>Your first name will be shown publicly.</Privacy>{errors.firstName&&<span className="text-sm text-red-700">{errors.firstName}</span>}</label><label className="font-bold">Last Name *<input name="lastName" required maxLength={100} className={inputClass}/><Privacy>Only your last initial will be visible publicly.</Privacy>{errors.lastName&&<span className="text-sm text-red-700">{errors.lastName}</span>}</label><label className="font-bold">State *<select name="state" required defaultValue="" className={inputClass}><option value="" disabled>Select a state</option>{US_STATES.map(s=><option key={s}>{s}</option>)}</select><Privacy>Your state will be shown publicly. Your city and street address are not requested.</Privacy>{errors.state&&<span className="text-sm text-red-700">{errors.state}</span>}</label><label className="font-bold">Email Address *<input name="email" type="email" required maxLength={254} className={inputClass}/><Privacy>This information will never be shown publicly.</Privacy>{errors.email&&<span className="text-sm text-red-700">{errors.email}</span>}</label></div>
  <label className="block font-bold">Product or Service Reviewed *<select name="product" required value={product} onChange={e=>setProduct(e.target.value)} className={inputClass}><option value="" disabled>Select a product or service</option>{REVIEW_PRODUCTS.map(p=><option key={p}>{p}</option>)}</select><Privacy>Your selection will be shown publicly with your review.</Privacy>{errors.product&&<span className="text-sm text-red-700">{errors.product}</span>}</label>{product==="Other"&&<label className="block font-bold">Product or service name *<input name="otherDescription" required maxLength={120} className={inputClass}/><Privacy>This description will be shown publicly.</Privacy>{errors.otherDescription&&<span className="text-sm text-red-700">{errors.otherDescription}</span>}</label>}
  <div className="grid gap-4 md:grid-cols-2"><RatingField name="easeRating" label="Ease of Purchase" explanation="How simple and straightforward was the buying process with IDS?" value={ratings.easeRating} onChange={n=>setRatings({...ratings,easeRating:n})}/><RatingField name="speedRating" label="Speed of Service" explanation="How quickly did IDS respond, answer questions, and handle your purchase or service needs?" value={ratings.speedRating} onChange={n=>setRatings({...ratings,speedRating:n})}/><RatingField name="priceRating" label="Price Compared to Other Retailers" explanation="How competitive was IDS pricing compared with other dealers or manufacturer offers you considered?" value={ratings.priceRating} onChange={n=>setRatings({...ratings,priceRating:n})} guidance={<p className="mt-3 text-xs leading-5 text-slate-500">1 — Much higher than competitors · 2 — Somewhat higher · 3 — About the same · 4 — Better than most · 5 — Best price or value found</p>}/><RatingField name="supportRating" optional label="Support Before & After the Sale" explanation="How satisfied were you with the guidance and support you received both before and after your purchase? Leave this section blank if no assistance was required." value={ratings.supportRating} onChange={n=>setRatings({...ratings,supportRating:n})}/></div>
  {(["easeRating","speedRating","priceRating","supportRating"] as const).map(key=>errors[key]&&<p key={key} className="text-sm text-red-700">{errors[key]}</p>)}
  <label className="block font-bold">Written Review *<span className="mt-1 block text-sm font-normal leading-6 text-slate-600">Share your honest feelings about your interaction with Integrity Distribution Systems.</span><textarea name="writtenReview" required maxLength={1000} rows={7} value={written} onChange={e=>setWritten(e.target.value)} placeholder="Tell us what stood out, what went well, and anything you believe future customers should know." className={inputClass}/><span className="mt-1 flex justify-between text-sm"><span className="text-red-700">{errors.writtenReview}</span><span aria-live="polite">{written.length} / 1,000</span></span></label>
  <div className="sr-only" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="flex gap-3 font-semibold"><input name="publishingConsent" type="checkbox" required className="mt-1 h-5 w-5 accent-emerald-600"/><span>I confirm that this review reflects my honest experience with Integrity Distribution Systems and authorize IDS to publish it on its website. *</span></label>{errors.publishingConsent&&<p className="text-sm text-red-700">{errors.publishingConsent}</p>}<label className="flex gap-3"><input name="contactConsent" type="checkbox" className="mt-1 h-5 w-5 accent-emerald-600"/><span>IDS may contact me privately if clarification or follow-up is needed.</span></label><button disabled={busy} className="w-full rounded-2xl bg-emerald-600 px-7 py-4 text-lg font-black text-white transition hover:bg-emerald-700 disabled:opacity-60">{busy?"Submitting…":"Submit Review"}</button></form>;
}
