import type { DemoRequest } from "./types";

const escape=(value:string)=>value.replace(/\\/g,"\\\\").replace(/\r\n|\r|\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");
const parameter=(value:string)=>`"${value.replace(/[\r\n]/g," ").replace(/\\/g,"\\\\").replace(/"/g,"\\\"")}"`;
const email=(value:string)=>{const clean=value.trim();if(!/^[^\s@<>:,;]+@[^\s@<>:,;]+\.[^\s@<>:,;]+$/.test(clean))throw new Error("A valid calendar email is required.");return clean;};
const utc=(value:string)=>new Date(value).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");
const fold=(line:string)=>{const chunks=[];let rest=line;while(Buffer.byteLength(rest,"utf8")>75){let cut=Math.min(73,rest.length);while(Buffer.byteLength(rest.slice(0,cut),"utf8")>73)cut--;chunks.push(rest.slice(0,cut));rest=" "+rest.slice(cut);}chunks.push(rest);return chunks.join("\r\n");};

export function createDemoIcs(request:DemoRequest,{organizerEmail,attendeeEmail,attendeeName}:{organizerEmail:string;attendeeEmail:string;attendeeName:string}){const description=[`Customer: ${request.customerName}`,`Email: ${request.customerEmail}`,`Phone: ${request.customerPhone}`,`Property Address: ${request.propertyAddress}`,`Equipment Interest: ${request.equipmentInterest??"Not specified"}`,`Request ID: ${request.id}`].join("\n");const organizer=email(organizerEmail),attendee=email(attendeeEmail);const lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Integrity Distribution Systems//Demo Scheduling//EN","CALSCALE:GREGORIAN","METHOD:REQUEST","BEGIN:VEVENT",`UID:demo-${request.id}@integrityautomowers.com`,`DTSTAMP:${utc(new Date().toISOString())}`,`DTSTART:${utc(request.requestedStartAt)}`,`DTEND:${utc(request.requestedEndAt)}`,`SUMMARY:${escape(`IDS Demo — ${request.customerName}`)}`,`DESCRIPTION:${escape(description)}`,`LOCATION:${escape(request.propertyAddress)}`,"STATUS:CONFIRMED",`ORGANIZER;CN=${parameter("Integrity Distribution Systems")}:mailto:${organizer}`,`ATTENDEE;CN=${parameter(attendeeName)};RSVP=FALSE:mailto:${attendee}`,"END:VEVENT","END:VCALENDAR"];return lines.map(fold).join("\r\n")+"\r\n";}
