import "server-only";
import { sendIdsNotification, sendServerEmail } from "@/lib/email";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { SITE_CONTACT } from "@/lib/site-contact";
import { createDemoIcs } from "./ics";
import { humanDemoTime } from "./time";
import type { DemoRequest } from "./types";

type EventType="ids_new_request"|"customer_approved"|"ids_calendar_invite"|"customer_denied";
async function deliver(request:DemoRequest,type:EventType,send:()=>Promise<unknown>){const c=getSupabaseServiceClient();const{data,error}=await c.rpc("demo_claim_notification",{p_request_id:request.id,p_event_type:type});if(error||!data)throw new Error("Notification claim failed.");const claim=data as{claimed:boolean;eventId:string;claimedAt:string};if(!claim.claimed)return"skipped" as const;try{await send();await c.rpc("demo_finish_notification",{p_event_id:claim.eventId,p_claimed_at:claim.claimedAt,p_status:"sent",p_error:null});return"sent" as const;}catch(error){await c.rpc("demo_finish_notification",{p_event_id:claim.eventId,p_claimed_at:claim.claimedAt,p_status:"failed",p_error:error instanceof Error?error.message.slice(0,100):"SEND_FAILED"});throw error;}}
const details=(r:DemoRequest)=>[`Customer: ${r.customerName}`,`Email: ${r.customerEmail}`,`Phone: ${r.customerPhone}`,`Property: ${r.propertyAddress}`,`Requested time: ${humanDemoTime(r.requestedStartAt,r.requestedEndAt)}`,`Equipment: ${r.equipmentInterest??"Not specified"}`,`Source: ${r.source}`,`Request ID: ${r.id}`].join("\n");
const configuredOrganizer=()=>{const explicit=process.env.DEMO_ORGANIZER_EMAIL?.trim();if(explicit)return explicit;const from=process.env.DEMO_FROM_EMAIL?.trim();if(from&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(from))return from;throw new Error("DEMO_ORGANIZER_EMAIL or a plain DEMO_FROM_EMAIL is required for calendar invitations.");};
const attachment=(r:DemoRequest,attendeeEmail:string,attendeeName:string)=>({filename:`ids-demo-${r.id}.ics`,content:Buffer.from(createDemoIcs(r,{organizerEmail:configuredOrganizer(),attendeeEmail,attendeeName})).toString("base64"),contentType:"text/calendar; method=REQUEST; charset=UTF-8"});
export async function notifyNewDemoRequest(r:DemoRequest){return deliver(r,"ids_new_request",()=>sendIdsNotification({subject:"New Demo Request",text:`A new demo request is pending IDS approval.\n\n${details(r)}\n\nAdmin: /admin/demo-scheduling`}));}
export async function notifyDemoApproval(r:DemoRequest){const results:{customer?:string;calendar?:string}={};try{results.customer=await deliver(r,"customer_approved",()=>sendServerEmail({to:r.customerEmail,subject:"Your IDS Demo Is Confirmed",text:`Hello ${r.customerName},\n\nYour IDS demo is confirmed for ${humanDemoTime(r.requestedStartAt,r.requestedEndAt)} at ${r.propertyAddress}.\n\nMachine requested: ${r.equipmentInterest??"Not specified"}\n\nContact IDS: ${SITE_CONTACT.email.display}\n`,attachments:[attachment(r,r.customerEmail,r.customerName)]}));}catch{results.customer="failed";}const calendarEmail=process.env.DEMO_CALENDAR_EMAIL??process.env.NOTIFY_EMAIL;try{if(!calendarEmail)throw new Error("DEMO_CALENDAR_EMAIL and NOTIFY_EMAIL are missing.");results.calendar=await deliver(r,"ids_calendar_invite",()=>sendServerEmail({to:calendarEmail,subject:`IDS Demo — ${r.customerName}`,text:details(r),attachments:[attachment(r,calendarEmail,"IDS Demo Calendar")]}));}catch{results.calendar="failed";}return results;}
export async function notifyDemoDenial(r:DemoRequest){return deliver(r,"customer_denied",()=>sendServerEmail({to:r.customerEmail,subject:"Update on Your IDS Demo Request",text:`Hello ${r.customerName},\n\nMachine requested: ${r.equipmentInterest??"Not specified"}\n\n${r.adminMessage}\n\nYour requested appointment was not confirmed. You may return to the IDS website to request another available time.`}));}
export async function retryFailedDemoNotifications(r:DemoRequest){if(r.status==="pending")return{newRequest:await notifyNewDemoRequest(r).catch(()=>"failed")};if(r.status==="approved")return notifyDemoApproval(r);if(r.status==="denied")return{denial:await notifyDemoDenial(r).catch(()=>"failed")};return{};}
