import "server-only";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { addDays, centralLocalToUtc, endAtForDuration } from "./time";
import { generateAvailableSlots } from "./availability";
import type { AvailabilityException, AvailabilityRule, DemoEquipmentInterest, DemoRequest, DemoSource } from "./types";

const requestColumns="id,customer_name,customer_email,customer_phone,property_address,requested_start_at,requested_end_at,status,source,equipment_interest,admin_message,created_at,approved_at,denied_at,cancelled_at";
const mapRequest=(r:Record<string,unknown>):DemoRequest=>({id:String(r.id),customerName:String(r.customer_name),customerEmail:String(r.customer_email),customerPhone:String(r.customer_phone),propertyAddress:String(r.property_address),requestedStartAt:String(r.requested_start_at),requestedEndAt:String(r.requested_end_at),status:r.status as DemoRequest["status"],source:r.source as DemoRequest["source"],equipmentInterest:r.equipment_interest as DemoRequest["equipmentInterest"],adminMessage:r.admin_message as string|null,createdAt:String(r.created_at),approvedAt:r.approved_at as string|null,deniedAt:r.denied_at as string|null,cancelledAt:r.cancelled_at as string|null});
export async function getAvailableSlots(start:string,end:string,now=new Date()){const c=getSupabaseServiceClient();const rangeStart=centralLocalToUtc(start,"00:00")?.toISOString(),rangeEnd=centralLocalToUtc(addDays(end,1),"00:00")?.toISOString();if(!rangeStart||!rangeEnd)return[];const [{data:rules,error:rErr},{data:exceptions,error:eErr},{data:requests,error:qErr},{data:settings,error:sErr}]=await Promise.all([c.from("demo_availability_rules").select("id,weekday,enabled,start_time,end_time"),c.from("demo_availability_exceptions").select("id,starts_at,ends_at,all_day,reason").lt("starts_at",rangeEnd).gt("ends_at",rangeStart),c.from("demo_requests").select("requested_start_at,requested_end_at,status").in("status",["pending","approved"]).lt("requested_start_at",rangeEnd).gt("requested_end_at",rangeStart),c.from("demo_settings").select("duration_minutes,scheduling_horizon_days").eq("id",true).single()]);if(rErr||eErr||qErr||sErr)throw rErr??eErr??qErr??sErr;return generateAvailableSlots({start,end,now,rules:rules??[],exceptions:exceptions??[],requests:requests??[],duration:Number(settings.duration_minutes),horizon:Number(settings.scheduling_horizon_days)});}
export async function createDemoRequest(value:{name:string;email:string;phone:string;address:string;startAt:string;source:DemoSource;equipmentInterest:DemoEquipmentInterest;idempotencyKey:string}){const c=getSupabaseServiceClient(),start=new Date(value.startAt);const{data:settings,error:settingsError}=await c.from("demo_settings").select("duration_minutes").eq("id",true).single();if(settingsError)throw settingsError;const end=endAtForDuration(start,Number(settings.duration_minutes));const{data,error}=await c.rpc("demo_create_request",{p_name:value.name,p_email:value.email,p_phone:value.phone,p_address:value.address,p_start_at:start.toISOString(),p_end_at:end.toISOString(),p_source:value.source,p_equipment_interest:value.equipmentInterest,p_idempotency_key:value.idempotencyKey});if(error)throw error;return String(data);}
export async function readDemoRequest(id:string){const{data,error}=await getSupabaseServiceClient().from("demo_requests").select(requestColumns).eq("id",id).single();if(error)throw error;return mapRequest(data as Record<string,unknown>);}
export async function readDemoNotificationEvents(id:string){const{data,error}=await getSupabaseServiceClient().from("demo_notification_events").select("event_type,status,last_error").eq("request_id",id);if(error)throw error;return data??[];}
export async function readAdminScheduling(){const c=getSupabaseServiceClient();const[{data:requests,error:q},{data:rules,error:r},{data:exceptions,error:e},{data:events,error:n}]=await Promise.all([c.from("demo_requests").select(requestColumns).order("requested_start_at"),c.from("demo_availability_rules").select("id,weekday,enabled,start_time,end_time").order("weekday"),c.from("demo_availability_exceptions").select("id,starts_at,ends_at,all_day,reason").order("starts_at"),c.from("demo_notification_events").select("request_id,event_type,status,last_error")]);if(q||r||e||n)throw q??r??e??n;return{requests:(requests??[]).map(x=>mapRequest(x as Record<string,unknown>)),rules:(rules??[]).map(x=>({id:x.id,weekday:x.weekday,enabled:x.enabled,startTime:x.start_time.slice(0,5),endTime:x.end_time.slice(0,5)} as AvailabilityRule)),exceptions:(exceptions??[]).map(x=>({id:x.id,startsAt:x.starts_at,endsAt:x.ends_at,allDay:x.all_day,reason:x.reason} as AvailabilityException)),notifications:eventsByRequest(events??[])};}
function eventsByRequest(rows:{request_id:string;event_type:string;status:string;last_error:string|null}[]){return rows.reduce<Record<string,typeof rows>>((a,r)=>{(a[r.request_id]??=[]).push(r);return a;},{});}
export async function saveRules(rules:AvailabilityRule[]){const c=getSupabaseServiceClient();for(const r of rules){const{error}=await c.from("demo_availability_rules").update({enabled:r.enabled,start_time:r.startTime,end_time:r.endTime,updated_at:new Date().toISOString()}).eq("weekday",r.weekday);if(error)throw error;}}
export async function addException(value:{startsAt:string;endsAt:string;allDay:boolean;reason:string|null}){const{error}=await getSupabaseServiceClient().from("demo_availability_exceptions").insert({starts_at:value.startsAt,ends_at:value.endsAt,all_day:value.allDay,reason:value.reason});if(error)throw error;}
export async function deleteException(id:string){const{error}=await getSupabaseServiceClient().from("demo_availability_exceptions").delete().eq("id",id);if(error)throw error;}
export async function transitionRequest(id:string,action:string,message:string|null){const{data,error}=await getSupabaseServiceClient().rpc("demo_transition_request",{p_request_id:id,p_action:action,p_message:message});if(error)throw error;return data as "changed"|"unchanged";}
