import assert from "node:assert/strict";
import test from "node:test";
import { createPricingAdminHandlers } from "../lib/admin-pricing/handlers";
import type { PricingItem } from "../lib/admin-pricing/types";
import { salesModeForProductSlug } from "../lib/catalog/sales-mode";
import { catalogImportOverwritesPricing, mergePreservedPricing } from "../scripts/import-catalog";

const id = "11111111-1111-4111-8111-111111111111";
const item: PricingItem = { id, kind:"products", category:"Equipment", name:"Test", slug:"test", brand:"IDS", productName:null, publicStatus:"active", quoteOnly:false, targetLabel:null, values:{regular_price_cents:100}, effectivePriceCents:100 };
const context = (kind="products", recordId=id) => ({ params: Promise.resolve({ kind, id: recordId }) });
const request = (body: unknown) => new Request("http://local/api/admin/pricing/products/"+id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
function handlers(admin=true) { let saved: Record<string,unknown>|null=null; return { saved:()=>saved, api:createPricingAdminHandlers({isAdmin:async()=>admin,read:async()=>({items:[item]}),update:async(_kind,_id,values)=>{saved=values;return {...item,values:{...item.values,...values} as PricingItem["values"]};}}) }; }

test("unauthenticated pricing GET and PATCH are rejected",async()=>{const {api}=handlers(false);assert.equal((await api.GET()).status,401);assert.equal((await api.PATCH(request({regular_price_cents:100}),context())).status,401);});
test("pricing PATCH rejects unknown kinds and invalid UUIDs",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({regular_price_cents:100}),context("arbitrary-table"))).status,400);assert.equal((await api.PATCH(request({regular_price_cents:100}),context("products","not-a-uuid"))).status,400);});
test("pricing PATCH rejects unknown properties",async()=>{const {api}=handlers();const response=await api.PATCH(request({regular_price_cents:100,table:"catalog_products"}),context());assert.equal(response.status,422);});
test("pricing PATCH rejects negative and fractional cents",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({regular_price_cents:-1}),context())).status,422);assert.equal((await api.PATCH(request({regular_price_cents:10.5}),context())).status,422);});
test("nullable prices preserve blank inheritance while explicit zero remains zero",async()=>{const first=handlers();assert.equal((await first.api.PATCH(request({override_regular_price_cents:null}),context("product-services"))).status,200);assert.deepEqual(first.saved(),{override_regular_price_cents:null});const second=handlers();assert.equal((await second.api.PATCH(request({override_regular_price_cents:0}),context("product-services"))).status,200);assert.deepEqual(second.saved(),{override_regular_price_cents:0});});
test("pricing PATCH rejects invalid and reversed dates",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({sale_starts_at:"not-a-date"}),context())).status,422);assert.equal((await api.PATCH(request({sale_starts_at:"2026-09-02T00:00:00Z",sale_ends_at:"2026-09-01T00:00:00Z"}),context())).status,422);});
test("a valid pricing update changes only the selected allowlisted values",async()=>{const state=handlers();const response=await state.api.PATCH(request({regular_price_cents:279900,sale_price_cents:null,show_public_price:true}),context());assert.equal(response.status,200);assert.deepEqual(state.saved(),{regular_price_cents:279900,sale_price_cents:null,show_public_price:true});});
test("Pandag remains quote-only independently of admin pricing",()=>assert.equal(salesModeForProductSlug("pandag-g1"),"quote_only"));

test("normal catalog imports preserve existing live pricing and seed new records",()=>{const warnings:string[]=[];const incoming=[{slug:"existing",regular_price_cents:100,sale_price_cents:90},{slug:"new",regular_price_cents:200,sale_price_cents:null}];const existing=[{slug:"existing",regular_price_cents:999,sale_price_cents:888}];const merged=mergePreservedPricing(incoming,existing,["slug"],["regular_price_cents","sale_price_cents"],false,"catalog_products",{warn:(message)=>warnings.push(String(message)),log:()=>undefined});assert.equal(merged[0]?.regular_price_cents,999);assert.equal(merged[0]?.sale_price_cents,888);assert.equal(merged[1]?.regular_price_cents,200);assert.match(warnings[0]??"",/Preserving live pricing/);});
test("the exact overwrite flag permits deliberate spreadsheet pricing replacement",()=>{assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test",CATALOG_IMPORT_OVERWRITE_PRICING:"true"}),true);assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test",CATALOG_IMPORT_OVERWRITE_PRICING:"false"}),false);assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test"}),false);const merged=mergePreservedPricing([{slug:"existing",regular_price_cents:100}],[{slug:"existing",regular_price_cents:999}],["slug"],["regular_price_cents"],true,"catalog_products");assert.equal(merged[0]?.regular_price_cents,100);});
test("tracked Lymow workbook pricing cannot overwrite an existing database variant normally",()=>{const merged=mergePreservedPricing([{product_id:"lymow",variant_slug:"lymow-one-plus-5a",regular_price_cents:319900,sale_price_cents:299900}],[{product_id:"lymow",variant_slug:"lymow-one-plus-5a",regular_price_cents:305000,sale_price_cents:null}],["product_id","variant_slug"],["regular_price_cents","sale_price_cents"],false,"catalog_product_variants",{warn:()=>undefined,log:()=>undefined});assert.equal(merged[0]?.regular_price_cents,305000);assert.equal(merged[0]?.sale_price_cents,null);});
