import assert from "node:assert/strict";
import test from "node:test";
import { createPricingAdminHandlers } from "../lib/admin-pricing/handlers";
import { isoToLocalDateTimeInput } from "../lib/admin-pricing/datetime-local";
import type { PricingItem } from "../lib/admin-pricing/types";
import { salesModeForProductSlug } from "../lib/catalog/sales-mode";
import { scheduledPublicPrice } from "../lib/catalog/public-price";
import { selectActivePriceSchedule, type ActivePriceSchedule } from "../lib/catalog/active-price-schedule";
import { catalogImportOverwritesPricing, mergePreservedPricing, planPriceScheduleImport } from "../scripts/import-catalog";
import { readFileSync } from "node:fs";

const id = "11111111-1111-4111-8111-111111111111";
const item: PricingItem = { id, kind:"products", category:"Equipment", name:"Test", slug:"test", brand:"IDS", productName:null, publicStatus:"active", quoteOnly:false, targetLabel:null, values:{regular_price_cents:100}, effectivePriceCents:100, activeScheduleName:null };
const context = (kind="products", recordId=id) => ({ params: Promise.resolve({ kind, id: recordId }) });
const request = (body: unknown) => new Request("http://local/api/admin/pricing/products/"+id,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
function handlers(admin=true, existing:Record<string,unknown>={sale_starts_at:null,sale_ends_at:null}) { let saved: Record<string,unknown>|null=null; return { saved:()=>saved, api:createPricingAdminHandlers({isAdmin:async()=>admin,read:async()=>({items:[item]}),readValues:async()=>existing,update:async(_kind,_id,values)=>{saved=values;return {...item,values:{...item.values,...values} as PricingItem["values"]};}}) }; }

test("unauthenticated pricing GET and PATCH are rejected",async()=>{const {api}=handlers(false);assert.equal((await api.GET()).status,401);assert.equal((await api.PATCH(request({regular_price_cents:100}),context())).status,401);});
test("pricing PATCH rejects unknown kinds and invalid UUIDs",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({regular_price_cents:100}),context("arbitrary-table"))).status,400);assert.equal((await api.PATCH(request({regular_price_cents:100}),context("products","not-a-uuid"))).status,400);});
test("pricing PATCH rejects unknown properties",async()=>{const {api}=handlers();const response=await api.PATCH(request({regular_price_cents:100,table:"catalog_products"}),context());assert.equal(response.status,422);});
test("pricing PATCH rejects negative and fractional cents",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({regular_price_cents:-1}),context())).status,422);assert.equal((await api.PATCH(request({regular_price_cents:10.5}),context())).status,422);});
test("nullable prices preserve blank inheritance while explicit zero remains zero",async()=>{const first=handlers();assert.equal((await first.api.PATCH(request({override_regular_price_cents:null}),context("product-services"))).status,200);assert.deepEqual(first.saved(),{override_regular_price_cents:null});const second=handlers();assert.equal((await second.api.PATCH(request({override_regular_price_cents:0}),context("product-services"))).status,200);assert.deepEqual(second.saved(),{override_regular_price_cents:0});});
test("pricing PATCH rejects invalid and reversed dates",async()=>{const {api}=handlers();assert.equal((await api.PATCH(request({sale_starts_at:"not-a-date"}),context())).status,422);assert.equal((await api.PATCH(request({sale_starts_at:"2026-09-02T00:00:00Z",sale_ends_at:"2026-09-01T00:00:00Z"}),context())).status,422);});
test("schedule starts_at is required and partial PATCH windows use stored boundaries",async()=>{const state=handlers(true,{starts_at:"2026-08-01T00:00:00.000Z",ends_at:"2026-08-12T00:00:00.000Z"});assert.equal((await state.api.PATCH(request({starts_at:null}),context("schedules"))).status,422);assert.equal((await state.api.PATCH(request({starts_at:""}),context("schedules"))).status,422);assert.equal((await state.api.PATCH(request({starts_at:"2026-08-15T00:00:00Z"}),context("schedules"))).status,422);assert.equal((await state.api.PATCH(request({ends_at:"2026-07-31T00:00:00Z"}),context("schedules"))).status,422);});
test("a valid pricing update changes only the selected allowlisted values",async()=>{const state=handlers();const response=await state.api.PATCH(request({regular_price_cents:279900,sale_price_cents:null,show_public_price:true}),context());assert.equal(response.status,200);assert.deepEqual(state.saved(),{regular_price_cents:279900,sale_price_cents:null,show_public_price:true});});
test("Pandag remains quote-only independently of admin pricing",()=>assert.equal(salesModeForProductSlug("pandag-g1"),"quote_only"));

test("normal catalog imports preserve existing live pricing and seed new records",()=>{const warnings:string[]=[];const incoming=[{slug:"existing",regular_price_cents:100,sale_price_cents:90},{slug:"new",regular_price_cents:200,sale_price_cents:null}];const existing=[{slug:"existing",regular_price_cents:999,sale_price_cents:888}];const merged=mergePreservedPricing(incoming,existing,["slug"],["regular_price_cents","sale_price_cents"],false,"catalog_products",{warn:(message)=>warnings.push(String(message)),log:()=>undefined});assert.equal(merged[0]?.regular_price_cents,999);assert.equal(merged[0]?.sale_price_cents,888);assert.equal(merged[1]?.regular_price_cents,200);assert.match(warnings[0]??"",/Preserving live pricing/);});
test("the exact overwrite flag permits deliberate spreadsheet pricing replacement",()=>{assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test",CATALOG_IMPORT_OVERWRITE_PRICING:"true"}),true);assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test",CATALOG_IMPORT_OVERWRITE_PRICING:"false"}),false);assert.equal(catalogImportOverwritesPricing({NODE_ENV:"test"}),false);const merged=mergePreservedPricing([{slug:"existing",regular_price_cents:100}],[{slug:"existing",regular_price_cents:999}],["slug"],["regular_price_cents"],true,"catalog_products");assert.equal(merged[0]?.regular_price_cents,100);});
test("tracked Lymow workbook pricing cannot overwrite an existing database variant normally",()=>{const merged=mergePreservedPricing([{product_id:"lymow",variant_slug:"lymow-one-plus-5a",regular_price_cents:319900,sale_price_cents:299900}],[{product_id:"lymow",variant_slug:"lymow-one-plus-5a",regular_price_cents:305000,sale_price_cents:null}],["product_id","variant_slug"],["regular_price_cents","sale_price_cents"],false,"catalog_product_variants",{warn:()=>undefined,log:()=>undefined});assert.equal(merged[0]?.regular_price_cents,305000);assert.equal(merged[0]?.sale_price_cents,null);});

test("datetime-local values round-trip through local wall-clock time without shifting the instant",()=>{const stored="2026-08-10T15:30:00.000Z";const local=isoToLocalDateTimeInput(stored);assert.equal(new Date(local).toISOString(),stored);});

test("schedule import preserves matches, inserts new names on the same target, and overwrites matches deliberately",()=>{const existing=[{product_id:"product",schedule_name:"Launch",starts_at:"old"}];const incoming=[{product_id:"product",schedule_name:"Launch",starts_at:"new"},{product_id:"product",schedule_name:"Fall",starts_at:"fall"}];assert.deepEqual(planPriceScheduleImport(incoming,existing,false).map(item=>item.action),["preserve","insert"]);assert.deepEqual(planPriceScheduleImport(incoming,existing,true).map(item=>item.action),["update","insert"]);});

const basePrice={display_msrp_price_cents:12000,regular_price_cents:10000,sale_price_cents:null,sale_starts_at:null,sale_ends_at:null,promotion_label:null,show_public_price:true,contact_for_pricing:false};
const schedule=(id:string,starts_at:string,ends_at:string|null,price:number,status="active"):ActivePriceSchedule=>({id,schedule_name:id,product_id:"product",starts_at,ends_at,regular_price_cents:price,sale_price_cents:null,promotion_label:id,show_public_price:true,contact_for_pricing:false,public_status:status});
test("public pricing uses base without a schedule and ignores expired or future schedules",()=>{const now=Date.parse("2026-08-10T12:00:00Z");assert.equal(scheduledPublicPrice(basePrice,[],"product","product",now).price.currentPriceCents,10000);const inactive=[schedule("expired","2026-08-01T00:00:00Z","2026-08-09T00:00:00Z",8000),schedule("future","2026-08-11T00:00:00Z",null,7000)];assert.equal(scheduledPublicPrice(basePrice,inactive,"product","product",now).price.currentPriceCents,10000);});
test("public pricing uses an active schedule and latest start wins overlaps",()=>{const now=Date.parse("2026-08-10T12:00:00Z");const schedules=[schedule("early","2026-08-01T00:00:00Z",null,9000),schedule("latest","2026-08-08T00:00:00Z",null,8000),schedule("hidden","2026-08-09T00:00:00Z",null,7000,"hidden")];const result=scheduledPublicPrice(basePrice,schedules,"product","product",now);assert.equal(result.price.currentPriceCents,8000);assert.equal(result.schedule?.id,"latest");});
test("public display and checkout import the identical active-schedule selector",()=>{const checkout=readFileSync(new URL("../lib/checkout/pricing-resolver.ts",import.meta.url),"utf8");const publicLoader=readFileSync(new URL("../lib/catalog/public-price.ts",import.meta.url),"utf8");assert.match(checkout,/selectActivePriceSchedule/);assert.match(publicLoader,/selectActivePriceSchedule/);const selected=selectActivePriceSchedule([schedule("same","2026-08-01T00:00:00Z",null,7500)],"product","product",Date.parse("2026-08-10T12:00:00Z"));assert.equal(selected?.regular_price_cents,7500);});
