import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import BusinessCard, { OFFER_DISCLAIMER } from "../components/featured-businesses/BusinessCard";
import { phoneHref, validateFeaturedBusiness } from "../lib/featured-businesses/validation";
import type { FeaturedBusiness } from "../lib/featured-businesses/types";

const business:FeaturedBusiness={id:"10000000-0000-0000-0000-000000000001",businessName:"ABC Lawn",description:"Lawn care",operatingRegion:"Central Illinois",imageUrl:null,imagePath:null,imageAlt:null,websiteUrl:"https://abc.example/",facebookUrl:"https://facebook.com/abc",phone:"(217) 555-1234",address:null,referralCode:"IDS10",specialOffer:"10% off",isPublic:true,isFeatured:true,isArchived:false,sortOrder:1,createdAt:"2026-01-01",updatedAt:"2026-01-01"};
test("public card renders usable optional contact, referral, offer and safe tracked links",()=>{const html=renderToStaticMarkup(<BusinessCard business={business} source="homepage"/>);assert.match(html,/tel:2175551234/);assert.match(html,/destination=website&amp;source=homepage/);assert.match(html,/destination=facebook&amp;source=homepage/);assert.match(html,/IDS10/);assert.match(html,/10% off/);assert.match(html,new RegExp(OFFER_DISCLAIMER.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(html,/noopener noreferrer/);});
test("optional fields do not produce empty UI or offer disclaimer",()=>{const html=renderToStaticMarkup(<BusinessCard business={{...business,websiteUrl:null,facebookUrl:null,phone:null,operatingRegion:null,referralCode:null,specialOffer:null}} source="directory"/>);assert.doesNotMatch(html,/Phone|Serving|IDS Referral Code|Special Offer|Visit Website|Facebook/);assert.doesNotMatch(html,/Offers are provided/);});
test("phone links preserve a leading plus and remove formatting",()=>assert.equal(phoneHref("+1 (217) 555-1234"),"tel:+12175551234"));
test("validation rejects hidden or archived featured records and unsafe URL schemes",()=>{assert.equal(validateFeaturedBusiness({...business,isPublic:false}).ok,false);assert.equal(validateFeaturedBusiness({...business,isArchived:true}).ok,false);assert.equal(validateFeaturedBusiness({...business,websiteUrl:"javascript:alert(1)"}).ok,false);});
test("migration enforces directory visibility, one featured record, atomic switching, and no public writes",()=>{const sql=readFileSync("supabase/migrations/20260812150000_create_featured_business_spotlight.sql","utf8");assert.match(sql,/unique index featured_businesses_single_featured_idx/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/using\(is_public and not is_archived\)/);assert.match(sql,/revoke all[^;]+from public,anon,authenticated,service_role/);assert.doesNotMatch(sql,/grant (insert|update|delete)[^;]+to anon|grant (insert|update|delete)[^;]+to authenticated/i);assert.match(sql,/destination_type in\('website','facebook'\)/);});
test("homepage placement follows Featured Machines and mobile placement follows its catalog",()=>{const desktop=readFileSync("app/page.tsx","utf8"),mobile=readFileSync("components/mobile/MobileHomepage.tsx","utf8");assert.ok(desktop.indexOf("<HomeBusinessSpotlight />")>desktop.indexOf("<EquipmentCatalog />"));assert.match(mobile,/Featured Machines[\s\S]*?<EquipmentCatalog \/><HomeBusinessSpotlight \/>/);});
test("redirect loads a stored URL and never accepts an arbitrary URL parameter",()=>{const source=readFileSync("app/api/featured-businesses/[id]/redirect/route.ts","utf8");assert.match(source,/website_url/);assert.match(source,/facebook_url/);assert.match(source,/featured_business_clicks/);assert.doesNotMatch(source,/search\.get\(["']url["']\)/);});
test("admin routes enforce existing authentication and support CRUD, image, and feature RPC",()=>{for(const file of ["app/api/admin/featured-businesses/route.ts","app/api/admin/featured-businesses/[id]/route.ts","app/api/admin/featured-businesses/[id]/image/route.ts"])assert.match(readFileSync(file,"utf8"),/isReviewAdmin/);const server=readFileSync("lib/featured-businesses/server.ts","utf8");assert.match(server,/set_featured_business/);assert.match(server,/deleteBusiness/);});
test("general business saves cannot assign storage objects; only the scoped image API writes image paths",()=>{const server=readFileSync("lib/featured-businesses/server.ts","utf8");const rowDefinition=server.match(/const row = [^;]+;/)?.[0]??"";assert.doesNotMatch(rowDefinition,/image_url|image_path/);const imageRoute=readFileSync("app/api/admin/featured-businesses/[id]/image/route.ts","utf8");assert.match(imageRoute,/businesses\/\$\{id\}\//);assert.match(imageRoute,/\.eq\("id",id\)/);});
test("Aftermarket implementation remains isolated from this feature",()=>{const changedFeatureFiles=["app/page.tsx","components/mobile/MobileHomepage.tsx","components/admin/AdminNav.tsx","supabase/migrations/20260812150000_create_featured_business_spotlight.sql"];for(const file of changedFeatureFiles)assert.doesNotMatch(readFileSync(file,"utf8"),/ids-aftermarket|aftermarket_label|catalog_options/);});
