import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { renderToStaticMarkup } from "react-dom/server";
import BusinessCard, { OFFER_DISCLAIMER } from "../components/featured-businesses/BusinessCard";
import { phoneHref, validateFeaturedBusiness } from "../lib/featured-businesses/validation";
import type { FeaturedBusiness } from "../lib/featured-businesses/types";
import { derivePhoneAreaCode } from "../lib/featured-businesses/location";
import { filterBusinesses } from "../lib/featured-businesses/search";
import { validateFeaturedBusinessRequest } from "../lib/featured-businesses/request-validation";
import { validateBusinessImage } from "../lib/featured-businesses/image-validation";
import { notifyFeaturedBusinessRequest } from "../lib/featured-businesses/request-notification";
import { reminderKind } from "../lib/featured-businesses/listing-lifecycle-policy";
import { isCronAuthorized } from "../lib/featured-businesses/cron-auth";
import {
  HOMEPAGE_ROTATION_INTERVAL_MS,
  isActivePublicBusiness,
  nextBusinessIndex,
  previousBusinessIndex,
  scheduleSpotlightRotation,
  selectInitialBusinessIndex,
} from "../lib/featured-businesses/homepage-rotation";

const business:FeaturedBusiness={id:"10000000-0000-0000-0000-000000000001",businessName:"ABC Lawn",description:"Lawn care",operatingRegion:"Central Illinois",imageUrl:null,imagePath:null,imageAlt:null,websiteUrl:"https://abc.example/",facebookUrl:"https://facebook.com/abc",phone:"(217) 555-1234",address:null,businessCity:null,businessState:null,businessCounty:null,postalCode:null,phoneAreaCode:"217",serviceAreas:[],referralCode:"IDS10",specialOffer:"10% off",isPublic:true,isFeatured:true,isArchived:false,sortOrder:1,listingStartedAt:"2026-01-01",listingExpiresAt:"2026-07-01",listingGraceUntil:"2026-07-31",listingExpiredAt:null,lastRenewedAt:null,renewalCount:0,createdAt:"2026-01-01",updatedAt:"2026-01-01"};
test("public card renders usable optional contact, referral, offer and safe tracked links",()=>{const html=renderToStaticMarkup(<BusinessCard business={business} source="homepage"/>);assert.match(html,/tel:2175551234/);assert.match(html,/destination=website&amp;source=homepage/);assert.match(html,/destination=facebook&amp;source=homepage/);assert.match(html,/IDS10/);assert.match(html,/10% off/);assert.match(html,new RegExp(OFFER_DISCLAIMER.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(html,/noopener noreferrer/);});
test("optional fields do not produce empty UI or offer disclaimer",()=>{const html=renderToStaticMarkup(<BusinessCard business={{...business,websiteUrl:null,facebookUrl:null,phone:null,operatingRegion:null,referralCode:null,specialOffer:null}} source="directory"/>);assert.doesNotMatch(html,/Phone|Serving|IDS Referral Code|Special Offer|Visit Website|Facebook/);assert.doesNotMatch(html,/Offers are provided/);});
test("phone links preserve a leading plus and remove formatting",()=>assert.equal(phoneHref("+1 (217) 555-1234"),"tel:+12175551234"));
test("validation rejects hidden or archived featured records and unsafe URL schemes",()=>{assert.equal(validateFeaturedBusiness({...business,isPublic:false}).ok,false);assert.equal(validateFeaturedBusiness({...business,isArchived:true}).ok,false);assert.equal(validateFeaturedBusiness({...business,websiteUrl:"javascript:alert(1)"}).ok,false);});
test("migration enforces directory visibility, one featured record, atomic switching, and no public writes",()=>{const sql=readFileSync("supabase/migrations/20260812150000_create_featured_business_spotlight.sql","utf8");assert.match(sql,/unique index featured_businesses_single_featured_idx/);assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/using\(is_public and not is_archived\)/);assert.match(sql,/revoke all[^;]+from public,anon,authenticated,service_role/);assert.doesNotMatch(sql,/grant (insert|update|delete)[^;]+to anon|grant (insert|update|delete)[^;]+to authenticated/i);assert.match(sql,/destination_type in\('website','facebook'\)/);});
test("desktop and mobile spotlights are home-only after price match",()=>{const desktop=readFileSync("components/home/DesktopHomepage.tsx","utf8"),mobile=readFileSync("components/mobile/MobileHomepage.tsx","utf8");for(const source of [desktop,mobile]){const home=source.slice(source.indexOf('view === "home"'),source.indexOf('view !== "home"'));assert.match(home,/<HomeSalesSpecial \/><HomePriceMatch \/><HomeBusinessSpotlight \/>/);const machines=source.match(/view === "machines"[\s\S]*?<EquipmentCatalog \/><\/div>/)?.[0]??"";assert.ok(machines);assert.doesNotMatch(machines,/HomeBusinessSpotlight/);}});
test("redirect loads a stored URL and never accepts an arbitrary URL parameter",()=>{const source=readFileSync("app/api/featured-businesses/[id]/redirect/route.ts","utf8");assert.match(source,/website_url/);assert.match(source,/facebook_url/);assert.match(source,/featured_business_clicks/);assert.doesNotMatch(source,/search\.get\(["']url["']\)/);});
test("admin routes enforce existing authentication and support CRUD, image, and feature RPC",()=>{for(const file of ["app/api/admin/featured-businesses/route.ts","app/api/admin/featured-businesses/[id]/route.ts","app/api/admin/featured-businesses/[id]/image/route.ts"])assert.match(readFileSync(file,"utf8"),/isReviewAdmin/);const server=readFileSync("lib/featured-businesses/server.ts","utf8");assert.match(server,/set_featured_business/);assert.match(server,/deleteBusiness/);});
test("general business saves cannot assign storage objects; only the scoped image API writes image paths",()=>{const server=readFileSync("lib/featured-businesses/server.ts","utf8");const rowDefinition=server.match(/const row = [^;]+;/)?.[0]??"";assert.doesNotMatch(rowDefinition,/image_url|image_path/);const imageRoute=readFileSync("app/api/admin/featured-businesses/[id]/image/route.ts","utf8");assert.match(imageRoute,/businesses\/\$\{id\}\//);assert.match(imageRoute,/\.eq\("id",id\)/);});
test("Aftermarket implementation remains isolated from this feature",()=>{const changedFeatureFiles=["app/page.tsx","components/mobile/MobileHomepage.tsx","components/admin/AdminNav.tsx","supabase/migrations/20260812150000_create_featured_business_spotlight.sql"];for(const file of changedFeatureFiles)assert.doesNotMatch(readFileSync(file,"utf8"),/ids-aftermarket|aftermarket_label|catalog_options/);});

const validRequest={contactName:"Jane Owner",contactEmail:" JANE@example.com ",businessName:"Wayne Works",description:"Land clearing and excavation",businessCity:"Piedmont",businessState:"MO",businessCounty:"Wayne County",postalCode:"63957",operatingRegion:"Southeast Missouri",phone:null,address:null,websiteUrl:"https://example.com",facebookUrl:"https://facebook.com/example",specialOffer:null,additionalNotes:null,consentConfirmed:true,serviceAreas:[{stateCode:"MO",countyName:"Butler County",statewide:false}]};
test("application validates private/public required fields and keeps phone and street address optional",()=>{const parsed=validateFeaturedBusinessRequest(validRequest);assert.equal(parsed.ok,true);if(parsed.ok){assert.equal(parsed.value.contactEmail,"jane@example.com");assert.equal(parsed.value.phone,null);assert.equal(parsed.value.phoneAreaCode,null);assert.equal(parsed.value.address,null);assert.deepEqual(parsed.value.serviceAreas.map(x=>x.countyName),["Wayne County","Butler County"])}for(const key of ["contactName","contactEmail","businessName","description","businessState","businessCounty"]){const result=validateFeaturedBusinessRequest({...validRequest,[key]:""});assert.equal(result.ok,false,key)}assert.equal(validateFeaturedBusinessRequest({...validRequest,contactEmail:"bad"}).ok,false);assert.equal(validateFeaturedBusinessRequest({...validRequest,consentConfirmed:false}).ok,false);assert.equal(validateFeaturedBusinessRequest({...validRequest,websiteUrl:"javascript:alert(1)"}).ok,false);assert.equal(validateFeaturedBusinessRequest({...validRequest,facebookUrl:"https://example.com"}).ok,false);});
test("public application rejects privilege injection",()=>{for(const key of ["isPublic","isFeatured","isArchived","sortOrder","referralCode","status","approvedBusinessId","imageUrl","imagePath","phoneAreaCode"]){assert.equal(validateFeaturedBusinessRequest({...validRequest,[key]:key==="sortOrder"?0:true}).ok,false,key)}});
test("phone area code is derived only from a valid optional US phone",()=>{assert.equal(derivePhoneAreaCode("(573) 555-1234"),"573");assert.equal(derivePhoneAreaCode("+1 573 555 1234"),"573");assert.equal(derivePhoneAreaCode(null),null);assert.equal(derivePhoneAreaCode("123"),null)});
test("image magic bytes accept JPEG PNG WebP and reject SVG, mismatches, and oversized files",async()=>{const jpeg=new File([new Uint8Array([0xff,0xd8,0xff,0,0])],"x.jpg",{type:"image/jpeg"}),png=new File([new Uint8Array([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])],"x.png",{type:"image/png"}),webp=new File([new TextEncoder().encode("RIFF0000WEBP")],"x.webp",{type:"image/webp"});for(const file of [jpeg,png,webp])assert.equal((await validateBusinessImage(file)).ok,true);assert.equal((await validateBusinessImage(new File(["<svg/>"],"x.svg",{type:"image/svg+xml"}))).ok,false);assert.equal((await validateBusinessImage(new File(["no"],"x.jpg",{type:"image/jpeg"}))).ok,false);assert.equal((await validateBusinessImage(new File([new Uint8Array(5*1024*1024+1)],"x.png",{type:"image/png"}))).ok,false)});
test("directory filters base/service/statewide/area code and keyword public fields",()=>{const a={...business,id:"a",businessName:"Business A",description:"Excavation",businessState:"MO",businessCounty:"Wayne County",phone:"573-555-1000",phoneAreaCode:"573",serviceAreas:[{stateCode:"MO",countyName:"Wayne County",statewide:false},{stateCode:"MO",countyName:"Butler County",statewide:false}]},b={...business,id:"b",businessName:"Business B",businessState:"MO",businessCounty:"Cape Girardeau County",phone:null,phoneAreaCode:null,serviceAreas:[{stateCode:"MO",countyName:null,statewide:true}]};for(const county of ["Wayne County","Butler County"])assert.deepEqual(filterBusinesses([a,b],{state:"MO",county}).map(x=>x.id),["a","b"]);assert.deepEqual(filterBusinesses([a,b],{state:"MO"}).map(x=>x.id),["a","b"]);assert.deepEqual(filterBusinesses([a,b],{areaCode:"573"}).map(x=>x.id),["a"]);assert.deepEqual(filterBusinesses([a,b],{q:"Wayne"}).map(x=>x.id),["a"])});
test("phone and street address omit cleanly while structured location remains public",()=>{const html=renderToStaticMarkup(<BusinessCard business={{...business,businessState:"MO",businessCounty:"Wayne County",serviceAreas:[{stateCode:"MO",countyName:"Wayne County",statewide:false}],phone:null,address:null}} source="directory"/>);assert.match(html,/Wayne County/);assert.doesNotMatch(html,/>Phone<|>Address</)});
test("homepage and directory expose both CTAs and filter controls",()=>{const home=readFileSync("components/featured-businesses/HomeBusinessSpotlight.tsx","utf8"),directory=readFileSync("app/featured-businesses/page.tsx","utf8");assert.match(home,/Discover Featured Businesses/);assert.match(home,/Request to be a Featured Business/);assert.match(home,/featured-businesses\/request/);for(const text of ["Search businesses or services","State","County","Area Code","Clear Filters"])assert.match(directory,new RegExp(text))});
test("request migration locks private rows/storage and approval to service role",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");assert.match(sql,/featured_business_requests force row level security/);assert.match(sql,/featured_business_request_service_areas force row level security/);assert.match(sql,/revoke all on table public\.featured_business_requests from public, anon, authenticated/);assert.match(sql,/featured-business-request-images','featured-business-request-images',false/);assert.doesNotMatch(sql,/create policy[^;]+featured-business-request-images/i);assert.match(sql,/revoke all on function public\.approve_featured_business_request[^;]+from public, anon, authenticated/);assert.match(sql,/grant execute on function public\.approve_featured_business_request[^;]+to service_role/);assert.match(sql,/interval '24 hours'/);assert.match(sql,/>= 3/);assert.match(sql,/submission_fingerprint text check/);assert.match(sql,/is_featured,is_archived,sort_order[^;]+true,false,false,100/);const approval=sql.slice(sql.indexOf("create function public.approve_featured_business_request"),sql.indexOf("revoke all on function public.approve_featured_business_request"));assert.doesNotMatch(approval,/set_featured_business/)});
test("public projections never include applicant or request data",()=>{const projection=readFileSync("lib/featured-businesses/public.ts","utf8");for(const privateField of ["contact_name","contact_email","additional_notes","admin_notes","logo_path"])assert.doesNotMatch(projection,new RegExp(privateField));});
test("submission notification is useful and never includes a private storage URL",async()=>{let sent:{subject:string;text:string}|null=null;const parsed=validateFeaturedBusinessRequest(validRequest);assert.equal(parsed.ok,true);if(!parsed.ok)return;await notifyFeaturedBusinessRequest(parsed.value,async message=>{sent=message;return {} as never});assert.ok(sent);assert.match((sent as {text:string}).text,/Wayne Works|Jane Owner|Wayne County|Logo: Uploaded/);assert.doesNotMatch((sent as {text:string}).text,/featured-business-request-images|storage\/v1/)});

test("listing migration assigns six calendar months plus 30-day grace to approvals and legacy public businesses",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");assert.match(sql,/listing_started_at timestamptz/);assert.match(sql,/listing_expires_at timestamptz/);assert.match(sql,/listing_grace_until timestamptz/);assert.match(sql,/where is_public and not is_archived/);assert.match(sql,/listing_expires_at\s*=\s*now\(\)\s*\+\s*interval '6 months'/);assert.match(sql,/listing_grace_until\s*=\s*now\(\)\s*\+\s*interval '6 months'\s*\+\s*interval '30 days'/);assert.match(sql,/values\(p_business_id[\s\S]+now\(\),now\(\)\+interval '6 months',now\(\)\+interval '6 months'\+interval '30 days',0\)/);assert.match(sql,/before insert or update of is_public, is_archived on public\.featured_businesses/);assert.match(sql,/new\.listing_grace_until = new\.listing_expires_at \+ interval '30 days'/)});
test("approval privately copies request renewal contact and remains idempotent",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");assert.match(sql,/featured_business_listing_contacts\(featured_business_id,contact_name,contact_email\)/);assert.match(sql,/request_row\.contact_name,request_row\.contact_email/);assert.match(sql,/if request_row\.approved_business_id is not null then return request_row\.approved_business_id/)});
test("renewal contacts and cleanup queue are forced-RLS service-role-only data",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");for(const table of ["featured_business_listing_contacts","featured_business_image_cleanup_queue"]){assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(sql,new RegExp(`alter table public\\.${table} force row level security`));assert.match(sql,new RegExp(`revoke all on table public\\.${table} from public,anon,authenticated`))}assert.doesNotMatch(readFileSync("lib/featured-businesses/public.ts","utf8"),/contact_email|contact_name|reminder_30_sent_at|reminder_7_sent_at/)});
test("public business and service-area RLS require an unexpired listing",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");assert.match(sql,/Active featured businesses are publicly readable[\s\S]+listing_expires_at > now\(\)/);assert.match(sql,/Active public business service areas are readable[\s\S]+business\.listing_expires_at > now\(\)/);assert.match(sql,/Featured business must be active, public, and not archived/)});
test("reminder windows select each reminder once and leave failed reminders eligible",()=>{const now=new Date("2026-01-01T00:00:00Z"),candidate={businessId:"a",businessName:"A",contactEmail:"renew@example.com",expiresAt:"2026-01-25T00:00:00Z",reminder30SentAt:null,reminder7SentAt:null};assert.equal(reminderKind(candidate,now),30);assert.equal(reminderKind({...candidate,reminder30SentAt:now.toISOString()},now),null);assert.equal(reminderKind({...candidate,expiresAt:"2026-01-06T00:00:00Z"},now),7);assert.equal(reminderKind({...candidate,expiresAt:"2026-01-06T00:00:00Z",reminder7SentAt:now.toISOString()},now),null);assert.equal(reminderKind({...candidate,contactEmail:null},now),30)});
test("lifecycle marks reminders only after send and isolates missing email and failures",()=>{const source=readFileSync("lib/featured-businesses/listing-lifecycle.ts","utf8");assert.match(source,/await deps\.send\([\s\S]+await deps\.markReminder/);assert.match(source,/if\(!kind\|\|!candidate\.contactEmail\)continue/);assert.match(source,/renewal reminder failed/);assert.match(source,/counts\.expired=await deps\.expire/)});
test("expiration, renewal and purge SQL preserve all lifecycle invariants",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8"),runtime=readFileSync("lib/featured-businesses/listing-lifecycle.ts","utf8");assert.match(runtime,/is_public:false,is_featured:false,listing_expired_at:at/);assert.match(sql,/business_row\.listing_expires_at\+interval '6 months'/);assert.match(sql,/new_expiration=now\(\)\+interval '6 months'/);assert.match(sql,/listing_grace_until=new_expiration\+interval '30 days'/);assert.match(sql,/listing_expired_at=null,last_renewed_at=now\(\),renewal_count=renewal_count\+1/);assert.match(sql,/reminder_30_sent_at=null,reminder_7_sent_at=null/);assert.match(sql,/if business_row\.is_archived then raise exception/);assert.match(sql,/is_featured=case when business_row\.listing_expires_at is null or business_row\.listing_expires_at<=now\(\) then false else is_featured end/)});
test("purge cascades completed request data and queues images before deleting business",()=>{const sql=readFileSync("supabase/migrations/20260825232100_featured_business_directory_requests.sql","utf8");assert.match(sql,/approved_business_id uuid references public\.featured_businesses\(id\) on delete cascade/);assert.match(sql,/insert into public\.featured_business_image_cleanup_queue\(image_path\)[\s\S]+delete from public\.featured_businesses/);assert.match(sql,/featured_business_service_areas[\s\S]+references public\.featured_businesses\(id\) on delete cascade/);assert.match(readFileSync("supabase/migrations/20260812150000_create_featured_business_spotlight.sql","utf8"),/featured_business_id uuid not null references public\.featured_businesses\(id\) on delete cascade/)});
test("image cleanup deletes queue rows only after successful storage removal",()=>{const source=readFileSync("lib/featured-businesses/server.ts","utf8");assert.match(source,/storage\.from\("featured-business-images"\)\.remove/);assert.match(source,/if\(removeError\)[\s\S]+continue}[\s\S]+featured_business_image_cleanup_queue"\)\.delete/)});
test("cron is daily, fail-closed, constant-time, and aggregate-only",()=>{const config=JSON.parse(readFileSync("vercel.json","utf8")),route=readFileSync("app/api/cron/featured-business-lifecycle/route.ts","utf8"),auth=readFileSync("lib/featured-businesses/cron-auth.ts","utf8"),secret="a".repeat(32);assert.deepEqual(config.crons,[{path:"/api/cron/featured-business-lifecycle",schedule:"0 14 * * *"}]);assert.equal(isCronAuthorized(null,undefined),false);assert.equal(isCronAuthorized("Bearer wrong",secret),false);assert.equal(isCronAuthorized(`Bearer ${secret}`,secret),true);assert.match(route,/CRON_SECRET/);assert.match(auth,/timingSafeEqual/);assert.match(route,/status:401/);assert.doesNotMatch(route,/contactEmail|contact_name|contact_email/)});
test("manual editor exposes private renewal contact, lifecycle status, and renew control",()=>{const source=readFileSync("app/admin/featured-businesses/page.tsx","utf8");for(const text of ["LISTING TERM","PRIVATE RENEWAL CONTACT","RENEWAL EMAIL NOT PROVIDED","Renew +6 Months","EXPIRING SOON","Grace Period Ends"])assert.ok(source.includes(text),text)});
test("directory intentionally keeps in-memory search and raises only the source cap to 500",()=>{const source=readFileSync("lib/featured-businesses/server.ts","utf8");assert.match(source,/else query=query\.limit\(500\)/);assert.doesNotMatch(source,/limit\(200\)/);assert.match(readFileSync("app/api/featured-businesses/route.ts","utf8"),/Math\.min\(24/)});

test("homepage uses the all-business rotation endpoint once instead of featured selection",()=>{const source=readFileSync("components/featured-businesses/HomeBusinessSpotlight.tsx","utf8");assert.match(source,/fetch\("\/api\/featured-businesses\?homepageRotation=true"/);assert.doesNotMatch(source,/featured=true/);assert.equal(source.match(/fetch\(/g)?.length,1);assert.match(source,/source="homepage"/)});
test("homepage rotation endpoint keeps directory paging at 24 but returns its active set before paging",()=>{const source=readFileSync("app/api/featured-businesses/route.ts","utf8"),server=readFileSync("lib/featured-businesses/server.ts","utf8");assert.match(source,/Math\.min\(24/);assert.match(source,/if \(homepageRotation\)[\s\S]+return Response\.json\(\{ businesses, count: businesses\.length \}\)/);assert.match(server,/query=query\.limit\(500\)/);assert.match(source,/readPublicBusinesses\(featured && !homepageRotation\)/)});
test("homepage eligibility admits only unarchived public businesses with a future expiration",()=>{const now=Date.parse("2026-08-25T12:00:00Z");assert.equal(isActivePublicBusiness({...business,listingExpiresAt:"2026-08-26T12:00:00Z"},now),true);assert.equal(isActivePublicBusiness({...business,isPublic:false},now),false);assert.equal(isActivePublicBusiness({...business,isArchived:true},now),false);assert.equal(isActivePublicBusiness({...business,listingExpiresAt:"2026-08-25T12:00:00Z"},now),false);assert.equal(isActivePublicBusiness({...business,listingExpiresAt:null},now),false)});
test("random starting index is selected once from injected randomness",()=>{let calls=0;const random=()=>{calls++;return .74};assert.equal(selectInitialBusinessIndex(4,random),2);assert.equal(calls,1);assert.equal(selectInitialBusinessIndex(1,random),0);assert.equal(calls,2);assert.equal(selectInitialBusinessIndex(0,random),0);assert.equal(calls,2)});
test("next and previous rotation wrap correctly",()=>{assert.equal(nextBusinessIndex(0,3),1);assert.equal(nextBusinessIndex(2,3),0);assert.equal(previousBusinessIndex(1,3),0);assert.equal(previousBusinessIndex(0,3),2);assert.equal(nextBusinessIndex(0,1),0)});
test("seven-second rotation scheduler advances once and cleanup cancels it",()=>{let scheduledDelay=0,callback:(()=>void)|null=null,cancelled=false,advances=0;const cleanup=scheduleSpotlightRotation(()=>advances++,undefined,(next,delay)=>{callback=next;scheduledDelay=delay;return 9 as unknown as ReturnType<typeof setTimeout>},()=>{cancelled=true});assert.equal(scheduledDelay,HOMEPAGE_ROTATION_INTERVAL_MS);assert.equal(advances,0);(callback as unknown as ()=>void)();assert.equal(advances,1);cleanup();assert.equal(cancelled,true)});
test("homepage rotation pauses for hover and focus and restarts its single timeout after navigation",()=>{const source=readFileSync("components/featured-businesses/HomeBusinessSpotlight.tsx","utf8");assert.match(source,/businesses\.length < 2 \|\| isPointerInside \|\| isFocusInside/);assert.match(source,/onPointerEnter=\{\(\) => setIsPointerInside\(true\)\}/);assert.match(source,/onPointerLeave=\{\(\) => setIsPointerInside\(false\)\}/);assert.match(source,/onFocus=\{\(\) => setIsFocusInside\(true\)\}/);assert.match(source,/setIsFocusInside\(false\)/);assert.match(source,/setRotationEpoch\(\(epoch\) => epoch \+ 1\)/);assert.match(source,/return scheduleSpotlightRotation/)});
test("one business has no control clutter while multi-business controls stay accessible",()=>{const source=readFileSync("components/featured-businesses/HomeBusinessSpotlight.tsx","utf8");assert.match(source,/const hasRotation = businesses\.length > 1/);assert.match(source,/\{hasRotation \? \(/);assert.match(source,/aria-label="Show previous featured business"/);assert.match(source,/aria-label="Show next featured business"/);assert.match(source,/HOMEPAGE_ROTATION_DOT_LIMIT/);assert.match(source,/of \{businesses\.length\}/)});
test("homepage retains disclaimer CTAs and dealer resources without automatic live announcements",()=>{const source=readFileSync("components/featured-businesses/HomeBusinessSpotlight.tsx","utf8");for(const value of ["INDEPENDENT_BUSINESS_DISCLAIMER","Discover Featured Businesses","Request to be a Featured Business","Dealer &amp; Tech Community Resources","Open Dealer &amp; Tech Portal"])assert.match(source,new RegExp(value));assert.doesNotMatch(source,/aria-live/)});
test("homepage fade is subtle and disabled for reduced motion",()=>{const css=readFileSync("components/featured-businesses/HomeBusinessSpotlight.module.css","utf8");assert.match(css,/400ms ease-out/);assert.match(css,/@media \(prefers-reduced-motion: reduce\)/);assert.match(css,/animation: none/)});
test("homepage rotation response remains on the established public projection",()=>{const route=readFileSync("app/api/featured-businesses/route.ts","utf8"),projection=readFileSync("lib/featured-businesses/public.ts","utf8");assert.match(route,/readPublicBusinesses/);for(const privateField of ["contact_name","contact_email","additional_notes","admin_notes","submission_fingerprint","request_status"])assert.doesNotMatch(projection,new RegExp(privateField))});
