import assert from 'node:assert/strict';import test from 'node:test';
import {processorFixture} from './helpers/installation-stripe-fixtures';
import {installationStripeProjection,validateInstallationPayment} from '../lib/installations/stripe-policy';
import {requiredFundsBeforeDeadline} from '../lib/installations/admin-policy';
import type Stripe from 'stripe';
for(const [label,target,patch] of [
 ['session mode','session',{livemode:true}],['session amount','session',{amount_total:24999}],['session currency','session',{currency:'cad'}],['session ownership','session',{metadata:{ids_kind:'professional_installation',installation_id:'foreign',purpose:'deposit'}}],
 ['purpose','session',{metadata:{ids_kind:'professional_installation',installation_id:'11111111-1111-4111-8111-111111111111',purpose:'balance'}}],['method','session',{payment_method_types:['us_bank_account']}],['payment status','session',{payment_status:'unpaid'}],['session reference','session',{id:'cs_test_wrong'}],
 ['intent reference','intent',{id:'pi_wrong'}],['intent status','intent',{status:'requires_payment_method'}],['intent amount received','intent',{amount_received:0}],['intent amount','intent',{amount:24999}],['intent currency','intent',{currency:'cad'}],['intent live','intent',{livemode:true}],['intent missing mode','intent',{livemode:undefined}],['intent latest charge','intent',{latest_charge:'ch_wrong'}],['capture','intent',{capture_method:'manual'}],
 ['charge reference','charge',{id:'ch_wrong'}],['charge live','charge',{livemode:true}],['charge missing mode','charge',{livemode:undefined}],['charge unpaid','charge',{paid:false}],['charge uncaptured','charge',{captured:false}],['charge amount','charge',{amount_captured:0}],['charge currency','charge',{currency:'cad'}],['charge intent','charge',{payment_intent:'pi_wrong'}],['charge metadata','charge',{metadata:{}}],
] as const)test(`controlled Stripe evidence rejects ${label}`,()=>{const f=processorFixture();Object.assign(f[target],patch);assert.throws(()=>validateInstallationPayment(f.session,f.intent,f.charge,f.p));});
test('required payment labeled deposit settles the entire initial amount inside 72 hours',()=>{const f=processorFixture(100000,{status:'pending',paid_at:null});const result=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[],null);assert.equal(result.balance.balanceDueCents,0);assert.equal(result.balance.netPaidCents,100000);assert.equal(result.evidence.purpose,'deposit');});
test('actual occurrence, delayed notification, and strict normal deadline remain distinct',()=>{const f=processorFixture(100000);f.state.installation.balance_due_at=new Date(f.charge.created*1000+1000).toISOString();const delayed=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[],null,'2026-10-31T12:00:00Z');assert.equal(Date.parse(delayed.evidence.paymentOccurredAt!),f.charge.created*1000);assert.equal(requiredFundsBeforeDeadline(f.state),true);f.state.installation.balance_due_at=f.p.paid_at;assert.equal(requiredFundsBeforeDeadline(f.state),false);});
for(const status of ['pending','requires_action','failed','canceled','succeeded'] as const)test(`controlled refund ${status} has the correct financial meaning`,()=>{const f=processorFixture();f.charge.amount_refunded=5000;const r=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[f.refund(5000,status)],1000);assert.equal(r.balance.netPaidCents,status==='succeeded'?20000:25000);assert.equal(r.balance.pendingRefundsCents,['pending','requires_action'].includes(status)?5000:0);assert.equal(r.refundRows[0].paid_at,status==='succeeded'?new Date((f.charge.created+120)*1000).toISOString():null);});
test('refund creation time is never invented as a success time without occurrence evidence',()=>{const f=processorFixture();const refund=f.refund();refund.balance_transaction=null;f.charge.amount_refunded=5000;const result=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],null);assert.equal(result.refundRows[0].paid_at,null);assert.notEqual(result.refundRows[0].processor_created_at,null);});
test('partial refund keeps the remaining payment credit and separate notifications do not duplicate refunds',()=>{const f=processorFixture();const refund=f.refund();f.charge.amount_refunded=5000;const a=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],1000);f.p.refunded_cents=5000;f.p.status='partially_refunded';f.state.payments.push(...a.refundRows);const b=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],2000);assert.equal(a.refundRows[0].id,b.refundRows[0].id);assert.equal(b.balance.netPaidCents,20000);});
test('confirmed refund resists an old pending event; later failure requires actual failure transaction proof',()=>{const f=processorFixture();const refund=f.refund();f.charge.amount_refunded=5000;const success=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],1000);f.p.refunded_cents=5000;f.p.status='partially_refunded';f.state.payments.push(...success.refundRows);refund.status='pending';assert.equal(installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],999).balance.netPaidCents,20000);refund.status='failed';assert.throws(()=>installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],1001),/regression/);refund.failure_balance_transaction='txn_failure';assert.throws(()=>installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],999),/regression/);assert.equal(installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],1001).balance.netPaidCents,25000);});
for(const patch of [{charge:'ch_foreign'},{payment_intent:'pi_foreign'},{currency:'cad'},{amount:25001},{amount:0},{amount:1.5},{status:'unknown'}])test(`refund rejects forged ${JSON.stringify(patch)}`,()=>{const f=processorFixture();f.charge.amount_refunded=5000;assert.throws(()=>installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[{...f.refund(),...patch} as Stripe.Refund],null));});
test('duplicate processor references and incomplete refund lists fail closed',()=>{const f=processorFixture();f.charge.amount_refunded=5000;const refund=f.refund();assert.throws(()=>installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund,refund],null),/duplicate_refund/);const first=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[refund],null);f.state.payments.push(...first.refundRows);assert.throws(()=>installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[],null),/incomplete_refund_list/);});
test('an old deposit observation cannot remove newer cash credit',()=>{const f=processorFixture();f.state.payments.push({id:'cash',method:'cash',purpose:'cash',status:'paid',paid_at:f.p.paid_at,amount_cents:75000,refunded_cents:0});const result=installationStripeProjection(f.state,f.p,f.session,f.intent,f.charge,[],1);assert.equal(result.balance.netPaidCents,100000);assert.equal(result.balance.balanceDueCents,0);});
