import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { renderToStaticMarkup } from "react-dom/server";
import ContactInformationModal from "../components/contact/ContactInformationModal";
import HomePriceMatch from "../components/promotions/HomePriceMatch";
import { createPriceMatchAdminHandlers } from "../lib/price-match/admin-handlers";
import { DEFAULT_PRICE_MATCH, validatePriceMatch } from "../lib/price-match/config";

test("Meet or Beat admin requires authentication and supports all editable fields",async()=>{let saved=DEFAULT_PRICE_MATCH;const unauthorized=createPriceMatchAdminHandlers({isAdmin:async()=>false,read:async()=>saved,save:async value=>value});assert.equal((await unauthorized.GET()).status,401);assert.equal((await unauthorized.PUT(new Request("http://local",{method:"PUT",body:JSON.stringify(saved)}))).status,401);const authorized=createPriceMatchAdminHandlers({isAdmin:async()=>true,read:async()=>saved,save:async value=>(saved=value)});assert.equal((await authorized.GET()).status,200);const updated={enabled:false,heading:"A heading",description:"A description",buttonLabel:"Ask IDS"};const response=await authorized.PUT(new Request("http://local",{method:"PUT",body:JSON.stringify(updated)}));assert.equal(response.status,200);assert.deepEqual(saved,updated)});
test("Meet or Beat validation rejects blank, invalid, and oversized plain text",()=>{assert.equal(validatePriceMatch(null).ok,false);assert.equal(validatePriceMatch({...DEFAULT_PRICE_MATCH,enabled:"yes"}).ok,false);assert.equal(validatePriceMatch({...DEFAULT_PRICE_MATCH,heading:""}).ok,false);assert.equal(validatePriceMatch({...DEFAULT_PRICE_MATCH,heading:"x".repeat(251)}).ok,false);assert.equal(validatePriceMatch({...DEFAULT_PRICE_MATCH,description:"x".repeat(1501)}).ok,false);assert.equal(validatePriceMatch({...DEFAULT_PRICE_MATCH,buttonLabel:"x".repeat(61)}).ok,false)});
test("homepage price match renders fallback content and configured trigger while default contact triggers stay unchanged",()=>{const html=renderToStaticMarkup(<HomePriceMatch/>);assert.match(html,/We’ll Do Our Absolute Best/);assert.match(html,/Found a better price\?/);assert.match(html,/>Contact Us<\/button>/);assert.match(renderToStaticMarkup(<ContactInformationModal triggerLabel="Ask IDS"/>),/>Ask IDS<\/button>/);assert.match(renderToStaticMarkup(<ContactInformationModal/>),/>Contact Us<\/button>/)});
test("homepage can omit disabled settings and public reads have a production fallback",()=>{const component=readFileSync("components/promotions/HomePriceMatch.tsx","utf8");const server=readFileSync("lib/price-match/server.ts","utf8");assert.match(component,/if \(!settings\.enabled\) return null/);assert.match(server,/return \(await readPriceMatch\(\)\) \?\? DEFAULT_PRICE_MATCH/);assert.match(server,/catch \{ return DEFAULT_PRICE_MATCH; \}/)});
test("price match migration is a locked-down singleton seeded with current production copy",()=>{const sql=readFileSync("supabase/migrations/20260811034725_create_homepage_price_match_settings.sql","utf8");assert.match(sql,/id text PRIMARY KEY CHECK \(id = 'price-match'\)/);assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL.*anon, authenticated, service_role/);assert.match(sql,/GRANT SELECT, INSERT, UPDATE.*service_role/);assert.match(sql,/We’ll Do Our Absolute Best To Meet or Beat Any Verified Competitor Price/);assert.match(sql,/Found a better price\?/);assert.match(sql,/'Contact Us'/)});
