import "server-only";
import {getSupabaseServiceClient} from "@/lib/supabase";
import {DEFAULT_PRICING,locationRefusalLaborRefund,travelQuote,type PricingSnapshot} from "./policy";

const db=()=>getSupabaseServiceClient();
async function audit(id:string,eventType:string,details:Record<string,unknown>){await db().from("installation_audit_events").insert({installation_id:id,event_type:eventType,actor:"admin",details})}
export async function saveInstallationTravel(id:string,body:Record<string,unknown>){const c=db(),{data:i,error}=await c.from("installations").select("draft_pricing,pricing_snapshot").eq("id",id).single();if(error)throw error;const pricing=(i.pricing_snapshot??i.draft_pricing??DEFAULT_PRICING) as PricingSnapshot;const oneWayMinutes=Number(body.oneWayMinutes),approved=body.approvedChargeCents===undefined?undefined:Number(body.approvedChargeCents);if(!Number.isSafeInteger(oneWayMinutes)||oneWayMinutes<0||approved!==undefined&&(!Number.isSafeInteger(approved)||approved<0))throw new Error("invalid_travel");const q=travelQuote(oneWayMinutes,pricing,approved);if(q.manuallyOverridden&&!String(body.reason??"").trim())throw new Error("travel_override_reason_required");await c.from("installations").update({estimated_one_way_drive_minutes:q.estimatedOneWayMinutes,included_one_way_drive_minutes:q.includedOneWayMinutes,excess_one_way_drive_minutes:q.excessOneWayMinutes,billable_travel_hours_per_direction:q.billableHoursPerDirection,total_billable_travel_hours:q.totalBillableHours,calculated_travel_charge_cents:q.calculatedChargeCents,approved_travel_charge_cents:q.approvedChargeCents,travel_manually_overridden:q.manuallyOverridden,travel_override_reason:q.manuallyOverridden?String(body.reason):null,updated_at:new Date().toISOString()}).eq("id",id);await audit(id,"travel",{...q,reason:body.reason??null})}
export async function startAuthorizedWork(id:string,body:Record<string,unknown>){const c=db(),{data:i,error}=await c.from("installations").select("status,payment_status,cash_status,special_cash_failure_reschedule").eq("id",id).single();if(error)throw error;if(i.special_cash_failure_reschedule||["cancelled","terminated"].includes(i.status))throw new Error("work_cannot_begin");if(!["paid"].includes(i.payment_status)&&i.cash_status!=="approved")throw new Error("required_payment_not_confirmed");await c.from("installation_work_sessions").insert({installation_id:id,technician:String(body.technician||"IDS technician"),started_at:new Date().toISOString(),notes:body.notes??null});await c.from("installations").update({status:"in_progress",updated_at:new Date().toISOString()}).eq("id",id);await audit(id,"session_start",{technician:body.technician||"IDS technician"})}
export async function correctWorkSession(id:string,body:Record<string,unknown>){const c=db(),sessionId=String(body.sessionId??""),minutes=Number(body.durationMinutes),reason=String(body.reason??"").trim();if(!sessionId||!Number.isSafeInteger(minutes)||minutes<0||!reason)throw new Error("invalid_time_correction");const{data:s,error}=await c.from("installation_work_sessions").select("*").eq("id",sessionId).eq("installation_id",id).single();if(error||s.status==="running")throw error??new Error("running_session_cannot_be_corrected");await c.from("installation_work_sessions").insert({installation_id:id,technician:s.technician,started_at:s.started_at,ended_at:s.ended_at,duration_minutes:minutes,status:"corrected",notes:reason,corrected_from_id:s.id});await c.from("installation_work_sessions").update({duration_minutes:0,status:"corrected",notes:`Superseded: ${reason}`}).eq("id",s.id);await audit(id,"session_correct",{sessionId,previousMinutes:s.duration_minutes,newMinutes:minutes,reason})}
export async function recordPlacementRefusal(id:string,body:Record<string,unknown>){const c=db(),{data:i,error}=await c.from("installations").select("pricing_snapshot").eq("id",id).single();if(error||!i.pricing_snapshot)throw error??new Error("missing_pricing_snapshot");const{data:s,error:sessionError}=await c.from("installation_work_sessions").select("duration_minutes").eq("installation_id",id);if(sessionError)throw sessionError;const minutes=(s??[]).reduce((sum,row)=>sum+(row.duration_minutes??0),0),refund=locationRefusalLaborRefund((i.pricing_snapshot as PricingSnapshot).laborCents,minutes);if(refund>0)await c.from("installation_adjustments").insert({installation_id:id,kind:"credit",description:"Labor refund: customer refused technically acceptable placement",amount_cents:-refund,created_by:"admin"});await c.from("installations").update({status:"terminated",updated_at:new Date().toISOString()}).eq("id",id);await audit(id,"placement_refusal",{cumulativeMinutes:minutes,laborRefundCents:refund,materialsReconciliationRequired:true,notes:body.notes??null})}
