export const BUSINESS_TIME_ZONE = "America/Chicago";
export type PricingSnapshot = {laborCents:number;materialsAllowanceCents:number;depositCents:number;includedLaborMinutes:number;additionalLaborHourlyCents:number;laborIncrementMinutes:number;undergroundPerSegmentCents:number;undergroundSegmentFeet:number;includedOneWayTravelMinutes:number;travelHourlyCents:number};
export const DEFAULT_PRICING:PricingSnapshot={laborCents:80000,materialsAllowanceCents:20000,depositCents:25000,includedLaborMinutes:240,additionalLaborHourlyCents:12500,laborIncrementMinutes:15,undergroundPerSegmentCents:5000,undergroundSegmentFeet:10,includedOneWayTravelMinutes:120,travelHourlyCents:3500};
export const initialAmount=(p:PricingSnapshot)=>p.laborCents+p.materialsAllowanceCents;
export const undergroundLabor=(feet:number,p:PricingSnapshot)=>feet<=0?0:Math.ceil(feet/p.undergroundSegmentFeet)*p.undergroundPerSegmentCents;
export const additionalLabor=(minutes:number,p:PricingSnapshot)=>Math.ceil(Math.max(0,minutes-p.includedLaborMinutes)/p.laborIncrementMinutes)*(p.additionalLaborHourlyCents*p.laborIncrementMinutes/60);
export const travelQuote=(oneWayMinutes:number,p:PricingSnapshot,approvedChargeCents?:number)=>{const excess=Math.max(0,oneWayMinutes-p.includedOneWayTravelMinutes),perDirection=Math.ceil(excess/60),hours=perDirection*2,calculated=hours*p.travelHourlyCents;return{estimatedOneWayMinutes:oneWayMinutes,includedOneWayMinutes:p.includedOneWayTravelMinutes,excessOneWayMinutes:excess,billableHoursPerDirection:perDirection,totalBillableHours:hours,calculatedChargeCents:calculated,approvedChargeCents:approvedChargeCents??calculated,manuallyOverridden:approvedChargeCents!==undefined&&approvedChargeCents!==calculated}};
export const balanceDueAt=(appointment:string)=>new Date(new Date(appointment).getTime()-72*60*60*1000);
export const approvalPaymentPurpose=(appointment:string,now=new Date())=>new Date(appointment).getTime()-now.getTime()<=72*60*60*1000?"initial":"deposit" as const;
export const cancellationDepositRefund=(depositCents:number,appointment:string,now=new Date())=>{const h=(new Date(appointment).getTime()-now.getTime())/3600000;return h>48?depositCents:h>=24?Math.round(depositCents/2):0};
export const locationRefusalLaborRefund=(laborCents:number,cumulativeMinutes:number)=>cumulativeMinutes<=60?Math.round(laborCents*.5):cumulativeMinutes<=120?Math.round(laborCents*.25):0;
export const cashFailureState=(depositCents:number)=>({cashStatus:"revoked" as const,rescheduleOpportunityUsed:true,requiresPrepayment:true,depositForfeitCents:depositCents});
export const mayRescheduleCashFailure=(alreadyUsed:boolean,newAppointment:string,now=new Date())=>!alreadyUsed&&new Date(newAppointment).getTime()-now.getTime()>72*3600000;
export const safetyTerminationLaborRefund=()=>0;
export const authoritativeTotal=(p:PricingSnapshot,adjustments:number[])=>initialAmount(p)+adjustments.reduce((a,b)=>a+b,0);
export const remainingBalance=(total:number,payments:number[],refunds:number[]=[])=>Math.max(0,total-payments.reduce((a,b)=>a+b,0)+refunds.reduce((a,b)=>a+b,0));
