import "server-only";
import type Stripe from "stripe";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { getStripeServerClient } from "@/lib/stripe/server";
import { getStripeConfiguration } from "@/lib/stripe/config";
import { authoritativeTotal, remainingBalance, type PricingSnapshot } from "./policy";

export async function createInstallationCheckout(token: string, purpose: "deposit" | "balance") {
 const db=getSupabaseServiceClient(),{data:i,error}=await db.from("installations").select("*").eq("public_token",token).single();if(error||!i.pricing_snapshot)throw error??new Error("not_approved");
 const p=i.pricing_snapshot as PricingSnapshot,[{data:a},{data:paid}]=await Promise.all([db.from("installation_adjustments").select("amount_cents").eq("installation_id",i.id),db.from("installation_payments").select("amount_cents,refunded_cents").eq("installation_id",i.id).eq("status","paid")]);
 const total=authoritativeTotal(p,(a??[]).map(x=>x.amount_cents)),remaining=remainingBalance(total,(paid??[]).map(x=>x.amount_cents),(paid??[]).map(x=>x.refunded_cents)),amount=purpose==="deposit"?Math.min(i.deposit_due_cents??p.depositCents,remaining):remaining;if(amount<=0)throw new Error("nothing_due");if(purpose==="balance"&&i.cash_status==="approved")throw new Error("cash_approved");
 const key=`installation:${i.id}:${purpose}:${amount}`,{data:existing}=await db.from("installation_payments").select("stripe_session_id").eq("idempotency_key",key).maybeSingle();if(existing?.stripe_session_id){const old=await getStripeServerClient().checkout.sessions.retrieve(existing.stripe_session_id);if(old.url&&old.status==="open")return old.url}
 const config=getStripeConfiguration(),metadata={ids_kind:"professional_installation",installation_id:i.id,purpose},session=await getStripeServerClient().checkout.sessions.create({mode:"payment",payment_method_types:["card"],customer_email:i.customer_email,line_items:[{quantity:1,price_data:{currency:"usd",unit_amount:amount,product_data:{name:purpose==="deposit"?"Professional Installation booking deposit":"Professional Installation balance",description:purpose==="deposit"?"Applied toward the installation total; not an additional fee.":undefined}}}],metadata,payment_intent_data:{metadata},success_url:`${config.appBaseUrl}/professional-installation/${token}?payment=success`,cancel_url:`${config.appBaseUrl}/professional-installation/${token}?payment=cancelled`},{idempotencyKey:key});
 await db.from("installation_payments").upsert({installation_id:i.id,purpose,method:"stripe",status:"pending",amount_cents:amount,stripe_session_id:session.id,idempotency_key:key},{onConflict:"idempotency_key"});return session.url!;
}
export async function applyInstallationStripeSession(session:Stripe.Checkout.Session){if(session.metadata?.ids_kind!=="professional_installation")return false;const db=getSupabaseServiceClient(),id=session.metadata.installation_id;if(!id)throw new Error("missing installation id");if(session.status==="complete"&&session.payment_status==="paid"){const{data:p,error}=await db.from("installation_payments").update({status:"paid",stripe_payment_intent_id:typeof session.payment_intent==="string"?session.payment_intent:null,paid_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("stripe_session_id",session.id).select("purpose").single();if(error)throw error;await db.from("installations").update({payment_status:p.purpose==="deposit"?"deposit_paid":"paid",status:p.purpose==="deposit"?"scheduled":"ready",updated_at:new Date().toISOString()}).eq("id",id)}else if(session.status==="expired")await db.from("installation_payments").update({status:"cancelled",updated_at:new Date().toISOString()}).eq("stripe_session_id",session.id);return true}
export async function applyInstallationRefund(paymentIntentId:string,refundedCents:number){const db=getSupabaseServiceClient(),{data:p,error}=await db.from("installation_payments").select("id,installation_id,amount_cents").eq("stripe_payment_intent_id",paymentIntentId).maybeSingle();if(error)throw error;if(!p)return false;const status=refundedCents>=p.amount_cents?"refunded":"partially_refunded";await db.from("installation_payments").update({status,refunded_cents:Math.min(refundedCents,p.amount_cents),updated_at:new Date().toISOString()}).eq("id",p.id);await db.from("installations").update({payment_status:status,updated_at:new Date().toISOString()}).eq("id",p.installation_id);await db.from("installation_audit_events").insert({installation_id:p.installation_id,event_type:"stripe_refund",actor:"stripe",details:{paymentIntentId,refundedCents}});return true}
