"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import type { CustomerPaymentMethod, PaymentMethodSettings } from "@/lib/payment-method-settings/types";

const methods: { key:CustomerPaymentMethod; title:string; description:string }[] = [
  { key:"card", title:"Credit / Debit Card", description:"Controls whether direct card payment is offered during customer checkout." },
  { key:"ach_debit", title:"ACH Bank Payment", description:"Controls whether ACH Bank Payment is offered during customer checkout. Disabling ACH hides it from customers and prevents new ACH Checkout Sessions from being created." },
  { key:"hearth_financing", title:"Hearth Financing", description:"Controls whether the Hearth financing option is shown to customers." },
];

export default function PaymentMethodsAdminPage() {
  const [authed,setAuthed]=useState<boolean|null>(null);
  const [password,setPassword]=useState("");
  const [settings,setSettings]=useState<PaymentMethodSettings|null>(null);
  const [saving,setSaving]=useState<CustomerPaymentMethod|null>(null);
  const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/payment-methods",{cache:"no-store"});if(response.status===401){setAuthed(false);return;}const body=await response.json();if(response.ok){setSettings(body.settings);setAuthed(true);}else setMessage(body.error??"Payment method settings are unavailable.");},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function login(event:FormEvent){event.preventDefault();const response=await fetch("/api/admin/reviews/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(response.ok){setPassword("");setMessage("");await load();}else setMessage("Invalid password.");}
  async function toggle(method:CustomerPaymentMethod){if(!settings||saving)return;const enabled=!settings[method];setSaving(method);setMessage("");const response=await fetch("/api/admin/payment-methods",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({paymentMethod:method,enabled})});const body=await response.json();if(response.ok){setSettings(current=>current?{...current,[method]:enabled}:current);setMessage(`${methods.find(item=>item.key===method)?.title} ${enabled?"enabled":"disabled"}.`);}else setMessage(body.error??"The setting could not be saved.");setSaving(null);}
  if(authed===null)return <main className="min-h-screen bg-slate-100 p-6">Loading admin…</main>;
  if(!authed)return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-6"><form onSubmit={login} className="w-full max-w-md rounded-[2rem] bg-white p-8 shadow-xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="mt-2 text-3xl font-black">Payment Methods</h1><p className="mt-3 text-slate-600">Use the existing IDS administrator password.</p><label className="mt-6 block font-bold">Admin password<input type="password" required value={password} onChange={event=>setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label><button className="mt-5 w-full rounded-xl bg-slate-950 px-5 py-3 font-black text-white">Sign In</button>{message&&<p role="alert" className="mt-4 text-red-700">{message}</p>}</form></main>;
  return <main className="min-h-screen bg-slate-100 p-5 text-slate-950 md:p-10"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="text-4xl font-black">Payment Methods</h1><p className="mt-3 max-w-2xl text-slate-600">Control which new customer payment and financing choices are available. Environment-level safety switches remain authoritative.</p></div><button onClick={async()=>{await fetch("/api/admin/reviews/login",{method:"DELETE"});setAuthed(false);}} className="rounded-xl border px-4 py-2 font-bold">Sign Out</button></div>{message&&<p role="status" className="mt-6 rounded-xl bg-white p-4 font-bold">{message}</p>}<div className="mt-7 grid gap-5">{settings&&methods.map(method=>{const enabled=settings[method.key];return <article key={method.key} className="flex flex-wrap items-center justify-between gap-5 rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="max-w-2xl"><div className="flex items-center gap-3"><h2 className="text-xl font-black">{method.title}</h2><span className={`rounded-full px-3 py-1 text-xs font-black uppercase ${enabled?"bg-emerald-100 text-emerald-800":"bg-slate-200 text-slate-700"}`}>{enabled?"Enabled":"Disabled"}</span></div><p className="mt-3 leading-7 text-slate-600">{method.description}</p></div><button type="button" disabled={saving!==null} onClick={()=>void toggle(method.key)} className={`rounded-xl px-5 py-3 font-black text-white disabled:opacity-50 ${enabled?"bg-red-700":"bg-emerald-600"}`}>{saving===method.key?"Saving…":enabled?"Disable":"Enable"}</button></article>;})}</div></div></main>;
}
