"use client";
import { type FormEvent, useEffect, useState } from "react";
import type { FeaturedBusiness, FeaturedBusinessInput } from "@/lib/featured-businesses/types";
import Image from "next/image";

const empty:FeaturedBusinessInput={businessName:"",description:"",operatingRegion:null,imageUrl:null,imagePath:null,imageAlt:null,websiteUrl:null,facebookUrl:null,phone:null,address:null,referralCode:null,specialOffer:null,isPublic:false,isFeatured:false,isArchived:false,sortOrder:100};
const inputClass="mt-2 w-full rounded-xl border border-slate-300 p-3";
export default function FeaturedBusinessesAdmin(){const[authed,setAuthed]=useState<boolean|null>(null),[password,setPassword]=useState(""),[items,setItems]=useState<FeaturedBusiness[]>([]),[editing,setEditing]=useState<FeaturedBusinessInput&{id?:string}>(empty),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 async function load(){const r=await fetch("/api/admin/featured-businesses");if(r.status===401){setAuthed(false);return;}const p=await r.json().catch(()=>({}));setAuthed(true);if(r.ok)setItems(p.businesses);else setMessage(p.error??"Businesses could not be loaded.");}
 useEffect(()=>{fetch("/api/admin/featured-businesses").then(async r=>{if(r.status===401){setAuthed(false);return;}const p=await r.json().catch(()=>({}));setAuthed(true);if(r.ok)setItems(p.businesses);else setMessage(p.error??"Businesses could not be loaded.");});},[]);
 async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/reviews/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});if(r.ok){setPassword("");await load();}else setMessage("Invalid password.");}
 const update=<K extends keyof FeaturedBusinessInput>(key:K,value:FeaturedBusinessInput[K])=>setEditing(v=>({...v,[key]:value}));
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");const r=await fetch(editing.id?`/api/admin/featured-businesses/${editing.id}`:"/api/admin/featured-businesses",{method:editing.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing)});const p=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setMessage(p.error??Object.values(p.errors??{}).join(" ")??"Save failed.");setEditing({...p.business});setMessage("Business saved.");await load();}
 async function upload(file:File){if(!editing.id)return setMessage("Save the business before uploading its image.");const form=new FormData();form.set("file",file);setSaving(true);const r=await fetch(`/api/admin/featured-businesses/${editing.id}/image`,{method:"POST",body:form});const p=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return setMessage(p.error??"Upload failed.");setEditing(v=>({...v,imageUrl:p.imageUrl,imagePath:p.imagePath}));setMessage("Image uploaded.");await load();}
 async function removeImage(){if(!editing.id||!editing.imageUrl)return;setSaving(true);const r=await fetch(`/api/admin/featured-businesses/${editing.id}/image`,{method:"DELETE"});setSaving(false);if(!r.ok)return setMessage("Image could not be removed.");setEditing(v=>({...v,imageUrl:null,imagePath:null}));setMessage("Image removed.");await load();}
 async function remove(){if(!editing.id||!confirm("Delete this saved business and its image?"))return;const r=await fetch(`/api/admin/featured-businesses/${editing.id}`,{method:"DELETE"});if(r.ok){setEditing(empty);setMessage("Business deleted.");await load();}else setMessage("Business could not be deleted.");}
 if(authed===null)return <main className="min-h-screen bg-slate-100 p-6">Loading admin…</main>;
 if(!authed)return <main className="min-h-screen bg-slate-100 p-6 md:p-10"><form onSubmit={login} className="mx-auto max-w-md rounded-[2rem] bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="mt-2 text-4xl font-black">Featured Businesses</h1><label className="mt-7 block font-bold">Admin password<input className={inputClass} type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Sign In</button>{message&&<p role="alert" className="mt-4 font-bold text-red-700">{message}</p>}</form></main>;
 return <main className="min-h-screen bg-slate-100 p-5 text-slate-950 md:p-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="text-4xl font-black">Featured Businesses</h1></div><div className="flex gap-2"><button type="button" onClick={()=>setEditing(empty)} className="rounded-xl bg-emerald-600 px-4 py-3 font-black text-white">Add Business</button><button type="button" onClick={async()=>{await fetch("/api/admin/reviews/login",{method:"DELETE"});setAuthed(false);}} className="rounded-xl border px-4 py-3 font-bold">Sign Out</button></div></div>
 <div className="mt-8 grid gap-7 lg:grid-cols-[minmax(260px,.7fr)_1.3fr]"><aside aria-label="Saved businesses" className="space-y-3">{items.map(item=><button type="button" key={item.id} onClick={()=>setEditing(item)} className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm"><span className="block break-words font-black">{item.businessName}</span><span className="mt-2 flex flex-wrap gap-2 text-xs font-bold">{item.isFeatured&&<span className="rounded bg-emerald-100 px-2 py-1 text-emerald-900">FEATURED ON HOMEPAGE</span>}<span className="rounded bg-slate-100 px-2 py-1">{item.isArchived?"ARCHIVED":item.isPublic?"PUBLIC":"HIDDEN"}</span></span></button>)}</aside>
 <form onSubmit={save} className="space-y-5 rounded-[2rem] bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-black">{editing.id?`Edit ${editing.businessName}`:"Add Business"}</h2><label className="block font-bold">Business Name *<input required maxLength={160} className={inputClass} value={editing.businessName} onChange={e=>update("businessName",e.target.value)}/></label><label className="block font-bold">Services Description *<textarea required maxLength={3000} rows={5} className={inputClass} value={editing.description} onChange={e=>update("description",e.target.value)}/></label>
 <div className="grid gap-5 sm:grid-cols-2"><label className="block font-bold">Operating Region<input maxLength={200} className={inputClass} value={editing.operatingRegion??""} onChange={e=>update("operatingRegion",e.target.value||null)}/></label><label className="block font-bold">Phone Number<input maxLength={80} className={inputClass} value={editing.phone??""} onChange={e=>update("phone",e.target.value||null)}/></label><label className="block font-bold">Website URL<input type="url" className={inputClass} value={editing.websiteUrl??""} onChange={e=>update("websiteUrl",e.target.value||null)}/></label><label className="block font-bold">Facebook URL<input type="url" className={inputClass} value={editing.facebookUrl??""} onChange={e=>update("facebookUrl",e.target.value||null)}/></label><label className="block font-bold sm:col-span-2">Address<textarea rows={2} maxLength={500} className={inputClass} value={editing.address??""} onChange={e=>update("address",e.target.value||null)}/></label><label className="block font-bold">IDS Referral Code<input maxLength={100} className={inputClass} value={editing.referralCode??""} onChange={e=>update("referralCode",e.target.value||null)}/></label><label className="block font-bold">Display Order<input type="number" min={0} max={100000} className={inputClass} value={editing.sortOrder} onChange={e=>update("sortOrder",Number(e.target.value))}/></label><label className="block font-bold sm:col-span-2">Special Offer / Discount<textarea rows={3} maxLength={1000} className={inputClass} value={editing.specialOffer??""} onChange={e=>update("specialOffer",e.target.value||null)}/></label></div>
 <fieldset className="rounded-xl border p-4"><legend className="px-2 font-black">Visibility</legend><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={editing.isPublic} onChange={e=>update("isPublic",e.target.checked)} />Public</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={editing.isArchived} onChange={e=>{update("isArchived",e.target.checked);if(e.target.checked)update("isFeatured",false);}} />Archived</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" disabled={!editing.isPublic||editing.isArchived} checked={editing.isFeatured} onChange={e=>update("isFeatured",e.target.checked)} />Featured</label></div><p className="mt-2 text-sm text-slate-500">Featuring this business automatically removes the previous homepage feature. Hidden or archived businesses cannot be featured.</p></fieldset>
 {editing.id&&<section><p className="font-black">Image / Logo</p>{editing.imageUrl&&<Image src={editing.imageUrl} alt={editing.imageAlt||`${editing.businessName} preview`} width={800} height={500} unoptimized className="mt-3 max-h-56 max-w-full rounded-xl border object-contain"/>}<label className="mt-3 block font-bold">Image alt text<input maxLength={240} className={inputClass} value={editing.imageAlt??""} onChange={e=>update("imageAlt",e.target.value||null)}/></label><div className="mt-3 flex flex-wrap gap-3"><label className="inline-flex cursor-pointer rounded-xl border px-4 py-3 font-bold">Upload / Replace Image<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value="";}}/></label>{editing.imageUrl&&<button type="button" onClick={()=>void removeImage()} className="rounded-xl border border-red-300 px-4 py-3 font-bold text-red-700">Remove Image</button>}</div></section>}
 <div className="flex flex-wrap gap-3"><button disabled={saving} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white disabled:opacity-60">{saving?"Saving…":"Save Business"}</button>{editing.id&&<button type="button" onClick={()=>void remove()} className="rounded-xl bg-red-700 px-5 py-3 font-black text-white">Delete Business</button>}</div>{message&&<p role="status" className="font-bold text-slate-700">{message}</p>}</form></div></div></main>}
