"use client";
import Link from "next/link";
import type { MachineOptionalServices } from "@/lib/checkout/types";
import type { MachineServiceAvailability } from "@/lib/checkout/optional-services";
import { SupportTerms } from "@/components/service/ServiceTerms";

const allAvailable: MachineServiceAvailability = { install: { available: true, message: "" }, setup: { available: true, message: "" }, remoteSupport: { available: true, message: "" } };

export default function OptionalServices({ value, onChange, availability = allAvailable, supportAvailable, eligibleCheckout }: { value: MachineOptionalServices; onChange: (value: MachineOptionalServices) => void; availability?: MachineServiceAvailability; supportAvailable?: boolean; eligibleCheckout: boolean }) {
  const current = supportAvailable === undefined ? availability : { ...availability, remoteSupport: { ...availability.remoteSupport, available: supportAvailable } };
  return <section className="space-y-5"><h3 className="text-3xl font-black">Optional Services</h3><p className="leading-7 text-slate-600">Choose the services you are interested in with your machine. Install and Setup add $0 at checkout; their separate pricing, deposit, approval and scheduling policies still apply. They are not free services.</p><div className="grid gap-4 lg:grid-cols-3">{([["install", "Install", "$0 at checkout"], ["setup", "Setup", "$0 at checkout"], ["remoteSupport", "Remote Support", "$100 at checkout, then $100/month"]] as const).map(([name, label, price]) => { const enabled = current[name].available && (name !== "remoteSupport" || eligibleCheckout); return <label key={name} className={`flex items-start gap-3 rounded-2xl border p-5 ${enabled ? "border-slate-300 bg-white" : "border-amber-300 bg-amber-50"}`}><input type="checkbox" className="mt-1 size-5 shrink-0" checked={value[name]} disabled={!enabled} onChange={e => onChange({ ...value, [name]: e.target.checked, ...(name === "remoteSupport" ? { acceptedSupportTerms: false } : {}) })} /><span><strong className="block text-xl">{label}</strong><span className="mt-2 block text-sm font-semibold">{price}</span>{!current[name].available && <span className="mt-3 block text-sm font-black text-amber-950">CURRENTLY UNAVAILABLE{current[name].message ? `: ${current[name].message}` : ""}</span>}{name === "remoteSupport" && current[name].available && !eligibleCheckout && <span className="mt-3 block text-sm text-amber-950">Available only with card or ACH machine checkout. For a financed or quoted purchase, subscribe separately.</span>}</span></label>; })}</div><Link href="/professional-installation" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center font-bold text-emerald-900 underline">Separate Installation and Setup terms</Link>{value.remoteSupport && <div className="space-y-5 rounded-2xl border border-emerald-300 bg-emerald-50 p-5"><SupportTerms /><label className="flex items-start gap-3 font-semibold"><input type="checkbox" className="mt-1 size-5 shrink-0" checked={value.acceptedSupportTerms} onChange={e => onChange({ ...value, acceptedSupportTerms: e.target.checked })} />I authorize the $100 Remote Support charge with this machine purchase and $100 monthly renewals after the first paid support month, using my saved payment method, until cancelled.</label></div>}</section>;
}
