/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
"use client";
import {useEffect,useState,type FormEvent} from "react";
import {formatInstallationTime} from "@/lib/installations/cash-validation";
import {activeWorkSessions,cumulativeWorkMinutes,workSessionMinutes,displayWorkMinutes} from "@/lib/installations/admin-policy";
import {loadInstallationAvailability} from "@/lib/installations/availability-client";
import SetupOnlyJobForm from "@/components/installations/SetupOnlyJobForm";
import InstallationServiceSummary from "@/components/installations/InstallationServiceSummary";
import {hasInstallation,hasSetup,serviceName} from "@/lib/installations/setup";
import {DEFAULT_PRICING} from "@/lib/installations/policy";
import InstallationBalanceSummary,{installationMoney as money} from "@/components/installations/InstallationBalanceSummary";
import InstallationAdminAction from "@/components/installations/InstallationAdminAction";
import RecordCashPayment from "@/components/installations/RecordCashPayment";
import CorrectCashReceipt from "@/components/installations/CorrectCashReceipt";
import RecordCashRefund from "@/components/installations/RecordCashRefund";
const priceLabels:Record<string,string>={setupLaborCents:"Setup labor (up to four separate hours)",laborCents:"Labor",materialsAllowanceCents:"Materials allowance",depositCents:"Deposit credited toward total",additionalLaborHourlyCents:"Extra labor per hour",undergroundPerSegmentCents:"Underground per started 10 feet",travelHourlyCents:"Separate-visit excess travel per started hour per direction"};
const options=(values:string[])=>values.map(value=>({value,label:value.replaceAll("_"," ")}));
function pricingFields(p:any,installationSelected=true){return Object.entries(priceLabels).filter(([key])=>installationSelected||["setupLaborCents","depositCents","travelHourlyCents"].includes(key)).map(([key,label])=>({name:`pricing.${key}`,label:`${label} ($)`,kind:"money" as const,value:((p[key]??DEFAULT_PRICING[key as keyof typeof DEFAULT_PRICING]??0)/100).toFixed(2)}));}
export default function Page(){
  const[authed,setAuthed]=useState<boolean|null>(null),[data,setData]=useState<any>(null),[message,setMessage]=useState(""),[refreshFailed,setRefreshFailed]=useState(false),[slots,setSlots]=useState<{value:string;label:string}[]>([]);
  async function load(){try{const r=await fetch("/api/admin/installations",{cache:"no-store"});setAuthed(r.status!==401);if(!r.ok){setRefreshFailed(true);setMessage((await r.json()).error||"Installation records could not be loaded.");return;}setData(await r.json());setRefreshFailed(false);const controller=new AbortController();try{setSlots((await loadInstallationAvailability(controller.signal)).map(s=>({value:s.startAt,label:formatInstallationTime(s.startAt)})));}catch{setSlots([]);}}catch{setAuthed(true);setRefreshFailed(true);setMessage("Installation records could not be loaded. Please retry.");}}
  useEffect(()=>{void load();},[]);
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const r=await fetch("/api/admin/reviews/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:new FormData(e.currentTarget).get("password")})});if(r.ok)await load();else setMessage("Invalid password.");}
  if(authed===null)return <main className="p-10">Loading installations…</main>;
  if(!authed)return <main className="mx-auto max-w-md p-10"><form onSubmit={login}><h1 className="text-2xl font-black">IDS Admin</h1><label className="mt-4 block">Administrator password<input name="password" type="password" required className="mt-1 w-full border p-3"/></label><button className="mt-3 min-h-11 rounded bg-slate-950 p-3 text-white">Sign in</button><p role="status">{message}</p></form></main>;
  return <main className="min-h-screen bg-slate-100 p-4 md:p-8"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-black">Professional Installations</h1><p className="mt-2">Review, approve, collect payment, track work, and reconcile.</p>{message&&<p role="status" className="mt-3 font-bold">{message}</p>}<button onClick={load} className="my-4 min-h-11 rounded border bg-white px-4">Refresh records and availability</button>
  {data&&<><details className="rounded-xl bg-white p-5"><summary className="font-bold">Defaults for future approvals and pricing history</summary><p className="my-3">Approved installations keep their saved pricing. Separate four-hour labor buckets and 15-minute overtime increments remain fixed. Combined visits include two one-way travel hours, then $35 per started excess hour total. Separate-visit travel retains the existing round-trip policy.</p><InstallationAdminAction action="defaults" title="Save future pricing defaults" fields={pricingFields(data.pricing)} base={{pricing:data.pricing}} onSaved={load} disabled={refreshFailed}/>{(data.pricingHistory??[]).map((h:any)=><p className="mt-2 text-sm" key={h.operation_key}>{formatInstallationTime(h.created_at)} — {h.actor}: {h.reason}</p>)}</details>
  <SetupOnlyJobForm slots={slots} onSaved={load} disabled={refreshFailed}/><div className="mt-6 space-y-6">{data.installations.map((i:any)=>{
    const sessions=data.sessions.filter((s:any)=>s.installation_id===i.id),payments=data.payments.filter((p:any)=>p.installation_id===i.id),adjustments=data.adjustments.filter((a:any)=>a.installation_id===i.id),corrections=(data.corrections??[]).filter((c:any)=>c.installation_id===i.id),refunds=(data.cashRefunds??[]).filter((r:any)=>r.installation_id===i.id),balance=data.balances?.[i.id]??null;
    const running=sessions.some((s:any)=>s.status==="running"),closed=["cancelled","terminated","declined","completed"].includes(i.status),cashEnabled=!refreshFailed&&!!balance&&data.controls?.cashRecordingEnabled===true;
    const common={installationId:i.id,onSaved:load,disabled:refreshFailed},pricing=i.pricing_snapshot??i.draft_pricing??data.pricing??DEFAULT_PRICING;
    return <article key={i.id} className="min-w-0 rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{i.customer_name}</h2><p className="break-words">{i.customer_email} · {i.customer_phone}</p><p>{i.property_address}</p><p className="mt-2">{formatInstallationTime(i.requested_start_at)}</p><a href={`/professional-installation/${i.public_token}`} className="text-emerald-800 underline">View customer record</a></div><div><p className="font-bold">{serviceName(i)}</p><p className="font-bold">Job: {i.status.replaceAll("_"," ")}</p><p>Safety: {i.safety_status.replaceAll("_"," ")}</p><p>Cash arrangement: {i.cash_status}</p><p>Work: {displayWorkMinutes(cumulativeWorkMinutes(sessions))} cumulative minutes{running?" plus current running session":""}</p></div></div>
      <p className="mt-4 text-sm">Connectivity: {i.internet_availability}. {hasInstallation(i)?"Grounding, responsibilities and terms":"Responsibilities and Setup terms"}: {(!hasInstallation(i)||i.grounding_acknowledged_at)&&i.responsibilities_acknowledged_at&&i.terms_acknowledged_at?"acknowledged":"review required"}. Underground: {i.underground_requested?`${i.estimated_underground_feet} estimated feet; utility marking acknowledged`:"not requested"}.</p>
      <p className="mt-2 text-sm">Travel: {i.estimated_one_way_drive_minutes??"not entered"} minutes each way; calculated {money(i.calculated_travel_charge_cents)}, approved {money(i.approved_travel_charge_cents)}. {i.travel_override_reason}</p>
      {i.balance_due_at&&<p className="mt-2 text-sm">Normal balance deadline: before {formatInstallationTime(i.balance_due_at)}. {i.payment_arrangement_reason&&`Approved arrangement: ${i.payment_arrangement_reason}`}</p>}
      {i.special_cash_failure_reschedule&&<p className="mt-2 font-bold">Cash unavailable on arrival. Reschedule opportunity: {i.reschedule_opportunity_used?"used; normal payment deadline applies":"one available"}. Deposit forfeited: {money(i.deposit_forfeited_cents??0)}.</p>}
      <InstallationServiceSummary job={i} sessions={sessions} adjustments={adjustments}/><div className="mt-5">{balance?<InstallationBalanceSummary balance={balance} settlementRequired={["cancelled","terminated","declined"].includes(i.status)}/>:<p role="status">{i.pricing_snapshot?"Current balance unavailable. Existing entry confirmation remains available.":"Pricing has not been approved."}</p>}</div>
      <details className="mt-5 rounded-xl border p-4" open={i.status==="requested"}><summary className="font-bold">Review, pricing, travel, and cash approval</summary><div className="mt-4 grid gap-4 lg:grid-cols-3">
        {i.status==="requested"&&<InstallationAdminAction {...common} action="approve" title="Approve job and saved pricing" reasonRequired={i.internet_availability!=="yes"}/>}
        {!closed&&hasInstallation(i)&&<InstallationAdminAction {...common} action="setup" title={hasSetup(i)?"Remove Setup; retain deposit and history":"Add Setup and approve combined travel from saved drive time"} base={{selected:!hasSetup(i)}}/>}<InstallationAdminAction {...common} action="pricing" title="Approve pricing for this job" fields={pricingFields(pricing,hasInstallation(i))} base={{pricing}}/>
        <InstallationAdminAction {...common} action="travel" title="Approve travel" fields={[{name:"oneWayMinutes",label:"Drive minutes each way",kind:"number",value:i.estimated_one_way_drive_minutes??120},{name:"approvedChargeCents",label:"Override total travel before subscriber discount ($, optional)",kind:"money",optional:true}]}/>
        {!closed&&<InstallationAdminAction {...common} action="cash" title="Save cash arrangement" fields={[{name:"status",label:"Decision",kind:"select",options:options(["approved","denied","revoked"])}]}/>}
        {!closed&&!i.special_cash_failure_reschedule&&<InstallationAdminAction {...common} action="arrangement" title="Record IDS payment arrangement"/>}
        {i.status==="requested"&&<InstallationAdminAction {...common} action="decline" title="Decline request"/>}
      </div></details>
      <RecordCashPayment installationId={i.id} balance={balance} enabled={cashEnabled} settlementRequired={["cancelled","terminated","declined"].includes(i.status)} onRecorded={load}/>
      <details className="mt-5 rounded-xl border p-4"><summary className="font-bold">Work, safety, rescheduling, and settlement</summary><div className="mt-4 grid gap-4 lg:grid-cols-3">
        {!closed&&(!running?<InstallationAdminAction {...common} action="session_start" title="Begin / resume selected service labor" reasonRequired={false} fields={[{name:"serviceType",label:"Labor bucket",kind:"select",options:[...(hasInstallation(i)?[{value:"installation",label:"Installation labor"}]:[]),...(hasSetup(i)?[{value:"setup",label:"Setup labor"}]:[])]}]}/>:<InstallationAdminAction {...common} action="session_stop" title="Stop current work session" reasonRequired={false} fields={[{name:"status",label:"Work state",kind:"select",options:options(["paused","suspended","completed"])}]}/>)}
        {!closed&&<InstallationAdminAction {...common} action="safety" title="Record safety or weather decision" fields={[{name:"status",label:"Safety decision",kind:"select",options:options(["suspended","remediation_pending","remediation_approved","weather_postponed","terminated","clear"])},{name:"evidence",label:"Remediation evidence / documentation",optional:true}]}/>}
        {!closed&&<InstallationAdminAction {...common} action="reschedule" title="Reschedule appointment" fields={[{name:"startAt",label:"Available four-hour appointment",kind:"select",options:slots}]}/>}
        {!closed&&i.cash_status==="approved"&&<InstallationAdminAction {...common} action="cash_failure" title="Record cash unavailable on arrival"/>}
        {i.special_cash_failure_reschedule&&!i.reschedule_opportunity_used&&<InstallationAdminAction {...common} action="cash_reschedule" title="Use one cash-failure reschedule" fields={[{name:"startAt",label:"Available appointment more than 72 hours away",kind:"select",options:slots}]}/>}
        {i.special_cash_failure_reschedule&&i.reschedule_opportunity_used&&<InstallationAdminAction {...common} action="forfeit_deposit" title="Record deposit forfeiture after missed deadline"/>}
        {i.pricing_snapshot&&<>{hasInstallation(i)&&<InstallationAdminAction {...common} action="materials" title="Reconcile actual eligible materials" fields={[{name:"actualCents",label:"Total actual materials used ($, including grounding and underground)",kind:"money"}]}/>}
        {(hasSetup(i)||adjustments.some((a:any)=>a.reconciliation_kind?.startsWith("setup_")))&&<InstallationAdminAction {...common} action="setup_materials" title="Reconcile actual Setup parts/materials" fields={[{name:"actualCents",label:"Customer-authorized actual eligible Setup parts/materials ($; no allowance)",kind:"money"}]}/>}
        <InstallationAdminAction {...common} action="labor" title="Reconcile cumulative additional labor" reasonRequired={false}/>
        {hasInstallation(i)&&<InstallationAdminAction {...common} action="underground" title="Reconcile underground labor" fields={[{name:"feet",label:"Total feet completed",kind:"number"}]}/>}
        <InstallationAdminAction {...common} action="adjustment" title="Record approved charge or credit" fields={[{name:"kind",label:"Kind",kind:"select",options:options(["material","credit","other"])},{name:"description",label:"Description"},{name:"amountCents",label:"Amount ($; negative for credit)",kind:"money"}]}/>
        {!closed&&hasInstallation(i)&&<InstallationAdminAction {...common} action="placement_refusal" title="Record placement refusal and labor credit"/>}</>}
        {!closed&&<InstallationAdminAction {...common} action="cancel" title="Record customer cancellation"/>}
      </div><p className="mt-3 text-sm">These decisions record work and settlement. Actual money returned is recorded separately. No return-trip fee is added.</p></details>
      <details className="mt-5 rounded-xl border p-4"><summary className="font-bold">Payment, cash corrections, cash returns, and work history</summary><div className="mt-3 space-y-3 break-words text-sm">
        {payments.map((p:any)=><div key={p.id} className="rounded border p-3"><p className="font-bold">{p.method} / {p.purpose}: {p.status} {money(p.amount_cents)}</p><p>Receipt {p.id}. Processor / legacy completed refunds: {money(p.refunded_cents)}.</p><p>{p.paid_at?`Received ${formatInstallationTime(p.paid_at)}. `:""}Recorded {formatInstallationTime(p.created_at)} by {p.recorded_by||(p.method==="stripe"?"Stripe":"legacy record; actor not stored")}.</p><p>{p.receipt_reference} {p.notes} {p.stripe_payment_intent_id}</p></div>)}
        {corrections.map((c:any)=><p key={c.id}>Recording correction {c.id}: {money(c.amount_cents)} against receipt {c.original_payment_id}. {c.reason}. Recorded {formatInstallationTime(c.created_at)} by {c.recorded_by}. No money return.</p>)}
        {refunds.map((r:any)=><p key={r.id}>Cash actually returned {r.id}: {money(r.amount_cents)} against receipt {r.original_payment_id}. Returned {formatInstallationTime(r.returned_at)}; recorded {formatInstallationTime(r.created_at)} by {r.recorded_by}. {r.reason} {r.reference}</p>)}
        {payments.filter((p:any)=>p.method==="cash"&&p.purpose!=="refund"&&["paid","partially_refunded","refunded"].includes(p.status)).map((p:any)=>{
          const eligible=p.amount_cents-p.refunded_cents-corrections.filter((c:any)=>c.original_payment_id===p.id).reduce((n:number,c:any)=>n+c.amount_cents,0)-refunds.filter((r:any)=>r.original_payment_id===p.id).reduce((n:number,r:any)=>n+r.amount_cents,0);
          return <div key={p.id} className="grid gap-3 lg:grid-cols-2"><CorrectCashReceipt installationId={i.id} paymentId={p.id} eligibleCents={eligible} enabled={cashEnabled} onRecorded={load}/><RecordCashRefund installationId={i.id} paymentId={p.id} eligibleCents={eligible} enabled={cashEnabled} onRecorded={load}/></div>;
        })}
        {adjustments.map((a:any)=><p key={a.id}>{a.kind}: {money(a.amount_cents)} — {a.description}. {a.created_by}</p>)}
        {sessions.map((s:any)=><div key={s.id}><p>{s.service_type??"installation"} work session {s.id}: {formatInstallationTime(s.started_at)} — {s.status} — {s.status==="running"?"running":displayWorkMinutes(workSessionMinutes(s))} minutes. {s.corrected_from_id&&`Corrects ${s.corrected_from_id}.`} {!activeWorkSessions(sessions).some(w=>w.id===s.id)&&"Superseded; excluded from cumulative time."} {s.notes}</p>{s.status!=="running"&&activeWorkSessions(sessions).some(w=>w.id===s.id)&&<InstallationAdminAction {...common} action="session_correct" scope={s.id} title="Correct this work session" base={{sessionId:s.id}} fields={[{name:"durationMinutes",label:"Correct total minutes for this session",kind:"number",value:s.duration_minutes}]}/>}</div>)}
      </div></details>
      <details className="mt-5 rounded-xl border p-4"><summary className="font-bold">Stripe test refunds and reconciliation</summary><p className="my-3 text-sm">Refunds require an IDS decision. A request may remain pending. Only confirmed successful refunds reduce net payments; allow 7–12 business days for the customer to see a refund.</p><div className="grid gap-4 lg:grid-cols-2">
        <InstallationAdminAction {...common} action="stripe_refund" title="Request Stripe TEST refund" endpoint={`/api/admin/installations/${i.id}/stripe/refunds`} fields={[{name:"originalPaymentId",label:"Original Stripe payment",kind:"select",options:payments.filter((p:any)=>p.method==="stripe"&&p.purpose!=="refund"&&["paid","partially_refunded"].includes(p.status)).map((p:any)=>({value:p.id,label:`${p.purpose}: ${money(p.amount_cents-p.refunded_cents)} remaining (${p.id})`}))},{name:"amountDollars",label:"Amount to refund ($)"},{name:"reference",label:"Reference",optional:true}]}/>
        <InstallationAdminAction {...common} action="stripe_reconcile" title="Refresh / recover Stripe evidence" reasonRequired={false} endpoint={`/api/admin/installations/${i.id}/stripe/reconcile`} fields={[{name:"paymentId",label:"Stripe payment",kind:"select",options:payments.filter((p:any)=>p.method==="stripe"&&p.purpose!=="refund").map((p:any)=>({value:p.id,label:`${p.purpose}: ${p.status} (${p.id})`}))},{name:"sessionId",label:"Known test Checkout Session reference (optional)",optional:true}]}/>
      </div></details>
      <details className="mt-3 rounded-xl border p-4"><summary className="font-bold">Approval and audit history</summary>{(data.audits??[]).filter((a:any)=>a.installation_id===i.id).map((a:any)=><details key={a.id} className="mt-2 text-sm"><summary>{formatInstallationTime(a.created_at)} — {a.event_type.replaceAll("_"," ")} — {a.actor}</summary><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(a.details,null,2)}</pre></details>)}</details>
    </article>;
  })}</div>{data.installations.length===0&&<p className="mt-6">No installation requests yet.</p>}</>}
  </div></main>;
}
