import { SETUP_DESCRIPTION } from "@/lib/installations/setup";

export default function SetupTerms() {
  return <details className="rounded-xl border p-4 text-sm leading-6">
    <summary className="cursor-pointer font-black">Professional Setup &amp; Optimization terms</summary>
    <p className="mt-3">{SETUP_DESCRIPTION} Work can include property mapping, mowing/work zones, no-go zones, pathways and transitions, mowing patterns, operating plans, schedules, frequency and automation, applicable track lubrication and real-blade conversion, operational testing, final adjustments, and a customer walkthrough.</p>
    <p className="mt-3">Tasks depend on the Lymow, Yarbo, or Pandag machine, property, and configuration. Setup includes up to four cumulative hours of Setup labor, separate from Installation labor. When the appropriate work is complete, the service is complete; unused time does not roll over, become credit, or cover future unrelated work. Additional Setup labor is $125/hour, billed at $31.25 per started 15 minutes after four hours. Pauses retain both labor totals; travel, waiting, and lodging do not consume Setup labor.</p>
    <p className="mt-3">Setup has no prepaid materials allowance. Customer-supplied blades incur no blade charge; IDS-supplied blades, grease, consumables, and parts are charged separately for actual eligible use. Customer-authorized purchases or consumed/non-returnable parts remain reconcilable if Setup is removed.</p>
    <p className="mt-3">Installation + Setup uses one booking, one $250 deposit credited toward the balance, and one travel charge. Two hours of one-way drive time from Williamsville, Missouri are included; additional combined-trip travel is $35 per started excess hour total. At 2.5 hours away this is $35; at 3.5 hours it is $70. A continuation does not create another charge merely because Setup exists. A separate future Setup-only visit follows the separate-visit travel rules.</p>
    <p className="mt-3">Eligible Remote Support subscribers receive 25% off eligible Setup labor and the one eligible travel charge, without a parts/materials discount. Eligibility will come only from the website’s active Remote Support subscriptions. Until that service launches, the subscriber discount is unavailable. Removing Setup does not refund or recreate the booking deposit.</p>
    <p className="mt-3">The same safety, weather, access, authorized-adult, cancellation, and rescheduling rules apply. The technician retains final technical authority over safe mapping, pathways, exclusions, and operating plans, while reasonably considering customer preferences. If a materially better approach would change the requested property-use plan, work pauses for an explanation of the benefits and drawbacks and customer approval.</p>
    <p className="mt-3">Unsafe electrical/property conditions, unsecured or aggressive animals, severe weather, threats, interference, or restricted access may pause or end work under the Installation safety and remediation rules, including documentation/photos and applicable rescheduling. An authorized adult must provide safe access and property authority.</p>
    <p className="mt-3">The single $250 deposit is fully refundable for cancellation more than 48 hours before the appointment, $125 refundable at 24–48 hours, and non-refundable within 24 hours. Existing approved cash-on-arrival failure/reschedule/forfeiture rules still apply. Allow 7–12 business days after IDS issues an approved refund.</p>
  </details>;
}
