import "server-only";
import { getSupabaseServiceClient } from "@/lib/supabase";
import type { CheckoutRequest, OrderPriceSnapshot, PaymentAttemptStatus, PaymentStatus } from "./types";

export class CheckoutRepositoryError extends Error { constructor(public code: "CONFLICT"|"UNAVAILABLE", message="Checkout repository operation failed."){super(message)} }
export type DraftResult={customerId:string;stripeCustomerId:string|null;orderId:string;publicReference:string;attemptId:string;attemptNumber:number;attemptStatus:PaymentAttemptStatus;attemptCreatedAt:string;stripeIdempotencyKey:string;sessionId:string|null};
export type CheckoutRecord={attemptId:string;orderId:string;customerId:string;publicReference:string;attemptStatus:PaymentAttemptStatus;paymentStatus:PaymentStatus;orderStatus:string;fulfillmentStatus:string;currency:"usd";totalCents:number;refundedCents:number;fundedAmountCents:number|null;amountRemainingCents:number|null;snapshot:OrderPriceSnapshot;sessionId:string|null;paymentIntentId:string|null};
export type ApplyCardEventV2Params={p_kind:"paid"|"processing"|"expired"|"refund"|"dispute";p_session_id:string|null;p_payment_intent_id:string|null;p_order_id:string;p_attempt_id:string;p_amount:number|null;p_currency:string|null;p_stripe_session_status:string|null;p_stripe_payment_status:string|null;p_refunded?:number|null;p_stripe_customer_id?:string|null;p_contact?:Record<string,unknown>|null};
const one=<T>(r:{data:T|null;error:{code?:string;message:string}|null}):T=>{if(r.error) throw new CheckoutRepositoryError(r.error.code==="23505"||r.error.message.includes("conflict")?"CONFLICT":"UNAVAILABLE");if(!r.data)throw new CheckoutRepositoryError("UNAVAILABLE");return r.data};
const completed=(r:{error:{code?:string;message:string}|null})=>{if(r.error)throw new CheckoutRepositoryError(r.error.code==="23505"||r.error.message.includes("conflict")?"CONFLICT":"UNAVAILABLE")};
export async function createCardCheckoutDraft(request:CheckoutRequest,snapshot:OrderPriceSnapshot,idempotencyKey:string,fingerprint:string){return one<DraftResult>(await getSupabaseServiceClient().rpc("checkout_create_card_draft",{p_idempotency_key:idempotencyKey,p_request_fingerprint:fingerprint,p_customer:{...request.customer,shippingAddress:request.shippingAddress},p_snapshot:snapshot}) as never)}
export async function createAchCheckoutDraft(request:CheckoutRequest,snapshot:OrderPriceSnapshot,idempotencyKey:string,fingerprint:string){return one<DraftResult>(await getSupabaseServiceClient().rpc("checkout_create_ach_draft",{p_idempotency_key:idempotencyKey,p_request_fingerprint:fingerprint,p_customer:{...request.customer,shippingAddress:request.shippingAddress},p_snapshot:snapshot}) as never)}
export async function createWireCheckoutDraft(request:CheckoutRequest,snapshot:OrderPriceSnapshot,idempotencyKey:string,fingerprint:string){return one<DraftResult>(await getSupabaseServiceClient().rpc("checkout_create_wire_draft",{p_idempotency_key:idempotencyKey,p_request_fingerprint:fingerprint,p_customer:{...request.customer,shippingAddress:request.shippingAddress},p_snapshot:snapshot}) as never)}
export async function linkCheckoutSession(attemptId:string,session:{id:string;payment_intent:string|null;status:string|null;payment_status:string;created:number;expires_at:number|null}){completed(await getSupabaseServiceClient().rpc("checkout_link_card_session",{p_attempt_id:attemptId,p_session_id:session.id,p_payment_intent_id:session.payment_intent,p_session_status:session.status,p_payment_status:session.payment_status,p_created_at:new Date(session.created*1000).toISOString(),p_expires_at:session.expires_at?new Date(session.expires_at*1000).toISOString():null}))}
export async function linkAchCheckoutSession(attemptId:string,session:{id:string;payment_intent:string|null;status:string|null;payment_status:string;payment_intent_status:string|null;created:number;expires_at:number|null}){completed(await getSupabaseServiceClient().rpc("checkout_link_ach_session",{p_attempt_id:attemptId,p_session_id:session.id,p_payment_intent_id:session.payment_intent,p_session_status:session.status,p_payment_status:session.payment_status,p_payment_intent_status:session.payment_intent_status,p_created_at:new Date(session.created*1000).toISOString(),p_expires_at:session.expires_at?new Date(session.expires_at*1000).toISOString():null}))}
export async function linkWireCheckoutSession(attemptId:string,stripeCustomerId:string,session:{id:string;payment_intent:string|null;status:string|null;payment_status:string;payment_intent_status:string|null;created:number;expires_at:number|null}){completed(await getSupabaseServiceClient().rpc("checkout_link_wire_session",{p_attempt_id:attemptId,p_stripe_customer_id:stripeCustomerId,p_session_id:session.id,p_payment_intent_id:session.payment_intent,p_session_status:session.status,p_payment_status:session.payment_status,p_payment_intent_status:session.payment_intent_status,p_created_at:new Date(session.created*1000).toISOString(),p_expires_at:session.expires_at?new Date(session.expires_at*1000).toISOString():null}))}
export async function findCheckoutRecord(field:"stripe_checkout_session_id"|"stripe_payment_intent_id",value:string):Promise<CheckoutRecord|null>{const r=await getSupabaseServiceClient().rpc("checkout_find_attempt",{p_session_id:field==="stripe_checkout_session_id"?value:null,p_payment_intent_id:field==="stripe_payment_intent_id"?value:null});if(r.error)throw new CheckoutRepositoryError("UNAVAILABLE");return r.data as CheckoutRecord|null}
export const findBySessionId=(id:string)=>findCheckoutRecord("stripe_checkout_session_id",id); export const findByPaymentIntentId=(id:string)=>findCheckoutRecord("stripe_payment_intent_id",id);
export async function findActiveWireByStripeCustomerId(id:string):Promise<CheckoutRecord|null>{const r=await getSupabaseServiceClient().rpc("checkout_find_wire_attempt_by_customer",{p_stripe_customer_id:id});if(r.error)throw new CheckoutRepositoryError("UNAVAILABLE");return r.data as CheckoutRecord|null}
export async function recordWebhookReceipt(e:{id:string;type:string;objectId:string|null;livemode:boolean;apiVersion:string|null}){return one<{state:string}>(await getSupabaseServiceClient().rpc("checkout_record_webhook",{p_event_id:e.id,p_event_type:e.type,p_object_id:e.objectId,p_livemode:e.livemode,p_api_version:e.apiVersion}) as never).state}
export async function finishWebhook(id:string,status:"processed"|"failed"|"ignored",code:string|null=null){completed(await getSupabaseServiceClient().rpc("checkout_finish_webhook",{p_event_id:id,p_status:status,p_error_code:code}))}
export async function applyCardEventV2(p:ApplyCardEventV2Params){return one(await getSupabaseServiceClient().rpc("checkout_apply_card_event_v2",p) as never)}
export async function applyAchEventV1(p:Record<string,unknown>){return one(await getSupabaseServiceClient().rpc("checkout_apply_ach_event_v1",p) as never)}
export async function applyWireEventV1(p:Record<string,unknown>){return one(await getSupabaseServiceClient().rpc("checkout_apply_wire_event_v1",p) as never)}
export function safeProjection(r:CheckoutRecord){return{publicReference:r.publicReference,attemptStatus:r.attemptStatus,paymentStatus:r.paymentStatus,orderStatus:r.orderStatus,fulfillmentStatus:r.fulfillmentStatus,currency:r.currency,totalCents:r.totalCents,refundedCents:r.refundedCents,fundedAmountCents:r.fundedAmountCents,amountRemainingCents:r.amountRemainingCents,items:[...r.snapshot.chargeableItems,...r.snapshot.includedPackageComponents].map(i=>({name:i.name,quantity:i.quantity,included:i.includedInPackagePrice}))}}
