"use client";

import { useEffect, useState, type FormEvent } from "react";
import type { PricingItem } from "@/lib/admin-pricing/types";
import type { CatalogDependencies, ManagedCatalog, ManagedCatalogItem, ManagedPackage, PackageComponent } from "@/lib/catalog-management/types";
import { centralDateTimeInputToIso, isoToLocalDateTimeInput } from "@/lib/admin-pricing/datetime-local";
import { sellingPriceDecision } from "@/lib/pricing-program/policy";
import AdminPricingDialog from "./AdminPricingDialog";
import AccessoryImageUploader from "./AccessoryImageUploader";
import { pricingMoney } from "./PricingCatalogCard";

export type CatalogAction = { type: "create-product" | "create-package" } | { type: "edit" | "delete"; item: PricingItem };
type CatalogRecord = ManagedCatalogItem | ManagedPackage;
type Draft = { name: string; slug: string; brand: string; category: string; description: string; imageUrl: string; compatibility: string; status: string; msrp: string; regular: string; sale: string; cost: string; start: string; end: string; promotion: string; showPrice: boolean; contact: boolean; coreSelectable: boolean };
const fieldClass = "mt-2 w-full rounded-xl border border-slate-300 bg-white p-3 text-sm font-normal";
const priceFields = [["msrp", "Manufacturer / MSRP"], ["regular", "IDS Everyday Price"], ["sale", "Temporary Sale Price"], ["cost", "Dealer Cost — PRIVATE / IDS INTERNAL ONLY"]] as const;
const dollars = (value: unknown) => typeof value === "number" ? (value / 100).toFixed(2) : "";
const amount = (value: string) => !value.trim() ? null : /^\d+(?:\.\d{1,2})?$/.test(value) && Number.isSafeInteger(Math.round(Number(value) * 100)) ? Math.round(Number(value) * 100) : NaN;
const recordDraft = (item?: CatalogRecord): Draft => ({ name: item?.name ?? "", slug: item?.slug ?? "", brand: item?.brand ?? "", category: item?.category ?? "machine", description: item?.description ?? "", imageUrl: item?.imageUrl ?? "", compatibility: item?.compatibility.join(", ") ?? "", status: item?.publicStatus ?? "active", msrp: dollars(item?.values.display_msrp_price_cents), regular: dollars(item?.values.regular_price_cents), sale: dollars(item?.values.sale_price_cents), cost: dollars(item?.values.dealer_cost_cents ?? item?.dealerCostCents), start: isoToLocalDateTimeInput(typeof item?.values.sale_starts_at === "string" ? item.values.sale_starts_at : null), end: isoToLocalDateTimeInput(typeof item?.values.sale_ends_at === "string" ? item.values.sale_ends_at : null), promotion: typeof item?.values.promotion_label === "string" ? item.values.promotion_label : "", showPrice: item?.values.show_public_price !== false, contact: item?.values.contact_for_pricing === true, coreSelectable: item?.kind === "packages" && item.isYarboCoreSelectable });

function pricingValues(draft: Draft) {
  const prices = { display_msrp_price_cents: amount(draft.msrp), regular_price_cents: amount(draft.regular), sale_price_cents: amount(draft.sale), dealer_cost_cents: amount(draft.cost) };
  if (Object.values(prices).some(value => typeof value === "number" && !Number.isFinite(value))) throw new Error("Enter valid dollar amounts with no more than two decimal places, or leave them blank.");
  const start = centralDateTimeInputToIso(draft.start); const end = centralDateTimeInputToIso(draft.end);
  if ((draft.start && !start) || (draft.end && !end)) throw new Error("Enter valid Central Time sale dates.");
  return { ...prices, sale_starts_at: start, sale_ends_at: end, promotion_label: draft.promotion.trim() || null, show_public_price: draft.showPrice, contact_for_pricing: draft.contact };
}

function PricingFields({ draft, onChange, label }: { draft: Draft; onChange: (value: Draft) => void; label?: string }) {
  return <fieldset className="grid gap-4 rounded-2xl border border-slate-200 p-4 sm:grid-cols-2"><legend className="px-2 font-black">{label ?? "Independent offering pricing"}</legend>{priceFields.map(([field, name]) => <label key={field} className="text-sm font-bold">{name} ($)<input type="number" min="0" step="0.01" value={draft[field]} onChange={event => onChange({ ...draft, [field]: event.target.value })} className={fieldClass}/><span className="mt-1 block text-xs font-normal text-slate-500">Blank = not set.</span></label>)}{([["start","Sale Start"],["end","Sale End"]] as const).map(([field,name]) => <label key={field} className="text-sm font-bold">{name} (Central Time)<input type="datetime-local" value={draft[field]} onChange={event => onChange({ ...draft, [field]: event.target.value })} className={fieldClass}/></label>)}<label className="text-sm font-bold sm:col-span-2">Promotion Label<input maxLength={160} value={draft.promotion} onChange={event => onChange({ ...draft, promotion: event.target.value })} className={fieldClass}/></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={draft.showPrice} onChange={event => onChange({ ...draft, showPrice: event.target.checked })}/> Show public price</label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={draft.contact} onChange={event => onChange({ ...draft, contact: event.target.checked })}/> Contact for pricing</label></fieldset>;
}

export function componentReferenceTotal(components: PackageComponent[], items: ManagedCatalogItem[]) {
  let cents = 0; let unknown = 0;
  const catalog = new Map(items.map(item => [`${item.kind}:${item.id}`, item]));
  for (const component of components) {
    const item = catalog.get(`${component.kind}:${component.id}`);
    if (item?.effectivePriceCents == null) unknown += 1;
    else cents += item.effectivePriceCents * component.quantity;
  }
  return { cents, unknown };
}

function PackageComponents({ items, components, onChange, allowInactive, onAllowInactive }: { items: ManagedCatalogItem[]; components: PackageComponent[]; onChange: (components: PackageComponent[]) => void; allowInactive: boolean; onAllowInactive: (allow: boolean) => void }) {
  const [search, setSearch] = useState(""); const [brand, setBrand] = useState("all"); const [category, setCategory] = useState("all");
  const brands = [...new Set(items.map(item => item.brand))].sort(); const categories = [...new Set(items.map(item => item.category))].sort();
  const logicalCoreAvailable = items.some(item => item.kind === "products" && item.slug === "yarbo" && !item.retiredAt && item.packageSelectable !== false && (allowInactive || item.publicStatus === "active"));
  const results = items.filter(item => item.packageSelectable !== false && !item.retiredAt && !(logicalCoreAvailable && item.kind === "variants" && (item.slug === "yarbo-y40" || item.slug === "yarbo-y40p")) && (allowInactive || item.publicStatus === "active") && (brand === "all" || item.brand === brand) && (category === "all" || item.category === category) && `${item.name} ${item.slug} ${item.brand}`.toLowerCase().includes(search.toLowerCase()));
  const total = componentReferenceTotal(components, items);
  function add(item: ManagedCatalogItem) { if (components.some(component => component.kind === item.kind && component.id === item.id)) return; onChange([...components, { kind: item.kind, id: item.id, quantity: 1 }]); }
  return <fieldset className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 font-black">Package contents</legend>
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">Search items<input value={search} onChange={event => setSearch(event.target.value)} placeholder="Name, slug, or brand" className={fieldClass}/></label><label className="text-sm font-bold">Brand<select value={brand} onChange={event => setBrand(event.target.value)} className={fieldClass}><option value="all">All brands</option>{brands.map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold">Category<select value={category} onChange={event => setCategory(event.target.value)} className={fieldClass}><option value="all">All categories</option>{categories.map(value => <option key={value}>{value}</option>)}</select></label></div>
    <label className="mt-4 flex items-start gap-2 text-xs font-bold text-amber-900"><input type="checkbox" checked={allowInactive} onChange={event => onAllowInactive(event.target.checked)}/> Explicit override: include inactive items. The package remains subject to component availability.</label>
    <p className="mt-2 text-xs text-slate-500">Quote-only offerings use the existing quote workflow. Select the logical Yarbo Core once; customers choose Y40 or Y40P afterward.</p>
    <ul aria-label="Available package components" className="mt-4 max-h-64 space-y-2 overflow-y-auto rounded-xl bg-slate-50 p-2">{results.map(item => { const selected = components.some(component => component.kind === item.kind && component.id === item.id); return <li key={`${item.kind}:${item.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold">{item.slug === "yarbo" ? "Yarbo Core (customer chooses Y40 or Y40P)" : item.name}</p><p className="mt-1 text-xs text-slate-600">{item.brand} · {item.category} · {item.publicStatus.replaceAll("_", " ")}</p>{item.compatibility.length > 0 && <p className="mt-1 text-xs text-slate-500">Compatibility: {item.compatibility.join(", ")}</p>}</div><button type="button" disabled={selected} onClick={() => add(item)} className="min-h-11 rounded-lg border border-emerald-600 px-3 text-sm font-black text-emerald-800 disabled:border-slate-200 disabled:text-slate-400">{selected ? "Selected" : "Add"}</button></li>; })}{results.length === 0 && <li className="p-3 text-sm text-slate-600">No matching active catalog items.</li>}</ul>
    <h3 className="mt-5 text-sm font-black">Selected components ({components.length})</h3><ul className="mt-2 space-y-2">{components.map(component => { const item = items.find(candidate => candidate.kind === component.kind && candidate.id === component.id); return <li key={`${component.kind}:${component.id}`} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><p className="min-w-0 basis-full text-sm font-bold sm:basis-auto sm:flex-1">{item?.slug === "yarbo" ? "Yarbo Core (Y40 or Y40P)" : item?.name ?? "Catalog component"}{item?.publicStatus !== "active" && <span className="mt-1 block text-xs text-amber-800">Inactive component — review availability before publishing.</span>}</p><label className="text-xs font-bold">Quantity<input aria-label={`Quantity for ${item?.name ?? component.id}`} type="number" min="1" max="100" step="1" value={component.quantity} onChange={event => onChange(components.map(current => current.kind === component.kind && current.id === component.id ? { ...current, quantity: Number(event.target.value) } : current))} className="ml-2 min-h-11 w-20 rounded-lg border p-2"/></label><button type="button" onClick={() => onChange(components.filter(current => current.kind !== component.kind || current.id !== component.id))} className="min-h-11 rounded-lg border px-3 text-xs font-bold text-red-700">Remove</button></li>; })}{components.length === 0 && <li className="text-sm text-slate-600">Select at least one item to build this package.</li>}</ul>
    <div className="mt-4 rounded-xl bg-blue-50 p-3 text-sm"><p className="font-black">Individual component total: {pricingMoney(total.cents)}</p>{total.unknown > 0 && <p className="mt-1 text-xs">{total.unknown} selected component(s) have no current customer price and are excluded from this reference total.</p>}<p className="mt-1 text-xs">Admin reference only. Set the package selling price independently below.</p></div>
  </fieldset>;
}

function CatalogForm({ action, catalog, onClose, onSaved }: { action: Exclude<CatalogAction, { type: "delete" }>; catalog: ManagedCatalog; onClose: () => void; onSaved: (message: string) => Promise<void> }) {
  const editing = action.type === "edit" ? [...catalog.items, ...catalog.packages].find(item => item.kind === action.item.kind && item.id === action.item.id) : undefined;
  const packageForm = action.type === "create-package" || editing?.kind === "packages";
  const [draft, setDraft] = useState(() => recordDraft(editing));
  const [coreDraft, setCoreDraft] = useState(() => recordDraft());
  const [components, setComponents] = useState<PackageComponent[]>(() => editing?.kind === "packages" ? editing.components : []);
  const [allowInactive, setAllowInactive] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const snapshot = action.type === "edit" ? action.item : null;
  const previewAmount = (value: string) => { const parsed = amount(value); return typeof parsed === "number" && Number.isFinite(parsed) ? parsed : null; };
  const proposed = sellingPriceDecision({ display_msrp_price_cents: previewAmount(draft.msrp), regular_price_cents: previewAmount(draft.regular), sale_price_cents: previewAmount(draft.sale), sale_starts_at: centralDateTimeInputToIso(draft.start), sale_ends_at: centralDateTimeInputToIso(draft.end) }, snapshot?.pricingProgramEnabled !== false);
  const proposedPrice = snapshot?.priceContextBlocked ? null : snapshot?.activeScheduleName ? snapshot.effectivePriceCents : snapshot?.quoteOnly || draft.status === "hidden" || !draft.showPrice || draft.contact ? null : proposed.priceCents;
  const coreSelected = components.some(component => { const item = catalog.items.find(item => item.kind === component.kind && item.id === component.id); return item?.kind === "products" && item.slug === "yarbo" || item?.kind === "variants" && (item.slug === "yarbo-y40" || item.slug === "yarbo-y40p"); });
  const coreSelectable = draft.coreSelectable || coreSelected;
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");
    if (action.type === "edit" && !editing) { setError("This offering is no longer in the catalog. Close and refresh Pricing Management."); return; }
    if (packageForm && (!components.length || components.some(component => !Number.isInteger(component.quantity) || component.quantity < 1 || component.quantity > 100))) { setError("Select at least one component and use quantities from 1 to 100."); return; }
    try {
      const prices = pricingValues(draft);
      const metadata: Record<string, unknown> = { ...(packageForm ? { package_name: draft.name.trim() } : { name: draft.name.trim() }), description: draft.description.trim() || null, image_url: draft.imageUrl.trim() || null, public_status: draft.status, ...prices };
      if (!packageForm && (!editing || editing.kind === "products")) Object.assign(metadata, { brand: draft.brand.trim(), category: draft.category.trim(), compatibility: draft.compatibility.split(",").map(value => value.trim()).filter(Boolean) });
      let path: string; let body: Record<string, unknown>;
      if (editing) { path = `/api/admin/catalog-management/${editing.kind}/${editing.id}`; body = { expectedUpdatedAt: editing.updatedAt, values: metadata, ...(packageForm ? { components, allowInactiveComponents: allowInactive } : {}) }; }
      else if (packageForm) { path = "/api/admin/catalog-management/packages"; body = { ...metadata, package_slug: draft.slug.trim(), brand: draft.brand.trim(), components, isYarboCoreSelectable: coreSelectable, allowInactiveComponents: allowInactive, ...(coreSelectable ? { corePrices: { y40p: pricingValues(coreDraft) } } : {}) }; }
      else { path = "/api/admin/catalog-management/products"; body = { ...metadata, slug: draft.slug.trim() }; }
      setBusy(true);
      const response = await fetch(path, { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error ?? "The offering could not be saved.");
      const item = payload.item ?? payload.package;
      const priceMessage = typeof item?.effectivePriceCents === "number" ? `Customer price is now ${pricingMoney(item.effectivePriceCents)}.` : "Review the offering’s current customer price and availability on its pricing card.";
      await onSaved(`${editing ? "Saved" : "Created"} ${draft.name}. ${priceMessage}`); onClose();
    } catch (failure) { setError(failure instanceof Error ? failure.message : "The offering could not be saved."); }
    finally { setBusy(false); }
  }
  return <AdminPricingDialog title={editing ? `Edit catalog · ${editing.name}` : packageForm ? "Create New Package" : "Add New Product"} onClose={onClose} busy={busy} wide={packageForm}><form onSubmit={save} className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">{packageForm ? "Package" : "Product"} Name<input required maxLength={160} value={draft.name} onChange={event => setDraft(current => ({ ...current, name: event.target.value }))} className={fieldClass}/></label><label className="text-sm font-bold">Slug<input required disabled={Boolean(editing)} pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={160} value={draft.slug} onChange={event => setDraft(current => ({ ...current, slug: event.target.value }))} placeholder="product-or-package-name" className={fieldClass}/>{editing && <span className="mt-1 block text-xs font-normal text-slate-500">The existing URL is preserved.</span>}</label>{!packageForm && (!editing || editing.kind === "products") && <><label className="text-sm font-bold">Brand<input required maxLength={160} value={draft.brand} onChange={event => setDraft(current => ({ ...current, brand: event.target.value }))} className={fieldClass}/></label>{!packageForm && <label className="text-sm font-bold">Category<input required list="catalog-product-categories" maxLength={80} value={draft.category} onChange={event => setDraft(current => ({ ...current, category: event.target.value }))} className={fieldClass}/><datalist id="catalog-product-categories">{["machine","Core","module","attachment","accessory","battery","replacement part","other"].map(value => <option key={value} value={value}/>)}</datalist></label>}</>}<label className="text-sm font-bold sm:col-span-2">Description<textarea rows={3} maxLength={5000} value={draft.description} onChange={event => setDraft(current => ({ ...current, description: event.target.value }))} className={fieldClass}/></label><label className="text-sm font-bold">Image / media reference<input value={draft.imageUrl} onChange={event => setDraft(current => ({ ...current, imageUrl: event.target.value }))} placeholder="Existing image URL or uploaded media" className={fieldClass}/></label><AccessoryImageUploader onUploaded={imageUrl => setDraft(current => ({ ...current, imageUrl }))}/>{!packageForm && (!editing || editing.kind === "products") && <label className="text-sm font-bold">Compatibility<input value={draft.compatibility} onChange={event => setDraft(current => ({ ...current, compatibility: event.target.value }))} placeholder="Y40, Y40P, or compatible product identifiers" className={fieldClass}/><span className="mt-1 block text-xs font-normal text-slate-500">Separate entries with commas.</span></label>}<label className="text-sm font-bold">Availability<select value={draft.status} onChange={event => setDraft(current => ({ ...current, status: event.target.value }))} className={fieldClass}>{["active","unavailable","coming_soon","hidden"].map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label></div>
    {packageForm && <><PackageComponents items={catalog.items} components={components} onChange={setComponents} allowInactive={allowInactive} onAllowInactive={setAllowInactive}/><label className="flex items-start gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-bold"><input type="checkbox" checked={coreSelectable} disabled={coreSelected || Boolean(editing)} onChange={event => setDraft(current => ({ ...current, coreSelectable: event.target.checked }))}/> Customer selects Yarbo Core: Y40 or Y40P<span className="font-normal">One logical public package with two Admin pricing contexts.</span></label>{coreSelectable && <p className="text-xs text-slate-600">Select the logical Yarbo Core once. Do not include both physical Core variants in the package. Customers choose their Core in the existing Yarbo flow.</p>}</>}
    {snapshot && <div className="grid gap-3 rounded-2xl bg-slate-100 p-4 sm:grid-cols-2"><div><p className="text-xs font-black uppercase">Current customer price</p><p className="mt-1 text-2xl font-black">{pricingMoney(snapshot.effectivePriceCents)}</p></div><div><p className="text-xs font-black uppercase">Proposed customer price</p><p className="mt-1 text-2xl font-black">{pricingMoney(proposedPrice)}</p><p className="mt-1 text-xs text-slate-600">{snapshot.priceContextBlocked ? "A parent offering or required dependency currently blocks this pricing context." : snapshot.activeScheduleName ? `Active schedule ${snapshot.activeScheduleName} continues to control the amount.` : "Final pricing and component availability are rechecked when saved."}</p></div></div>}
    <PricingFields draft={draft} onChange={setDraft} label={packageForm && coreSelectable ? "Y40 package pricing" : undefined}/>{packageForm && coreSelectable && !editing && <PricingFields draft={coreDraft} onChange={setCoreDraft} label="Y40P package pricing"/>}{packageForm && coreSelectable && editing && <p className="rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-950">Y40P pricing is edited on the Y40P card. Package contents are shared by both Core choices.</p>}
    {error && <p role="alert" className="rounded-xl bg-red-50 p-3 font-bold text-red-800">{error}</p>}<button disabled={busy} className="min-h-12 w-full rounded-xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-60">{busy ? "Saving…" : editing ? "Save catalog offering" : packageForm ? "Create package" : "Create product"}</button>
  </form></AdminPricingDialog>;
}

function DeleteOffering({ item, onClose, onSaved }: { item: PricingItem; onClose: () => void; onSaved: (message: string) => Promise<void> }) {
  const [dependencies, setDependencies] = useState<CatalogDependencies | null>(null); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); void fetch(`/api/admin/catalog-management/${item.kind}/${item.id}/dependencies`, { cache: "no-store", signal: controller.signal }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Dependencies could not be checked."); setDependencies(payload); }).catch(failure => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "Dependencies could not be checked."); }); return () => controller.abort(); }, [item.kind,item.id]);
  async function remove() {
    setBusy(true); setError("");
    try { const response = await fetch(`/api/admin/catalog-management/${item.kind}/${item.id}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedUpdatedAt: item.updatedAt, retireDependentPackages: Boolean(dependencies?.packages.length && confirmed) }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error ?? "The offering could not be removed."); await onSaved(`${item.name} was removed from the active catalog. Historical transactions are preserved.`); onClose(); } catch (failure) { setError(failure instanceof Error ? failure.message : "The offering could not be removed."); } finally { setBusy(false); }
  }
  return <AdminPricingDialog title={`Delete ${item.name}`} onClose={onClose} busy={busy}><p className="text-sm leading-6 text-slate-600">Delete removes this offering from the active sellable catalog. Existing orders, invoices, and transaction history remain intact.</p>{item.kind === "packages" && item.brand === "Yarbo" && <p className="mt-3 rounded-xl bg-blue-50 p-3 text-sm font-bold">This removes the one logical package and both its Y40 and Y40P pricing contexts.</p>}{!dependencies && !error && <p role="status" className="mt-4 font-bold">Checking package and history dependencies…</p>}{dependencies && dependencies.packages.length > 0 && <div className="mt-4 rounded-2xl border border-amber-300 bg-amber-50 p-4"><p className="font-black">This product is currently used in {dependencies.packages.length} active package{dependencies.packages.length === 1 ? "" : "s"}.</p><ul className="my-3 list-disc space-y-1 pl-5 text-sm">{dependencies.packages.map(pkg => <li key={pkg.id}>{pkg.name}</li>)}</ul><p className="text-sm">Removing it also retires these packages so customers cannot select an incomplete configuration.</p><label className="mt-4 flex items-start gap-2 text-sm font-black"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)}/> I intend to remove this offering and retire the affected packages.</label></div>}{dependencies?.historicalReferences && <p className="mt-4 text-sm font-bold">Historical references exist. The catalog record will be retired while its history is preserved.</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 font-bold text-red-800">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={busy || !dependencies || Boolean(dependencies.packages.length && !confirmed)} onClick={() => void remove()} className="min-h-12 rounded-xl bg-red-700 px-5 py-3 font-black text-white disabled:opacity-50">{busy ? "Removing…" : "Delete from active catalog"}</button><button type="button" disabled={busy} onClick={onClose} className="min-h-12 rounded-xl border px-5 py-3 font-bold">Cancel</button></div></AdminPricingDialog>;
}

function CatalogDialog({ action, onClose, onSaved }: { action: CatalogAction; onClose: () => void; onSaved: (message: string) => Promise<void> }) {
  const [catalog, setCatalog] = useState<ManagedCatalog | null>(null); const [error,setError] = useState("");
  useEffect(() => { if (action.type === "delete") return; const controller = new AbortController(); void fetch("/api/admin/catalog-management", { cache: "no-store", signal: controller.signal }).then(async response => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "The catalog could not be loaded."); setCatalog(payload); }).catch(failure => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "The catalog could not be loaded."); }); return () => controller.abort(); }, [action.type]);
  if (action.type === "delete") return <DeleteOffering item={action.item} onClose={onClose} onSaved={onSaved}/>;
  if (!catalog) return <AdminPricingDialog title="Catalog Management" onClose={onClose}>{error ? <p role="alert" className="font-bold text-red-800">{error}</p> : <p role="status">Loading catalog…</p>}</AdminPricingDialog>;
  return <CatalogForm action={action} catalog={catalog} onClose={onClose} onSaved={onSaved}/>;
}

export default function CatalogManagement({ action, onAction, onSaved }: { action: CatalogAction | null; onAction: (action: CatalogAction | null) => void; onSaved: (message: string) => Promise<void> }) {
  return <><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={() => onAction({ type: "create-product" })} className="min-h-12 rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">+ Add New Product</button><button type="button" onClick={() => onAction({ type: "create-package" })} className="min-h-12 rounded-xl bg-slate-950 px-5 py-3 font-black text-white">+ Create New Package</button></div>{action && <CatalogDialog key={`${action.type}:${"item" in action ? `${action.item.kind}:${action.item.id}` : "new"}`} action={action} onClose={() => onAction(null)} onSaved={onSaved}/>}</>;
}
