create table public.featured_businesses (
 id uuid primary key default gen_random_uuid(), business_name text not null check(char_length(business_name) between 1 and 160), description text not null check(char_length(description) between 1 and 3000), operating_region text check(operating_region is null or char_length(operating_region)<=200), image_url text check(image_url is null or char_length(image_url)<=2000), image_path text check(image_path is null or char_length(image_path)<=500), image_alt text check(image_alt is null or char_length(image_alt)<=240), website_url text check(website_url is null or website_url~'^https?://'), facebook_url text check(facebook_url is null or facebook_url~'^https?://'), phone text check(phone is null or char_length(phone)<=80), address text check(address is null or char_length(address)<=500), referral_code text check(referral_code is null or char_length(referral_code)<=100), special_offer text check(special_offer is null or char_length(special_offer)<=1000), is_public boolean not null default false, is_featured boolean not null default false, is_archived boolean not null default false, sort_order integer not null default 100 check(sort_order between 0 and 100000), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), constraint featured_business_visibility check(not is_featured or(is_public and not is_archived))
);
create unique index featured_businesses_single_featured_idx on public.featured_businesses(is_featured) where is_featured;
create index featured_businesses_public_directory_idx on public.featured_businesses(sort_order,business_name) where is_public and not is_archived;
create table public.featured_business_clicks(id bigint generated always as identity primary key,featured_business_id uuid not null references public.featured_businesses(id) on delete cascade,destination_type text not null check(destination_type in('website','facebook')),source text check(source in('homepage','directory')),clicked_at timestamptz not null default now());
create index featured_business_clicks_business_idx on public.featured_business_clicks(featured_business_id,clicked_at desc);
alter table public.featured_businesses enable row level security;
alter table public.featured_business_clicks enable row level security;
revoke all on table public.featured_businesses,public.featured_business_clicks from public,anon,authenticated,service_role;
grant select on table public.featured_businesses to anon,authenticated;
grant select,insert,update,delete on table public.featured_businesses to service_role;
grant select,insert on table public.featured_business_clicks to service_role;
grant usage,select on sequence public.featured_business_clicks_id_seq to service_role;
create policy "Eligible featured businesses are publicly readable" on public.featured_businesses for select to anon,authenticated using(is_public and not is_archived);
create function public.set_featured_business(p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin perform pg_catalog.pg_advisory_xact_lock(73190421);if not exists(select 1 from public.featured_businesses where id=p_business_id and is_public and not is_archived)then raise exception 'Featured business must be public and not archived';end if;update public.featured_businesses set is_featured=false,updated_at=now() where is_featured and id<>p_business_id;update public.featured_businesses set is_featured=true,updated_at=now() where id=p_business_id;end;$$;
revoke all on function public.set_featured_business(uuid) from public,anon,authenticated;
grant execute on function public.set_featured_business(uuid) to service_role;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('featured-business-images','featured-business-images',true,5242880,array['image/jpeg','image/png','image/webp'])on conflict(id)do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
