import "server-only";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { toPublicEntry } from "./public";
import type { IdsActionInput } from "./types";
const columns="id,title,description,category,location,event_date,featured,published,customer_permission_confirmed,sort_order,created_at,updated_at,ids_action_media(id,entry_id,media_type,media_url,storage_path,thumbnail_url,alt_text,sort_order,created_at)";
export async function readPublicEntries({category,featured=false,limit=12,offset=0}:{category?:string;featured?:boolean;limit?:number;offset?:number}){let q=getSupabaseServiceClient().from("ids_action_entries").select(columns,{count:"exact"}).eq("published",true).order("event_date",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false}).range(offset,offset+Math.min(limit,24)-1);if(featured)q=q.eq("featured",true);if(category&&category!=="all")q=q.eq("category",category);const{data,error,count}=await q;if(error)throw error;return{entries:(data??[]).map(r=>toPublicEntry(r as unknown as Record<string,unknown>)),count:count??0};}
export async function readAdminEntries(){const{data,error}=await getSupabaseServiceClient().from("ids_action_entries").select(columns).order("event_date",{ascending:false,nullsFirst:false}).order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(entry=>({...entry,ids_action_media:[...(entry.ids_action_media??[])].sort((a,b)=>a.sort_order-b.sort_order)}));}
const row=(v:IdsActionInput)=>({title:v.title,description:v.description,category:v.category,location:v.location,event_date:v.eventDate,featured:v.featured,published:v.published,customer_permission_confirmed:v.customerPermissionConfirmed,sort_order:v.sortOrder,updated_at:new Date().toISOString()});
export async function saveEntry(v:IdsActionInput,id?:string){const c=getSupabaseServiceClient();const q=id?c.from("ids_action_entries").update(row(v)).eq("id",id):c.from("ids_action_entries").insert(row(v));const{data,error}=await q.select(columns).single();if(error)throw error;return data;}
export async function deleteEntry(id:string){const c=getSupabaseServiceClient();const{data}=await c.from("ids_action_media").select("storage_path").eq("entry_id",id);const paths=(data??[]).map(x=>x.storage_path).filter(Boolean) as string[];if(paths.length)await c.storage.from("ids-action-media").remove(paths);const{error}=await c.from("ids_action_entries").delete().eq("id",id);if(error)throw error;}
