import "server-only";
import { sendServerEmail } from "@/lib/email";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { processBusinessImageCleanup } from "./server";
import { reminderKind, type RenewalCandidate } from "./listing-lifecycle-policy";

export type LifecycleCounts={reminders30Sent:number;reminders7Sent:number;expired:number;purged:number;imagesRemoved:number};
export type LifecycleDependencies={candidates:()=>Promise<RenewalCandidate[]>;send:(message:{to:string;subject:string;text:string})=>Promise<unknown>;markReminder:(id:string,kind:30|7,at:string)=>Promise<void>;expire:(at:string)=>Promise<number>;purgeCandidates:(at:string)=>Promise<string[]>;purge:(id:string)=>Promise<boolean>;cleanup:()=>Promise<number>};
function reminderMessage(candidate:RenewalCandidate,kind:30|7){const expiration=new Intl.DateTimeFormat("en-US",{dateStyle:"long",timeZone:"America/Chicago"}).format(new Date(candidate.expiresAt));return{to:candidate.contactEmail!,subject:`IDS Small Business Spotlight — ${kind} Days Until Listing Expiration`,text:kind===30?["Your IDS Small Business Spotlight listing for:","",candidate.businessName,"","is scheduled to expire on:","",expiration,"","Your listing is currently provided at no charge.","","If you would like your listing renewed for another six months, please reply to this email or contact IDS before the end of the grace period.","","Thank you for allowing IDS to support your business.","","Integrity Distribution Systems"].join("\n"):["This is a final reminder that your IDS Small Business Spotlight listing for:","",candidate.businessName,"","is scheduled to expire on:","",expiration,"","After expiration the listing will be removed from the public directory. IDS will retain it for a 30-day grace period before permanent deletion.","","If you would like another six-month listing term, please reply to this email or contact IDS.","","Integrity Distribution Systems"].join("\n")}}
export async function runFeaturedBusinessLifecycle(now=new Date(),dependencies?:LifecycleDependencies):Promise<LifecycleCounts>{const deps=dependencies??supabaseLifecycleDependencies(),counts:LifecycleCounts={reminders30Sent:0,reminders7Sent:0,expired:0,purged:0,imagesRemoved:0};for(const candidate of await deps.candidates()){const kind=reminderKind(candidate,now);if(!kind||!candidate.contactEmail)continue;try{await deps.send(reminderMessage(candidate,kind));await deps.markReminder(candidate.businessId,kind,now.toISOString());if(kind===30)counts.reminders30Sent++;else counts.reminders7Sent++}catch{console.error(`Featured business ${kind}-day renewal reminder failed`)}}counts.expired=await deps.expire(now.toISOString());for(const id of await deps.purgeCandidates(now.toISOString())){try{if(await deps.purge(id))counts.purged++}catch{console.error("Featured business purge failed")}}try{counts.imagesRemoved=await deps.cleanup()}catch{console.error("Featured business image cleanup failed")}return counts}
export function supabaseLifecycleDependencies():LifecycleDependencies{const client=getSupabaseServiceClient();return{async candidates(){const{data,error}=await client.from("featured_business_listing_contacts").select("featured_business_id,contact_email,reminder_30_sent_at,reminder_7_sent_at,featured_businesses!inner(business_name,listing_expires_at,is_archived)").not("featured_businesses.listing_expires_at","is",null).eq("featured_businesses.is_archived",false);if(error)throw error;return(data??[]).flatMap(row=>{const joined=Array.isArray(row.featured_businesses)?row.featured_businesses[0]:row.featured_businesses;if(!joined||!joined.listing_expires_at)return[];return[{businessId:String(row.featured_business_id),businessName:String(joined.business_name),expiresAt:String(joined.listing_expires_at),contactEmail:row.contact_email as string|null,reminder30SentAt:row.reminder_30_sent_at as string|null,reminder7SentAt:row.reminder_7_sent_at as string|null}]} )},send:sendServerEmail,async markReminder(id,kind,at){const column=kind===30?"reminder_30_sent_at":"reminder_7_sent_at";const{error}=await client.from("featured_business_listing_contacts").update({[column]:at,updated_at:at}).eq("featured_business_id",id).is(column,null);if(error)throw error},async expire(at){const{data,error}=await client.from("featured_businesses").update({is_public:false,is_featured:false,listing_expired_at:at,updated_at:at}).lte("listing_expires_at",at).is("listing_expired_at",null).select("id");if(error)throw error;return data?.length??0},async purgeCandidates(at){const{data,error}=await client.from("featured_businesses").select("id").lte("listing_grace_until",at).limit(500);if(error)throw error;return(data??[]).map(row=>String(row.id))},async purge(id){const{data,error}=await client.rpc("purge_expired_featured_business",{p_business_id:id});if(error)throw error;return Boolean(data)},cleanup:()=>processBusinessImageCleanup(100)}}
