import "server-only";
import { randomUUID } from "node:crypto";
import { getSupabaseServiceClient } from "@/lib/supabase";
import { sendServerEmail } from "@/lib/email";
import type { FeaturedBusinessRequest, FeaturedBusinessRequestInput } from "./request-types";
import type { ServiceArea } from "./location";
import { validateFeaturedBusinessRequest } from "./request-validation";

const columns="id,contact_name,contact_email,business_name,description,business_city,business_state,business_county,postal_code,operating_region,phone,phone_area_code,address,website_url,facebook_url,special_offer,additional_notes,logo_path,logo_content_type,status,admin_notes,more_info_message,more_info_requested_at,approved_business_id,approved_at,denied_at,consent_confirmed,created_at,updated_at,featured_business_request_service_areas(state_code,county_name,statewide)";
function toRequest(row:Record<string,unknown>):FeaturedBusinessRequest{const areas=Array.isArray(row.featured_business_request_service_areas)?row.featured_business_request_service_areas:[];return{id:String(row.id),contactName:String(row.contact_name),contactEmail:String(row.contact_email),businessName:String(row.business_name),description:String(row.description),businessCity:row.business_city as string|null,businessState:String(row.business_state),businessCounty:String(row.business_county),postalCode:row.postal_code as string|null,operatingRegion:row.operating_region as string|null,phone:row.phone as string|null,phoneAreaCode:row.phone_area_code as string|null,address:row.address as string|null,websiteUrl:row.website_url as string|null,facebookUrl:row.facebook_url as string|null,specialOffer:row.special_offer as string|null,additionalNotes:row.additional_notes as string|null,adminNotes:row.admin_notes as string|null,consentConfirmed:true,serviceAreas:areas.map(area=>{const item=area as Record<string,unknown>;return{stateCode:String(item.state_code),countyName:item.county_name as string|null,statewide:Boolean(item.statewide)}}),logoPath:String(row.logo_path),logoContentType:String(row.logo_content_type),status:row.status as FeaturedBusinessRequest["status"],moreInfoMessage:row.more_info_message as string|null,moreInfoRequestedAt:row.more_info_requested_at as string|null,approvedBusinessId:row.approved_business_id as string|null,approvedAt:row.approved_at as string|null,deniedAt:row.denied_at as string|null,createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
const dbRow=(value:FeaturedBusinessRequestInput)=>({contact_name:value.contactName,contact_email:value.contactEmail,business_name:value.businessName,description:value.description,business_city:value.businessCity,business_state:value.businessState,business_county:value.businessCounty,postal_code:value.postalCode,operating_region:value.operatingRegion,phone:value.phone,phone_area_code:value.phoneAreaCode,address:value.address,website_url:value.websiteUrl,facebook_url:value.facebookUrl,special_offer:value.specialOffer,additional_notes:value.additionalNotes,admin_notes:value.adminNotes,consent_confirmed:value.consentConfirmed,updated_at:new Date().toISOString()});
const areaRows=(id:string,areas:ServiceArea[])=>areas.map(area=>({request_id:id,state_code:area.stateCode,county_name:area.countyName,statewide:area.statewide}));
export async function listRequests(status?:string){let query=getSupabaseServiceClient().from("featured_business_requests").select(columns).order("created_at",{ascending:false});if(["pending","needs_info","approved","denied"].includes(status??""))query=query.eq("status",status!);const{data,error}=await query.limit(200);if(error)throw error;return(data??[]).map(item=>toRequest(item as Record<string,unknown>));}
export async function getRequest(id:string){const{data,error}=await getSupabaseServiceClient().from("featured_business_requests").select(columns).eq("id",id).maybeSingle();if(error)throw error;return data?toRequest(data as Record<string,unknown>):null;}
export async function createRequest(value:FeaturedBusinessRequestInput,logo:{path:string;originalName:string;contentType:string},fingerprint:string){const client=getSupabaseServiceClient();const id=logo.path.split("/")[1];const{error}=await client.from("featured_business_requests").insert({...dbRow(value),id,logo_path:logo.path,logo_original_filename:logo.originalName.slice(0,255),logo_content_type:logo.contentType,status:"pending",submission_fingerprint:fingerprint});if(error)throw error;const{error:areaError}=await client.from("featured_business_request_service_areas").insert(areaRows(id,value.serviceAreas));if(areaError){await client.from("featured_business_requests").delete().eq("id",id);throw areaError;}return id;}
export async function updateRequest(id:string,input:unknown){const current=await getRequest(id);if(!current)throw new Error("not_found");if(!["pending","needs_info"].includes(current.status))throw new Error("locked");const parsed=validateFeaturedBusinessRequest(input,true);if(!parsed.ok)return parsed;const client=getSupabaseServiceClient();const{error}=await client.from("featured_business_requests").update(dbRow(parsed.value)).eq("id",id);if(error)throw error;const{error:removeError}=await client.from("featured_business_request_service_areas").delete().eq("request_id",id);if(removeError)throw removeError;const{error:areaError}=await client.from("featured_business_request_service_areas").insert(areaRows(id,parsed.value.serviceAreas));if(areaError)throw areaError;return{ok:true as const,value:await getRequest(id)};}
export async function denyRequest(id:string,adminNotes?:string){const current=await getRequest(id);if(!current)throw new Error("not_found");if(current.approvedBusinessId)throw new Error("locked");const{error}=await getSupabaseServiceClient().from("featured_business_requests").update({status:"denied",denied_at:new Date().toISOString(),admin_notes:adminNotes?.trim().slice(0,2000)||current.adminNotes,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;}
export async function requestMoreInfo(id:string,message:string,sender=sendServerEmail){const current=await getRequest(id);if(!current)throw new Error("not_found");if(!["pending","needs_info"].includes(current.status))throw new Error("locked");const clean=message.trim().slice(0,3000);if(!clean)throw new Error("message_required");await sender({to:current.contactEmail,subject:"IDS Small Business Spotlight — More Information Requested",text:["Thank you for submitting your business for the IDS Small Business Spotlight.","","We need a little more information before we can complete our review.","","IDS REQUEST:",clean,"","Please reply to this email with the requested information.","","Thank you,","Integrity Distribution Systems"].join("\n")});const{error}=await getSupabaseServiceClient().from("featured_business_requests").update({status:"needs_info",more_info_message:clean,more_info_requested_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;}
export async function approveRequest(id:string){const client=getSupabaseServiceClient(),request=await getRequest(id);if(!request)throw new Error("not_found");if(request.approvedBusinessId)return request.approvedBusinessId;if(request.status==="denied")throw new Error("denied");const parsed=validateFeaturedBusinessRequest(request,true);if(!parsed.ok)throw new Error("invalid");const businessId=randomUUID(),extension=request.logoContentType==="image/jpeg"?"jpg":request.logoContentType.split("/")[1],path=`businesses/${businessId}/${businessId}.${extension}`;const{data:logo,error:downloadError}=await client.storage.from("featured-business-request-images").download(request.logoPath);if(downloadError||!logo)throw new Error("logo");const{error:uploadError}=await client.storage.from("featured-business-images").upload(path,await logo.arrayBuffer(),{contentType:request.logoContentType,upsert:false});if(uploadError)throw new Error("logo");const imageUrl=client.storage.from("featured-business-images").getPublicUrl(path).data.publicUrl;const{data,error}=await client.rpc("approve_featured_business_request",{p_request_id:id,p_business_id:businessId,p_image_path:path,p_image_url:imageUrl});if(error){await client.storage.from("featured-business-images").remove([path]);throw error;}const approvedId=String(data);if(approvedId!==businessId)await client.storage.from("featured-business-images").remove([path]);else await client.storage.from("featured-business-request-images").remove([request.logoPath]);return approvedId;}
