import "server-only";
import { getSupabaseCatalogClient, getSupabaseServiceClient } from "@/lib/supabase";
import { PUBLIC_BUSINESS_COLUMNS, toFeaturedBusiness } from "./public";
import type { FeaturedBusinessInput, FeaturedBusinessRenewalContact } from "./types";

const row = (value: FeaturedBusinessInput) => ({ business_name:value.businessName, description:value.description, operating_region:value.operatingRegion, image_alt:value.imageAlt, website_url:value.websiteUrl, facebook_url:value.facebookUrl, phone:value.phone, phone_area_code:value.phoneAreaCode,address:value.address,business_city:value.businessCity,business_state:value.businessState,business_county:value.businessCounty,postal_code:value.postalCode, referral_code:value.referralCode, special_offer:value.specialOffer, is_public:value.isPublic, is_featured:value.isFeatured, is_archived:value.isArchived, sort_order:value.sortOrder, updated_at:new Date().toISOString() });
export async function readPublicBusinesses(featuredOnly = false) { let query=getSupabaseCatalogClient().from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).order("sort_order").order("business_name"); if(featuredOnly) query=query.eq("is_featured",true).limit(1);else query=query.limit(500); const {data,error}=await query; if(error) throw error; return (data??[]).map(item=>toFeaturedBusiness(item as Record<string,unknown>)); }
export async function readAdminBusinesses() { const {data,error}=await getSupabaseServiceClient().from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).order("is_archived").order("sort_order").order("business_name"); if(error) throw error; return (data??[]).map(item=>toFeaturedBusiness(item as Record<string,unknown>)); }
export async function readAdminRenewalContacts(){const{data,error}=await getSupabaseServiceClient().from("featured_business_listing_contacts").select("featured_business_id,contact_name,contact_email,reminder_30_sent_at,reminder_7_sent_at");if(error)throw error;return(data??[]).map(row=>({featuredBusinessId:String(row.featured_business_id),contactName:row.contact_name as string|null,contactEmail:row.contact_email as string|null,reminder30SentAt:row.reminder_30_sent_at as string|null,reminder7SentAt:row.reminder_7_sent_at as string|null}) satisfies FeaturedBusinessRenewalContact)}
export function validateRenewalContact(input:unknown){const body=(input&&typeof input==="object"?input:{}) as Record<string,unknown>,contactName=typeof body.renewalContactName==="string"?body.renewalContactName.trim().slice(0,121):"",contactEmail=typeof body.renewalContactEmail==="string"?body.renewalContactEmail.trim().toLowerCase().slice(0,255):"";const errors:Record<string,string>={};if(contactName.length>120)errors.renewalContactName="Renewal contact name must be 120 characters or fewer.";if(contactEmail&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contactEmail))errors.renewalContactEmail="Enter a valid renewal contact email.";return Object.keys(errors).length?{ok:false as const,errors}:{ok:true as const,value:{contactName:contactName||null,contactEmail:contactEmail||null}}}
export async function saveBusiness(value:FeaturedBusinessInput,id?:string,renewal?:{contactName:string|null;contactEmail:string|null}) { const client=getSupabaseServiceClient(); let savedId=id; if(id){const {error}=await client.from("featured_businesses").update({...row(value),is_featured:false}).eq("id",id);if(error)throw error;}else{if(!value.businessState||!value.businessCounty||!value.serviceAreas.length)throw new Error("New businesses require structured location data.");const {data,error}=await client.from("featured_businesses").insert({...row(value),is_featured:false}).select("id").single();if(error)throw error;savedId=data.id;} if(!savedId)throw new Error("Business was not saved.");const{error:deleteAreasError}=await client.from("featured_business_service_areas").delete().eq("featured_business_id",savedId);if(deleteAreasError)throw deleteAreasError;if(value.serviceAreas.length){const{error:areaError}=await client.from("featured_business_service_areas").insert(value.serviceAreas.map(area=>({featured_business_id:savedId,state_code:area.stateCode,county_name:area.countyName,statewide:area.statewide})));if(areaError)throw areaError;}if(renewal){const{error:contactError}=await client.from("featured_business_listing_contacts").upsert({featured_business_id:savedId,contact_name:renewal.contactName,contact_email:renewal.contactEmail,updated_at:new Date().toISOString()},{onConflict:"featured_business_id"});if(contactError)throw contactError;} if(value.isFeatured){const {error}=await client.rpc("set_featured_business",{p_business_id:savedId});if(error)throw error;} const {data,error}=await client.from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).eq("id",savedId).single();if(error)throw error;return toFeaturedBusiness(data as Record<string,unknown>); }
export async function renewBusiness(id:string){const client=getSupabaseServiceClient();const{error}=await client.rpc("renew_featured_business_listing",{p_business_id:id});if(error)throw error;const{data,error:readError}=await client.from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).eq("id",id).single();if(readError)throw readError;return toFeaturedBusiness(data as Record<string,unknown>)}
export async function deleteBusiness(id:string){const client=getSupabaseServiceClient();const{data,error}=await client.rpc("delete_featured_business_with_cleanup",{p_business_id:id});if(error)throw error;if(!data)throw new Error("Business not found.");await processBusinessImageCleanup(20)}
export async function processBusinessImageCleanup(limit=100){const client=getSupabaseServiceClient();const{data,error}=await client.from("featured_business_image_cleanup_queue").select("id,image_path").order("created_at").limit(limit);if(error)throw error;let removed=0;for(const item of data??[]){const{error:removeError}=await client.storage.from("featured-business-images").remove([item.image_path]);if(removeError){await client.from("featured_business_image_cleanup_queue").update({last_attempted_at:new Date().toISOString()}).eq("id",item.id);continue}const{error:deleteError}=await client.from("featured_business_image_cleanup_queue").delete().eq("id",item.id);if(!deleteError)removed++}return removed}
