import "server-only";
import { getSupabaseCatalogClient, getSupabaseServiceClient } from "@/lib/supabase";
import { PUBLIC_BUSINESS_COLUMNS, toFeaturedBusiness } from "./public";
import type { FeaturedBusinessInput } from "./types";

const row = (value: FeaturedBusinessInput) => ({ business_name:value.businessName, description:value.description, operating_region:value.operatingRegion, image_alt:value.imageAlt, website_url:value.websiteUrl, facebook_url:value.facebookUrl, phone:value.phone, address:value.address, referral_code:value.referralCode, special_offer:value.specialOffer, is_public:value.isPublic, is_featured:value.isFeatured, is_archived:value.isArchived, sort_order:value.sortOrder, updated_at:new Date().toISOString() });
export async function readPublicBusinesses(featuredOnly = false) { let query=getSupabaseCatalogClient().from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).order("sort_order").order("business_name"); if(featuredOnly) query=query.eq("is_featured",true).limit(1); const {data,error}=await query; if(error) throw error; return (data??[]).map(item=>toFeaturedBusiness(item as Record<string,unknown>)); }
export async function readAdminBusinesses() { const {data,error}=await getSupabaseServiceClient().from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).order("is_archived").order("sort_order").order("business_name"); if(error) throw error; return (data??[]).map(item=>toFeaturedBusiness(item as Record<string,unknown>)); }
export async function saveBusiness(value:FeaturedBusinessInput,id?:string) { const client=getSupabaseServiceClient(); let savedId=id; if(id){const {error}=await client.from("featured_businesses").update({...row(value),is_featured:false}).eq("id",id);if(error)throw error;}else{const {data,error}=await client.from("featured_businesses").insert({...row(value),is_featured:false}).select("id").single();if(error)throw error;savedId=data.id;} if(value.isFeatured){const {error}=await client.rpc("set_featured_business",{p_business_id:savedId});if(error)throw error;} const {data,error}=await client.from("featured_businesses").select(PUBLIC_BUSINESS_COLUMNS).eq("id",savedId).single();if(error)throw error;return toFeaturedBusiness(data as Record<string,unknown>); }
export async function deleteBusiness(id:string){const client=getSupabaseServiceClient();const{data}=await client.from("featured_businesses").select("image_path").eq("id",id).maybeSingle();const{error}=await client.from("featured_businesses").delete().eq("id",id);if(error)throw error;if(data?.image_path)await client.storage.from("featured-business-images").remove([data.image_path]);}
