// Real local browser controls. Mobile dimensions are emulation, not a device test.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const [suffix,exe]=process.argv.slice(2);assert.match(suffix,/^[a-z0-9_]{1,26}$/);assert.ok(fs.existsSync(exe));
const out='docs/review/installation-readiness',config=JSON.parse(fs.readFileSync(`node_modules/.cache/ids-installation-test/${suffix}-services.json`,'utf8')),record=JSON.parse(fs.readFileSync(`${out}/${suffix}-app-record.json`,'utf8'));
const base=`http://127.0.0.1:${config.appPort}`,commands=[];
const run=(...args)=>{const result=execFileSync(exe,['--session','ids-installation-complete',...args],{encoding:'utf8',windowsHide:true,timeout:45000}).trim();commands.push({command:args[0],passed:true});return result;};
const ev=code=>JSON.parse(run('eval',code)),wait=code=>run('wait','--fn',code),screen=name=>run('screenshot',path.join(out,`${suffix}-${name}.png`));
run('errors','--clear');run('open',base+'/professional-installation/'+record.token);wait("document.body.innerText.includes('Saved pricing')");ev("(()=>{document.querySelector('details summary').click();return true})()");
const portalText=ev('document.body.innerText');assert.ok(portalText.includes('Cash actually returned: $25.00'));assert.ok(portalText.includes('Receipt recording correction: $675.00'));assert.ok(portalText.includes('90 recorded minutes'));
for(const [name,width,height] of [['customer-desktop',1440,1000],['customer-mobile',390,844]]){run('set','viewport',String(width),String(height));screen(name);assert.equal(ev('document.documentElement.scrollWidth<=innerWidth'),true);}
run('open',base+'/admin/installations');wait("document.body.innerText.includes('SYNTHETIC HTTP APP REVIEW') || !!document.querySelector('input[name=password]')");
if(ev("!!document.querySelector('input[name=password]')")){run('fill','input[name=password]',config.adminPassword);run('click','form button');wait("document.body.innerText.includes('SYNTHETIC HTTP APP REVIEW')");}
const card="Array.from(document.querySelectorAll('article')).find(a=>a.innerText.includes('SYNTHETIC HTTP APP REVIEW'))";
ev(`(()=>{const a=${card};a.scrollIntoView({block:'start'});return true})()`);screen('admin-mobile');assert.equal(ev('document.documentElement.scrollWidth<=innerWidth'),true);
ev(`(()=>{const a=${card};for(const d of a.querySelectorAll('details'))if(d.querySelector('summary')?.textContent.includes('Payment, cash corrections')&&!d.open)d.querySelector('summary').click();return true})()`);
const history=ev(`(${card}).innerText`);assert.ok(history.includes('cash'));assert.ok(history.includes('90'));assert.ok(history.includes('Cash actually returned'));run('set','viewport','1440','1000');ev(`(()=>{(${card}).scrollIntoView({block:'start'});return true})()`);screen('admin-desktop');
// A fresh request is submitted through the rendered final intake form.
run('open',base+'/professional-installation');wait("document.querySelector('select[name=startAt]')?.options.length>1");
for(const [name,value] of [['name','SYNTHETIC FINAL BROWSER'],['email','final-browser@example.invalid'],['phone','000-000-0000'],['address','Synthetic final browser property']])run('fill',`input[name=${name}]`,value);
run('select','select[name=internetAvailability]','yes');for(const name of ['groundingAcknowledged','responsibilitiesAcknowledged','termsAcknowledged'])run('check',`input[name=${name}]`);
const slot=ev("Array.from(document.querySelector('select[name=startAt]').options).filter(o=>o.value&&!o.disabled).at(-1).value");run('select','select[name=startAt]',slot);run('click','form button');wait("location.pathname!=='/professional-installation'");wait("document.body.innerText.includes('Request status: requested')");
const newToken=ev("location.pathname.split('/').pop()"),response=await fetch(base+'/api/installations/'+newToken),saved=await response.json();assert.equal(response.status,200);assert.equal(saved.installation.customer_name,'SYNTHETIC FINAL BROWSER');assert.equal(saved.installation.status,'requested');assert.equal(saved.payments.length,0);
run('set','viewport','390','844');screen('intake-saved-mobile');assert.equal(ev('document.documentElement.scrollWidth<=innerWidth'),true);assert.equal(run('errors'),'');
const result={passed:true,database:config.database,databaseOid:config.databaseOid,existingInstallationId:record.installationId,browserCreatedInstallationId:saved.installation.id,desktop:[1440,1000],mobileEmulation:[390,844],checks:['final customer/admin balances and receipt/correction/actual-return/work history rendered from real persistence','final desktop/mobile portal and admin without horizontal overflow','fresh final browser intake persisted as requested with zero payments','zero browser page errors'],commands:commands.length};fs.writeFileSync(`${out}/${suffix}-browser.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
