/* eslint-disable @typescript-eslint/no-explicit-any */
// Actual application operations + real PostgREST/PG. Stripe API responses and
// signed deliveries here are CONTROLLED, never actual Stripe-delivered evidence.
import fs from 'node:fs';import assert from 'node:assert/strict';import * as crypto from 'node:crypto';import * as util from 'node:util';
import Stripe from 'stripe';import {NextResponse} from 'next/server';import {createClient} from '@supabase/supabase-js';
import {loadInstallationModule as load} from '../../tests/helpers/installation-module';import {processorFixture} from '../../tests/helpers/installation-stripe-fixtures';
import * as accounting from '../../lib/installations/accounting';import * as adminPolicy from '../../lib/installations/admin-policy';import * as stripePolicy from '../../lib/installations/stripe-policy';import * as cashValidation from '../../lib/installations/cash-validation';import * as policy from '../../lib/installations/policy';import * as webhookPolicy from '../../lib/stripe/webhook-policy';
import {StripeConfigurationError} from '../../lib/stripe/config-values';
async function main(){
 const suffix=process.argv[2];assert.match(suffix,/^[a-z0-9_]{1,26}$/);const config=JSON.parse(fs.readFileSync(`node_modules/.cache/ids-installation-test/${suffix}-services.json`,'utf8')),manifest=JSON.parse(fs.readFileSync(`docs/review/installation-readiness/db-${suffix}-run.json`,'utf8'));assert.equal(config.database,manifest.database);assert.equal(config.runId,manifest.runId);assert.equal(config.databaseOid,manifest.databaseOid);
 const client=createClient(`http://127.0.0.1:${config.proxyPort}`,config.serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});let failRpc='';
 const db={from:client.from.bind(client),rpc:async(name:string,args:any)=>{if(failRpc===name){failRpc='';return {data:null,error:{message:'CONTROLLED persistence failure after processor operation'}};}return client.rpc(name,args);}};
 const query=async(name:string,args:any)=>{const r=await client.rpc(name,args);if(r.error)throw r.error;return r.data;};
 const state=(id:string)=>query('ids_installation_admin_state',{p_id:id});
 const sessions=new Map<string,any>(),intents=new Map<string,any>(),charges=new Map<string,any>(),refunds=new Map<string,any>(),keys=new Map<string,{request:string;object:any}>();let checkoutCreates=0,refundCreates=0,enabled=true;
 const list=(values:any[])=>({data:values,autoPagingToArray:async()=>structuredClone(values)});
 const sdk={webhooks:Stripe.webhooks,checkout:{sessions:{
  list:(args:any)=>list([...sessions.values()].filter(s=>!args.payment_intent||s.payment_intent===args.payment_intent)),retrieve:async(id:string)=>structuredClone(sessions.get(id)),expire:async(id:string)=>{sessions.get(id).status='expired';return structuredClone(sessions.get(id));},
  create:async(request:any,{idempotencyKey}:any)=>{const old=keys.get(idempotencyKey);if(old){assert.equal(old.request,JSON.stringify(request));return structuredClone(old.object);}checkoutCreates++;const s={...processorFixture(request.line_items[0].price_data.unit_amount).session,id:'cs_test_controlled_'+crypto.randomUUID(),created:Math.floor(Date.now()/1000),expires_at:request.expires_at,metadata:request.metadata,client_reference_id:request.client_reference_id,status:'open',payment_status:'unpaid',payment_intent:null,url:'http://localhost/controlled-checkout'};sessions.set(s.id,s);keys.set(idempotencyKey,{request:JSON.stringify(request),object:s});return structuredClone(s);}
 }},paymentIntents:{retrieve:async(id:string)=>structuredClone(intents.get(id))},charges:{retrieve:async(id:string)=>structuredClone(charges.get(id))},refunds:{
  list:(args:any)=>list([...refunds.values()].filter(r=>(!args.charge||r.charge===args.charge)&&(!args.payment_intent||r.payment_intent===args.payment_intent))),retrieve:async(id:string)=>structuredClone(refunds.get(id)),
  create:async(request:any,{idempotencyKey}:any)=>{const old=keys.get(idempotencyKey);if(old){assert.equal(old.request,JSON.stringify(request));return structuredClone(old.object);}refundCreates++;const intent=intents.get(request.payment_intent),r={...processorFixture().refund(request.amount,'pending','re_controlled_'+crypto.randomUUID()),payment_intent:intent.id,charge:intent.latest_charge,metadata:request.metadata,created:Math.floor(Date.now()/1000)};refunds.set(r.id,r);keys.set(idempotencyKey,{request:JSON.stringify(request),object:r});return structuredClone(r);}
 }};
 const controls={requireInstallationOnlinePayments:()=>{if(!enabled)throw Error('installation_online_payments_disabled');},requireInstallationCashRecording:()=>{},installationControls:()=>({cashRecordingEnabled:true})};
 // Normalize only VM realm prototypes; compare the complete JSON payload.
 const vmUtil={...util,isDeepStrictEqual:(a:unknown,b:unknown)=>util.isDeepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)))};
 const common={'node:crypto':crypto,'node:util':vmUtil,'@/lib/supabase':{getSupabaseServiceClient:()=>db},'@/lib/reviews/admin-auth':{isReviewAdmin:async()=>true},'./accounting':accounting,'./admin-policy':adminPolicy,'./stripe-policy':stripePolicy,'./cash-validation':cashValidation,'./policy':policy,'./controls':controls};
 const ledger=load<typeof import('../../lib/installations/ledger')>('lib/installations/ledger.ts',common);const modules={...common,'./ledger':ledger};
 const operations=load<typeof import('../../lib/installations/operations')>('lib/installations/operations.ts',modules),cash=load<typeof import('../../lib/installations/cash')>('lib/installations/cash.ts',modules);
 const stripe=load<typeof import('../../lib/installations/stripe')>('lib/installations/stripe.ts',{...modules,'@/lib/stripe/config':{getStripeMode:()=> 'test',getStripeConfiguration:()=>({appBaseUrl:'http://localhost'})},'@/lib/stripe/server':{getStripeServerClient:()=>sdk}});
 const slotRows=await query('ids_list_installation_slots',{p_start:new Date(Date.now()+22*86400000).toISOString().slice(0,10),p_end:new Date(Date.now()+41*86400000).toISOString().slice(0,10)});assert.ok(slotRows.length);
 const payload={name:'SYNTHETIC PROCESSOR APP',email:'processor-app@example.invalid',phone:'000-000-0000',address:'SYNTHETIC LOCAL PROPERTY',internetAvailability:'yes',undergroundRequested:false,estimatedUndergroundFeet:0,startAt:new Date(slotRows.at(-2).start_at).toISOString(),groundingAcknowledged:true,responsibilitiesAcknowledged:true,termsAcknowledged:true,undergroundAcknowledged:false,cashRequested:false,idempotencyKey:crypto.randomUUID()};
 const i=await query('ids_create_installation',{p_payload:payload});await operations.executeInstallationAdmin(i.id,{action:'approve',operationKey:crypto.randomUUID()});
 failRpc='ids_attach_installation_checkout';await assert.rejects(stripe.createInstallationCheckout(i.public_token,'deposit'));assert.equal(checkoutCreates,1);let s=await state(i.id);assert.equal(s.payments.length,1);assert.equal(s.payments[0].stripe_session_id,null);
 await stripe.createInstallationCheckout(i.public_token,'deposit');assert.equal(checkoutCreates,1);s=await state(i.id);let first=s.payments[0];assert.ok(first.stripe_session_id);await stripe.createInstallationCheckout(i.public_token,'deposit');assert.equal(checkoutCreates,1);
 sessions.get(first.stripe_session_id).status='expired';await stripe.createInstallationCheckout(i.public_token,'deposit');assert.equal(checkoutCreates,2);s=await state(i.id);first=s.payments.find((p:any)=>p.processor_state==='open');assert.equal(s.payments.find((p:any)=>p.id!==first.id).status,'cancelled');
 const pay=(sessionId:string)=>{const session=sessions.get(sessionId),f=processorFixture(session.amount_total,{id:session.metadata.payment_id,installation_id:session.metadata.installation_id,stripe_session_id:session.id,stripe_payment_intent_id:'pi_controlled_'+crypto.randomUUID(),stripe_charge_id:'ch_controlled_'+crypto.randomUUID()});session.status='complete';session.payment_status='paid';session.payment_intent=f.intent.id;f.intent.metadata=session.metadata;f.charge.metadata=session.metadata;intents.set(f.intent.id,f.intent);charges.set(f.charge.id,f.charge);return f;};
 pay(first.stripe_session_id);enabled=false;await stripe.reconcileInstallationPayment(first.id);s=await state(i.id);assert.equal(accounting.installationBalance(s.installation.pricing_snapshot,s.adjustments,s.payments,s.corrections,s.cashRefunds).balanceDueCents,75000);enabled=true;
 await stripe.createInstallationCheckout(i.public_token,'balance');s=await state(i.id);const remaining=s.payments.find((p:any)=>p.processor_state==='open');assert.equal(remaining.amount_cents,75000);
 // Existing online checkout can complete after cash. Preserve both actual
 // receipts as customer credit; never issue an automatic processor refund.
 await cash.recordInstallationCash(i.id,{operationKey:crypto.randomUUID(),amountDollars:'750.00',receivedAt:new Date().toISOString(),reference:'SYNTHETIC concurrent cash',notes:'Synthetic only',confirmOverpayment:false});
 pay(remaining.stripe_session_id);await stripe.reconcileInstallationPayment(remaining.id);s=await state(i.id);let balance=accounting.installationBalance(s.installation.pricing_snapshot,s.adjustments,s.payments,s.corrections,s.cashRefunds);assert.equal(balance.customerCreditCents,75000);assert.equal(refundCreates,0);
 await stripe.reconcileInstallationPayment(first.id);s=await state(i.id);assert.equal(s.installation.payment_status,'paid');
 const refundBody={operationKey:crypto.randomUUID(),originalPaymentId:remaining.id,amountDollars:'50.00',reason:'SYNTHETIC authorized test refund',reference:'CONTROLLED'};
 failRpc='ids_reconcile_installation_stripe';await assert.rejects(stripe.requestInstallationStripeRefund(i.id,refundBody));assert.equal(refundCreates,1);s=await state(i.id);assert.equal(s.payments.find((p:any)=>p.id===remaining.id).refunded_cents,0);
 const pending=await stripe.requestInstallationStripeRefund(i.id,refundBody);assert.equal(pending.processorStatus,'pending');assert.equal(refundCreates,1);
 const refund=refunds.get(pending.stripeRefundId);refund.status='succeeded';refund.balance_transaction={id:'txn_controlled_success',created:Math.floor(Date.now()/1000)};charges.get(refund.charge).amount_refunded=refund.amount;
 const secret='whsec_controlled_local_only',forbidden=()=>{throw Error('Unexpected order/demo/email dispatch');};
 const routeModules:Record<string,unknown>={'next/server':{NextResponse},'@/lib/installations/stripe':stripe,'@/lib/stripe/server':{getStripeServerClient:()=>sdk},'@/lib/stripe/config':{getStripeMode:()=> 'test',getStripeWebhookSecret:()=>secret,StripeConfigurationError},'@/lib/stripe/webhook-policy':webhookPolicy};
 for(const name of ['@/lib/checkout/order-repository','@/lib/stripe/ach-webhook-policy','@/lib/stripe/wire-webhook-policy','@/lib/stripe/payment-intent-resolution','@/lib/notifications/payment-notifications','@/lib/notifications/notification-keys','@/lib/demo-party/server','@/lib/demo-party/stripe-policy','@/lib/demo-party/security','@/lib/demo-scheduling/server','@/lib/demo-scheduling/notifications'])routeModules[name]=new Proxy({},{get:()=>forbidden});
 const route=load<typeof import('../../app/api/stripe/webhook/route')>('app/api/stripe/webhook/route.ts',routeModules);
 const event={id:'evt_controlled_signed_'+crypto.randomUUID(),object:'event',type:'refund.updated',livemode:false,created:Math.floor(Date.now()/1000),data:{object:refund}};
 const body=JSON.stringify(event),signature=Stripe.webhooks.generateTestHeaderString({payload:body,secret}),request=(sig=signature)=>new Request('http://localhost/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':sig},body});
 assert.equal((await route.POST(request('invalid'))).status,400);failRpc='ids_reconcile_installation_stripe';assert.equal((await route.POST(request())).status,503);assert.equal((await route.POST(request())).status,200);assert.equal((await route.POST(request())).status,200);
 s=await state(i.id);balance=accounting.installationBalance(s.installation.pricing_snapshot,s.adjustments,s.payments,s.corrections,s.cashRefunds);assert.equal(balance.completedRefundsCents,5000);assert.equal(balance.customerCreditCents,70000);assert.equal(s.payments.filter((p:any)=>p.stripe_refund_id===refund.id).length,1);
 assert.equal((await stripe.requestInstallationStripeRefund(i.id,refundBody)).processorStatus,'succeeded');assert.equal(refundCreates,1);await assert.rejects(stripe.requestInstallationStripeRefund(i.id,{...refundBody,amountDollars:'51.00'}),/conflict/);
 const results={passed:true,database:config.database,databaseOid:config.databaseOid,installationId:i.id,evidence:'Real application operations/PostgREST/PostgreSQL; controlled processor API and locally signed webhook payloads; NOT Stripe-delivered events',checks:['checkout persistence failure recovers original session without second create; expired session replaced','deposit and balance amounts use actual ledger; off flag preserves reconciliation','cash versus open online checkout retains both receipts as credit; old deposit reconciliation cannot downgrade settlement; no automatic money movement','refund persistence failure recovers same reference/key; pending not money returned; signed invalid/retry/duplicate events; partial success and unchanged original remaining credit'],checkoutCreates,refundCreates,emailsDispatched:0};
 fs.writeFileSync(`docs/review/installation-readiness/${suffix}-processor-app.json`,JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
