/* eslint-disable @typescript-eslint/no-explicit-any */
// REAL PostgreSQL persistence/concurrency, CONTROLLED Stripe object evidence.
import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';
import {PsqlConnection,literal,jsonLiteral} from './psql';import {adminState,adminArgs,adminSql} from './workflow-tests';
import {installationBalance} from '../../lib/installations/accounting';
import {installationStripeProjection,type InstallationStripePayment} from '../../lib/installations/stripe-policy';
import {processorFixture} from '../../tests/helpers/installation-stripe-fixtures';
import type Stripe from 'stripe';
const rpc=(name:string,args:Record<string,any>)=>`select public.${name}(${Object.entries(args).map(([k,v])=>`${k}=>${v===null?'null':typeof v==='object'?jsonLiteral(v):typeof v==='number'||typeof v==='boolean'?String(v):literal(v)}`).join(',')})`;
export async function awaitBlocked(observer:PsqlConnection,blockedPid:number,blockerPid:number){
 const deadline=Date.now()+2500;while(Date.now()<deadline){if(await observer.query(`select ${blockerPid}=any(pg_blocking_pids(${blockedPid}))`)==='t')return;await new Promise(r=>setTimeout(r,20));}throw new Error('Competing database command never demonstrably blocked');
}
export async function runStripeDatabaseTests(connect:()=>PsqlConnection,verify:(c:PsqlConnection)=>Promise<void>){
 const a=connect(),b=connect();await verify(a);await verify(b);for(const c of[a,b]){await c.query("set statement_timeout='15s'");await c.query("set lock_timeout='4s'");await c.query('set role service_role');}
 const aPid=Number(await a.query('select pg_backend_pid()')),bPid=Number(await b.query('select pg_backend_pid()')),checks:string[]=[];
 const slots=await a.json<{start_at:string}[]>("select json_agg(s) from public.ids_list_installation_slots((now() at time zone 'America/Chicago')::date+21,(now() at time zone 'America/Chicago')::date+41) s");let slotAt=0;
 const create=async()=>{const payload={name:'SYNTHETIC PROCESSOR DATABASE',email:'processor-test@example.invalid',phone:'000-000-0000',address:'SYNTHETIC LOCAL PROPERTY',internetAvailability:'yes',undergroundRequested:false,estimatedUndergroundFeet:0,startAt:new Date(slots[slotAt++].start_at).toISOString(),groundingAcknowledged:true,responsibilitiesAcknowledged:true,termsAcknowledged:true,undergroundAcknowledged:false,cashRequested:false,idempotencyKey:randomUUID()};const i=await a.json<{id:string}>(rpc('ids_create_installation',{p_payload:payload}));await a.json(adminSql(await adminArgs(a,i.id,{action:'approve',operationKey:randomUUID()})));return i.id;};
 const balance=(s:Awaited<ReturnType<typeof adminState>>)=>installationBalance(s.installation.pricing_snapshot,s.adjustments,s.payments,s.corrections,s.cashRefunds);
 const reserve=async(id:string,amount=25000,purpose='deposit')=>{const s=await adminState(a,id),paymentId=randomUUID(),request={mode:'payment',metadata:{ids_kind:'professional_installation',installation_id:id,payment_id:paymentId,purpose},line_items:[{price_data:{unit_amount:amount,currency:'usd'}}]};return a.json<InstallationStripePayment>(rpc('ids_reserve_installation_checkout',{p_id:id,p_payment_id:paymentId,p_purpose:purpose,p_amount:amount,p_request:request,p_expected_ledger:s.ledger,p_balance:balance(s)}));};
 const expectFailure=async(c:PsqlConnection,sql:string,pattern:RegExp)=>{await c.query('savepoint fail');const r=await c.raw(sql);await c.query('rollback to savepoint fail');assert.notEqual(r.code,'00000');assert.match(r.message,pattern);};
 const id=await create();const p=await reserve(id);const reserved=structuredClone(p);assert.equal((await reserve(id)).id,p.id);
 const f=processorFixture(p.amount_cents,{...p,stripe_session_id:'cs_test_db_'+p.id,stripe_payment_intent_id:'pi_db_'+p.id,stripe_charge_id:'ch_db_'+p.id});
 await a.query('begin');await expectFailure(a,rpc('ids_attach_installation_checkout',{p_id:id,p_payment_id:p.id,p_session_id:'cs_live_forbidden',p_expires:new Date().toISOString()}),/invalid_checkout_link/);await a.query('rollback');
 await a.json(rpc('ids_attach_installation_checkout',{p_id:id,p_payment_id:p.id,p_session_id:f.session.id,p_expires:new Date(f.session.expires_at*1000).toISOString()}));
 assert.deepEqual((await reserve(id)).processor_request,reserved.processor_request);
 checks.push('durable checkout reservation before processor call, one active record, original request/key retained, test-mode session attachment only');
 const args=async(refunds:Stripe.Refund[]=[],eventId='evt_controlled_'+randomUUID(),eventCreated=Math.floor(Date.now()/1000))=>{const s=await adminState(a,id),row=s.payments.find(x=>x.id===p.id) as InstallationStripePayment,projection=installationStripeProjection(s,row,f.session,f.intent,f.charge,refunds,eventCreated);return {p_id:id,p_payment_id:p.id,p_expected_ledger:s.ledger,p_balance_before:balance(s),p_balance_after:projection.balance,p_evidence:projection.evidence,p_refunds:projection.refundRows,p_event:{id:eventId,type:'controlled.local.processor',objectId:f.session.id,created:eventCreated,receivedAt:new Date().toISOString(),hash:createHash('sha256').update(eventId).digest('hex')}};};
 const settle=async(refunds:Stripe.Refund[]=[],eventId?:string,eventCreated?:number)=>{const values=await args(refunds,eventId,eventCreated);return a.json<any>(rpc('ids_reconcile_installation_stripe',values));};
 const first=await args(),before=await adminState(a,id);
 await a.query('reset role');await a.query('begin');await a.query("alter table public.installation_audit_events add constraint processor_test_fail check(event_type<>'stripe_reconciled') not valid");await a.query('set local role service_role');
 await expectFailure(a,rpc('ids_reconcile_installation_stripe',first),/processor_test_fail/);assert.deepEqual(await adminState(a,id),before);assert.equal(await a.query(`select count(*) from public.installation_processor_events where installation_id=${literal(id)}`),'0');await a.query('rollback');await a.query('set role service_role');
 for(const mutation of [{observedAt:null},{paid:'true'},{refundedCents:'0'},{paymentOccurredAt:'infinity'},{livemode:true},{amountCents:1},{sessionId:'cs_test_wrong'}]){await a.query('begin');await expectFailure(a,rpc('ids_reconcile_installation_stripe',{...first,p_evidence:{...first.p_evidence,...mutation}}),/invalid_processor_evidence|processor_payment_mismatch/);await a.query('rollback');}
 await a.json(rpc('ids_reconcile_installation_stripe',first));assert.equal((await a.json<any>(rpc('ids_reconcile_installation_stripe',first))).replayed,true);
 await a.query('begin');await expectFailure(a,rpc('ids_reconcile_installation_stripe',{...first,p_event:{...first.p_event,hash:'a'.repeat(64)}}),/processor_event_conflict/);await a.query('rollback');await settle();
 let state=await adminState(a,id);assert.equal(balance(state).netPaidCents,25000);assert.equal(Date.parse(state.payments[0].paid_at!),f.charge.created*1000);
 checks.push('atomic payment/financial/event/audit rollback; identical event replay, conflicting event rejection, separate duplicate event without double credit, forged/null evidence rejected, occurrence distinct from arrival');
 const makeRefundArgs=async(amount:number,key=randomUUID())=>{const s=await adminState(a,id),refundId=randomUUID(),payload={installationId:id,originalPaymentId:p.id,operationKey:key,amountCents:amount,reason:'SYNTHETIC refund authorization',reference:null,actor:'IDS shared administrator'},request={payment_intent:f.intent.id,amount,metadata:{ids_kind:'professional_installation',installation_id:id,original_payment_id:p.id,refund_operation_key:key}};
  return{p_id:id,p_refund_id:refundId,p_original_id:p.id,p_key:key,p_payload:payload,p_request:request,p_expected_ledger:s.ledger,p_balance_before:balance(s),p_balance_after:installationBalance(s.installation.pricing_snapshot,s.adjustments,[...s.payments,{id:refundId,original_payment_id:p.id,purpose:'refund',method:'stripe',status:'pending',amount_cents:amount,refunded_cents:0,paid_at:null}],s.corrections,s.cashRefunds)};};
 const refundArgs=await makeRefundArgs(5000);const reservation=await a.json<InstallationStripePayment>(rpc('ids_reserve_installation_refund',refundArgs));assert.equal((await a.json<InstallationStripePayment>(rpc('ids_reserve_installation_refund',refundArgs))).id,reservation.id);
 state=await adminState(a,id);assert.equal(balance(state).pendingRefundsCents,5000);assert.equal(balance(state).netPaidCents,25000);
 const refund=f.refund(5000,'pending','re_db_'+p.id);refund.metadata=refundArgs.p_request.metadata;
 await settle([refund]);assert.equal(balance(await adminState(a,id)).netPaidCents,25000);
 refund.status='succeeded';refund.balance_transaction={id:'txn_db_synthetic',created:f.charge.created+120} as Stripe.BalanceTransaction;f.charge.amount_refunded=5000;await settle([refund]);state=await adminState(a,id);assert.equal(balance(state).netPaidCents,20000);assert.equal(balance(state).pendingRefundsCents,0);assert.equal(state.payments.filter(r=>r.purpose==='refund').length,1);
 const paidRefund=structuredClone(refund);refund.status='pending';await settle([refund],undefined,Math.floor(Date.now()/1000)-100);assert.equal(balance(await adminState(a,id)).netPaidCents,20000);refund.status='succeeded';
 const failed=f.refund(1000,'failed','re_failed_'+p.id),cancelled=f.refund(1000,'canceled','re_cancelled_'+p.id);await settle([paidRefund,failed,cancelled]);assert.equal(balance(await adminState(a,id)).netPaidCents,20000);
 checks.push('authorized refund reserves pending without returning money; partial success retains $200 of $250; stable processor reference; old pending notification cannot regress success; failed/canceled evidence does not reduce paid funds');
 const r1=await makeRefundArgs(20000),r2=await makeRefundArgs(20000);await a.query('begin');await b.query('begin');await a.query(rpc('ids_reserve_installation_refund',r1));const racing=b.raw(rpc('ids_reserve_installation_refund',r2));await awaitBlocked(a,bPid,aPid);await a.query('commit');assert.match((await racing).message,/installation_ledger_changed|refund_exceeds_eligible/);await b.query('rollback');
 const r3=await makeRefundArgs(1);await a.query('begin');await expectFailure(a,rpc('ids_reserve_installation_refund',r3),/refund_exceeds_eligible/);await a.query('rollback');checks.push('observed two-backend blocking and concurrent over-refund rejection including pending reservations');
 // Expired sessions free the single active reservation; unpaid evidence cannot credit money.
 const expiredId=await create(),ep=await reserve(expiredId),ef=processorFixture(ep.amount_cents,{...ep,stripe_session_id:'cs_test_expired_'+ep.id,stripe_payment_intent_id:null,stripe_charge_id:null});ef.session.status='expired';ef.session.payment_status='unpaid';
 const es=await adminState(a,expiredId),ex=installationStripeProjection(es,ep,ef.session,null,null,[],null);await a.json(rpc('ids_reconcile_installation_stripe',{p_id:expiredId,p_payment_id:ep.id,p_expected_ledger:es.ledger,p_balance_before:balance(es),p_balance_after:ex.balance,p_evidence:ex.evidence,p_refunds:[],p_event:{id:'evt_expired_'+ep.id,type:'controlled.expired',objectId:ef.session.id,created:null,receivedAt:new Date().toISOString(),hash:'b'.repeat(64)}}));assert.notEqual((await reserve(expiredId)).id,ep.id);assert.equal(balance(await adminState(a,expiredId)).netPaidCents,0);
 checks.push('expired unpaid checkout never credits money and permits a distinct fresh reservation');
 const acl=await a.json<any[]>("select json_agg(json_build_object('name',p.proname,'anon',has_function_privilege('anon',p.oid,'execute'),'authenticated',has_function_privilege('authenticated',p.oid,'execute'),'service',has_function_privilege('service_role',p.oid,'execute'))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('ids_reserve_installation_checkout','ids_attach_installation_checkout','ids_reserve_installation_refund','ids_reconcile_installation_stripe')");assert.equal(acl.length,4);for(const row of acl){assert.equal(row.anon,false);assert.equal(row.authenticated,false);assert.equal(row.service,true);}checks.push('effective processor RPC permissions deny browser roles and retain existing service-role execution');
 return{passed:true,evidence:'real PostgreSQL with controlled processor objects; no actual Stripe API calls',checks,connections:[aPid,bPid]};
}
