"use client";

import { type FormEvent, useEffect, useState } from "react";
import { DEFAULT_PRICE_MATCH, PRICE_MATCH_BUTTON_LABEL_MAX, PRICE_MATCH_DESCRIPTION_MAX, PRICE_MATCH_HEADING_MAX, type PriceMatchConfig } from "@/lib/price-match/config";

export default function PriceMatchAdmin() {
  const [authed, setAuthed] = useState<boolean | null>(null), [password, setPassword] = useState(""), [settings, setSettings] = useState(DEFAULT_PRICE_MATCH), [message, setMessage] = useState(""), [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/admin/price-match"); if (response.status === 401) return setAuthed(false); const payload = await response.json().catch(() => ({})); setAuthed(true); if (response.ok) setSettings(payload.settings); else setMessage(payload.error ?? "Settings could not be loaded."); }
  useEffect(() => { fetch("/api/admin/price-match").then(async response => { if (response.status === 401) { setAuthed(false); return; } const payload = await response.json().catch(() => ({})); setAuthed(true); if (response.ok) setSettings(payload.settings); else setMessage(payload.error ?? "Settings could not be loaded."); }); }, []);
  async function login(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/reviews/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); if (response.ok) { setPassword(""); setMessage(""); await load(); } else setMessage("Invalid password."); }
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/admin/price-match", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); const payload = await response.json().catch(() => ({})); setSaving(false); if (response.ok) { setSettings(payload.settings); setMessage("Meet or Beat section saved successfully."); } else setMessage(payload.error ?? "Save failed."); }
  const update = <K extends keyof PriceMatchConfig>(key: K, value: PriceMatchConfig[K]) => setSettings(current => ({ ...current, [key]: value }));
  if (authed === null) return <main className="min-h-screen bg-slate-100 p-6"><p className="mx-auto max-w-xl">Loading admin…</p></main>;
  if (!authed) return <main className="min-h-screen bg-slate-100 p-6 text-slate-950 md:p-10"><form onSubmit={login} className="mx-auto max-w-md rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="mt-2 text-4xl font-black">Meet or Beat</h1><label className="mt-7 block font-bold">Admin password<input type="password" required value={password} onChange={event => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label><button className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Sign In</button>{message && <p role="alert" className="mt-4 text-sm font-bold text-red-700">{message}</p>}</form></main>;
  return <main className="min-h-screen bg-slate-100 p-6 text-slate-950 md:p-10"><div className="mx-auto max-w-3xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">IDS Admin</p><h1 className="text-4xl font-black">Meet or Beat</h1></div><button onClick={async () => { await fetch("/api/admin/reviews/login", { method: "DELETE" }); setAuthed(false); }} className="rounded-xl border px-4 py-2 font-bold">Sign Out</button></div><form onSubmit={save} className="mt-7 space-y-6 rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><label className="flex items-center gap-3 font-bold"><input type="checkbox" checked={settings.enabled} onChange={event => update("enabled", event.target.checked)} className="h-5 w-5 accent-emerald-600" />Show this section on homepage</label><label className="block font-bold">Heading<textarea required maxLength={PRICE_MATCH_HEADING_MAX} rows={3} value={settings.heading} onChange={event => update("heading", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label><label className="block font-bold">Description<textarea required maxLength={PRICE_MATCH_DESCRIPTION_MAX} rows={5} value={settings.description} onChange={event => update("description", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label><label className="block font-bold">Button Label<input required maxLength={PRICE_MATCH_BUTTON_LABEL_MAX} value={settings.buttonLabel} onChange={event => update("buttonLabel", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 p-3" /></label><button disabled={saving} className="rounded-xl bg-emerald-600 px-6 py-3 font-black text-white disabled:opacity-60">{saving ? "Saving…" : "Save Changes"}</button>{message && <p role="status" className="font-bold text-slate-700">{message}</p>}</form></div></main>;
}
